/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gov.hoabinh.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ClipType service. Represents a row in the &quot;ClipType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.gov.hoabinh.model.impl.ClipTypeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.gov.hoabinh.model.impl.ClipTypeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ClipType
 * @see vn.gov.hoabinh.model.impl.ClipTypeImpl
 * @see vn.gov.hoabinh.model.impl.ClipTypeModelImpl
 * @generated
 */
@ProviderType
public interface ClipTypeModel extends BaseModel<ClipType>, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a clip type model instance should use the {@link ClipType} interface instead.
	 */

	/**
	 * Returns the primary key of this clip type.
	 *
	 * @return the primary key of this clip type
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this clip type.
	 *
	 * @param primaryKey the primary key of this clip type
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the ID of this clip type.
	 *
	 * @return the ID of this clip type
	 */
	@AutoEscape
	public String getId();

	/**
	 * Sets the ID of this clip type.
	 *
	 * @param id the ID of this clip type
	 */
	public void setId(String id);

	/**
	 * Returns the group ID of this clip type.
	 *
	 * @return the group ID of this clip type
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this clip type.
	 *
	 * @param groupId the group ID of this clip type
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this clip type.
	 *
	 * @return the company ID of this clip type
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this clip type.
	 *
	 * @param companyId the company ID of this clip type
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this clip type.
	 *
	 * @return the user ID of this clip type
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this clip type.
	 *
	 * @param userId the user ID of this clip type
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this clip type.
	 *
	 * @return the user uuid of this clip type
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this clip type.
	 *
	 * @param userUuid the user uuid of this clip type
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the created date of this clip type.
	 *
	 * @return the created date of this clip type
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this clip type.
	 *
	 * @param createdDate the created date of this clip type
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the modified date of this clip type.
	 *
	 * @return the modified date of this clip type
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this clip type.
	 *
	 * @param modifiedDate the modified date of this clip type
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the title of this clip type.
	 *
	 * @return the title of this clip type
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this clip type.
	 *
	 * @param title the title of this clip type
	 */
	public void setTitle(String title);

	/**
	 * Returns the name of this clip type.
	 *
	 * @return the name of this clip type
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this clip type.
	 *
	 * @param name the name of this clip type
	 */
	public void setName(String name);

	/**
	 * Returns the description of this clip type.
	 *
	 * @return the description of this clip type
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this clip type.
	 *
	 * @param description the description of this clip type
	 */
	public void setDescription(String description);

	/**
	 * Returns the active of this clip type.
	 *
	 * @return the active of this clip type
	 */
	public boolean getActive();

	/**
	 * Returns <code>true</code> if this clip type is active.
	 *
	 * @return <code>true</code> if this clip type is active; <code>false</code> otherwise
	 */
	public boolean isActive();

	/**
	 * Sets whether this clip type is active.
	 *
	 * @param active the active of this clip type
	 */
	public void setActive(boolean active);

	/**
	 * Returns the language of this clip type.
	 *
	 * @return the language of this clip type
	 */
	@AutoEscape
	public String getLanguage();

	/**
	 * Sets the language of this clip type.
	 *
	 * @param language the language of this clip type
	 */
	public void setLanguage(String language);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(vn.gov.hoabinh.model.ClipType clipType);

	@Override
	public int hashCode();

	@Override
	public CacheModel<vn.gov.hoabinh.model.ClipType> toCacheModel();

	@Override
	public vn.gov.hoabinh.model.ClipType toEscapedModel();

	@Override
	public vn.gov.hoabinh.model.ClipType toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}