/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gov.hoabinh.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the FAQAnswer service. Represents a row in the &quot;FAQAnswer&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.gov.hoabinh.model.impl.FAQAnswerModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.gov.hoabinh.model.impl.FAQAnswerImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FAQAnswer
 * @see vn.gov.hoabinh.model.impl.FAQAnswerImpl
 * @see vn.gov.hoabinh.model.impl.FAQAnswerModelImpl
 * @generated
 */
@ProviderType
public interface FAQAnswerModel extends BaseModel<FAQAnswer> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a f a q answer model instance should use the {@link FAQAnswer} interface instead.
	 */

	/**
	 * Returns the primary key of this f a q answer.
	 *
	 * @return the primary key of this f a q answer
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this f a q answer.
	 *
	 * @param primaryKey the primary key of this f a q answer
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this f a q answer.
	 *
	 * @return the ID of this f a q answer
	 */
	public long getId();

	/**
	 * Sets the ID of this f a q answer.
	 *
	 * @param id the ID of this f a q answer
	 */
	public void setId(long id);

	/**
	 * Returns the questionid of this f a q answer.
	 *
	 * @return the questionid of this f a q answer
	 */
	public long getQuestionid();

	/**
	 * Sets the questionid of this f a q answer.
	 *
	 * @param questionid the questionid of this f a q answer
	 */
	public void setQuestionid(long questionid);

	/**
	 * Returns the content of this f a q answer.
	 *
	 * @return the content of this f a q answer
	 */
	@AutoEscape
	public String getContent();

	/**
	 * Sets the content of this f a q answer.
	 *
	 * @param content the content of this f a q answer
	 */
	public void setContent(String content);

	/**
	 * Returns the answer order of this f a q answer.
	 *
	 * @return the answer order of this f a q answer
	 */
	public int getAnswerOrder();

	/**
	 * Sets the answer order of this f a q answer.
	 *
	 * @param answerOrder the answer order of this f a q answer
	 */
	public void setAnswerOrder(int answerOrder);

	/**
	 * Returns the answered by user of this f a q answer.
	 *
	 * @return the answered by user of this f a q answer
	 */
	@AutoEscape
	public String getAnsweredByUser();

	/**
	 * Sets the answered by user of this f a q answer.
	 *
	 * @param answeredByUser the answered by user of this f a q answer
	 */
	public void setAnsweredByUser(String answeredByUser);

	/**
	 * Returns the answered date of this f a q answer.
	 *
	 * @return the answered date of this f a q answer
	 */
	public Date getAnsweredDate();

	/**
	 * Sets the answered date of this f a q answer.
	 *
	 * @param answeredDate the answered date of this f a q answer
	 */
	public void setAnsweredDate(Date answeredDate);

	/**
	 * Returns the modified by user of this f a q answer.
	 *
	 * @return the modified by user of this f a q answer
	 */
	@AutoEscape
	public String getModifiedByUser();

	/**
	 * Sets the modified by user of this f a q answer.
	 *
	 * @param modifiedByUser the modified by user of this f a q answer
	 */
	public void setModifiedByUser(String modifiedByUser);

	/**
	 * Returns the language of this f a q answer.
	 *
	 * @return the language of this f a q answer
	 */
	@AutoEscape
	public String getLanguage();

	/**
	 * Sets the language of this f a q answer.
	 *
	 * @param language the language of this f a q answer
	 */
	public void setLanguage(String language);

	/**
	 * Returns the modified date of this f a q answer.
	 *
	 * @return the modified date of this f a q answer
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this f a q answer.
	 *
	 * @param modifiedDate the modified date of this f a q answer
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the approved of this f a q answer.
	 *
	 * @return the approved of this f a q answer
	 */
	public boolean getApproved();

	/**
	 * Returns <code>true</code> if this f a q answer is approved.
	 *
	 * @return <code>true</code> if this f a q answer is approved; <code>false</code> otherwise
	 */
	public boolean isApproved();

	/**
	 * Sets whether this f a q answer is approved.
	 *
	 * @param approved the approved of this f a q answer
	 */
	public void setApproved(boolean approved);

	/**
	 * Returns the approved by user of this f a q answer.
	 *
	 * @return the approved by user of this f a q answer
	 */
	@AutoEscape
	public String getApprovedByUser();

	/**
	 * Sets the approved by user of this f a q answer.
	 *
	 * @param approvedByUser the approved by user of this f a q answer
	 */
	public void setApprovedByUser(String approvedByUser);

	/**
	 * Returns the approved date of this f a q answer.
	 *
	 * @return the approved date of this f a q answer
	 */
	public Date getApprovedDate();

	/**
	 * Sets the approved date of this f a q answer.
	 *
	 * @param approvedDate the approved date of this f a q answer
	 */
	public void setApprovedDate(Date approvedDate);

	/**
	 * Returns the user ID of this f a q answer.
	 *
	 * @return the user ID of this f a q answer
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this f a q answer.
	 *
	 * @param userId the user ID of this f a q answer
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this f a q answer.
	 *
	 * @return the user uuid of this f a q answer
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this f a q answer.
	 *
	 * @param userUuid the user uuid of this f a q answer
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the attach name of this f a q answer.
	 *
	 * @return the attach name of this f a q answer
	 */
	@AutoEscape
	public String getAttachName();

	/**
	 * Sets the attach name of this f a q answer.
	 *
	 * @param attachName the attach name of this f a q answer
	 */
	public void setAttachName(String attachName);

	/**
	 * Returns the folder ID of this f a q answer.
	 *
	 * @return the folder ID of this f a q answer
	 */
	public long getFolderId();

	/**
	 * Sets the folder ID of this f a q answer.
	 *
	 * @param folderId the folder ID of this f a q answer
	 */
	public void setFolderId(long folderId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(vn.gov.hoabinh.model.FAQAnswer faqAnswer);

	@Override
	public int hashCode();

	@Override
	public CacheModel<vn.gov.hoabinh.model.FAQAnswer> toCacheModel();

	@Override
	public vn.gov.hoabinh.model.FAQAnswer toEscapedModel();

	@Override
	public vn.gov.hoabinh.model.FAQAnswer toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}