/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gov.hoabinh.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the FAQCategoryQuestion service. Represents a row in the &quot;FAQCategoryQuestion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.gov.hoabinh.model.impl.FAQCategoryQuestionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.gov.hoabinh.model.impl.FAQCategoryQuestionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FAQCategoryQuestion
 * @see vn.gov.hoabinh.model.impl.FAQCategoryQuestionImpl
 * @see vn.gov.hoabinh.model.impl.FAQCategoryQuestionModelImpl
 * @generated
 */
@ProviderType
public interface FAQCategoryQuestionModel extends BaseModel<FAQCategoryQuestion> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a f a q category question model instance should use the {@link FAQCategoryQuestion} interface instead.
	 */

	/**
	 * Returns the primary key of this f a q category question.
	 *
	 * @return the primary key of this f a q category question
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this f a q category question.
	 *
	 * @param primaryKey the primary key of this f a q category question
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this f a q category question.
	 *
	 * @return the ID of this f a q category question
	 */
	public long getId();

	/**
	 * Sets the ID of this f a q category question.
	 *
	 * @param id the ID of this f a q category question
	 */
	public void setId(long id);

	/**
	 * Returns the question ID of this f a q category question.
	 *
	 * @return the question ID of this f a q category question
	 */
	public long getQuestionId();

	/**
	 * Sets the question ID of this f a q category question.
	 *
	 * @param questionId the question ID of this f a q category question
	 */
	public void setQuestionId(long questionId);

	/**
	 * Returns the category ID of this f a q category question.
	 *
	 * @return the category ID of this f a q category question
	 */
	public long getCategoryId();

	/**
	 * Sets the category ID of this f a q category question.
	 *
	 * @param categoryId the category ID of this f a q category question
	 */
	public void setCategoryId(long categoryId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		vn.gov.hoabinh.model.FAQCategoryQuestion faqCategoryQuestion);

	@Override
	public int hashCode();

	@Override
	public CacheModel<vn.gov.hoabinh.model.FAQCategoryQuestion> toCacheModel();

	@Override
	public vn.gov.hoabinh.model.FAQCategoryQuestion toEscapedModel();

	@Override
	public vn.gov.hoabinh.model.FAQCategoryQuestion toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}