/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gov.hoabinh.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the FAQComment service. Represents a row in the &quot;FAQComment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.gov.hoabinh.model.impl.FAQCommentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.gov.hoabinh.model.impl.FAQCommentImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FAQComment
 * @see vn.gov.hoabinh.model.impl.FAQCommentImpl
 * @see vn.gov.hoabinh.model.impl.FAQCommentModelImpl
 * @generated
 */
@ProviderType
public interface FAQCommentModel extends BaseModel<FAQComment> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a f a q comment model instance should use the {@link FAQComment} interface instead.
	 */

	/**
	 * Returns the primary key of this f a q comment.
	 *
	 * @return the primary key of this f a q comment
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this f a q comment.
	 *
	 * @param primaryKey the primary key of this f a q comment
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this f a q comment.
	 *
	 * @return the ID of this f a q comment
	 */
	public long getId();

	/**
	 * Sets the ID of this f a q comment.
	 *
	 * @param id the ID of this f a q comment
	 */
	public void setId(long id);

	/**
	 * Returns the answerid of this f a q comment.
	 *
	 * @return the answerid of this f a q comment
	 */
	public long getAnswerid();

	/**
	 * Sets the answerid of this f a q comment.
	 *
	 * @param answerid the answerid of this f a q comment
	 */
	public void setAnswerid(long answerid);

	/**
	 * Returns the content of this f a q comment.
	 *
	 * @return the content of this f a q comment
	 */
	@AutoEscape
	public String getContent();

	/**
	 * Sets the content of this f a q comment.
	 *
	 * @param content the content of this f a q comment
	 */
	public void setContent(String content);

	/**
	 * Returns the comm name of this f a q comment.
	 *
	 * @return the comm name of this f a q comment
	 */
	@AutoEscape
	public String getCommName();

	/**
	 * Sets the comm name of this f a q comment.
	 *
	 * @param commName the comm name of this f a q comment
	 */
	public void setCommName(String commName);

	/**
	 * Returns the comm email of this f a q comment.
	 *
	 * @return the comm email of this f a q comment
	 */
	@AutoEscape
	public String getCommEmail();

	/**
	 * Sets the comm email of this f a q comment.
	 *
	 * @param commEmail the comm email of this f a q comment
	 */
	public void setCommEmail(String commEmail);

	/**
	 * Returns the approved of this f a q comment.
	 *
	 * @return the approved of this f a q comment
	 */
	public boolean getApproved();

	/**
	 * Returns <code>true</code> if this f a q comment is approved.
	 *
	 * @return <code>true</code> if this f a q comment is approved; <code>false</code> otherwise
	 */
	public boolean isApproved();

	/**
	 * Sets whether this f a q comment is approved.
	 *
	 * @param approved the approved of this f a q comment
	 */
	public void setApproved(boolean approved);

	/**
	 * Returns the approve by user of this f a q comment.
	 *
	 * @return the approve by user of this f a q comment
	 */
	@AutoEscape
	public String getApproveByUser();

	/**
	 * Sets the approve by user of this f a q comment.
	 *
	 * @param approveByUser the approve by user of this f a q comment
	 */
	public void setApproveByUser(String approveByUser);

	/**
	 * Returns the approved date of this f a q comment.
	 *
	 * @return the approved date of this f a q comment
	 */
	public Date getApprovedDate();

	/**
	 * Sets the approved date of this f a q comment.
	 *
	 * @param approvedDate the approved date of this f a q comment
	 */
	public void setApprovedDate(Date approvedDate);

	/**
	 * Returns the comm date of this f a q comment.
	 *
	 * @return the comm date of this f a q comment
	 */
	public Date getCommDate();

	/**
	 * Sets the comm date of this f a q comment.
	 *
	 * @param commDate the comm date of this f a q comment
	 */
	public void setCommDate(Date commDate);

	/**
	 * Returns the user ID of this f a q comment.
	 *
	 * @return the user ID of this f a q comment
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this f a q comment.
	 *
	 * @param userId the user ID of this f a q comment
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this f a q comment.
	 *
	 * @return the user uuid of this f a q comment
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this f a q comment.
	 *
	 * @param userUuid the user uuid of this f a q comment
	 */
	public void setUserUuid(String userUuid);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(vn.gov.hoabinh.model.FAQComment faqComment);

	@Override
	public int hashCode();

	@Override
	public CacheModel<vn.gov.hoabinh.model.FAQComment> toCacheModel();

	@Override
	public vn.gov.hoabinh.model.FAQComment toEscapedModel();

	@Override
	public vn.gov.hoabinh.model.FAQComment toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}