/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gov.hoabinh.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the FAQCategory service. Represents a row in the &quot;FAQCategory&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.gov.hoabinh.model.impl.FAQCategoryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.gov.hoabinh.model.impl.FAQCategoryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FAQCategory
 * @see vn.gov.hoabinh.model.impl.FAQCategoryImpl
 * @see vn.gov.hoabinh.model.impl.FAQCategoryModelImpl
 * @generated
 */
@ProviderType
public interface FAQCategoryModel extends BaseModel<FAQCategory> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a f a q category model instance should use the {@link FAQCategory} interface instead.
	 */

	/**
	 * Returns the primary key of this f a q category.
	 *
	 * @return the primary key of this f a q category
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this f a q category.
	 *
	 * @param primaryKey the primary key of this f a q category
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this f a q category.
	 *
	 * @return the ID of this f a q category
	 */
	public long getId();

	/**
	 * Sets the ID of this f a q category.
	 *
	 * @param id the ID of this f a q category
	 */
	public void setId(long id);

	/**
	 * Returns the name of this f a q category.
	 *
	 * @return the name of this f a q category
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this f a q category.
	 *
	 * @param name the name of this f a q category
	 */
	public void setName(String name);

	/**
	 * Returns the description of this f a q category.
	 *
	 * @return the description of this f a q category
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this f a q category.
	 *
	 * @param description the description of this f a q category
	 */
	public void setDescription(String description);

	/**
	 * Returns the language of this f a q category.
	 *
	 * @return the language of this f a q category
	 */
	@AutoEscape
	public String getLanguage();

	/**
	 * Sets the language of this f a q category.
	 *
	 * @param language the language of this f a q category
	 */
	public void setLanguage(String language);

	/**
	 * Returns the parent of this f a q category.
	 *
	 * @return the parent of this f a q category
	 */
	public long getParent();

	/**
	 * Sets the parent of this f a q category.
	 *
	 * @param parent the parent of this f a q category
	 */
	public void setParent(long parent);

	/**
	 * Returns the catorder of this f a q category.
	 *
	 * @return the catorder of this f a q category
	 */
	public int getCatorder();

	/**
	 * Sets the catorder of this f a q category.
	 *
	 * @param catorder the catorder of this f a q category
	 */
	public void setCatorder(int catorder);

	/**
	 * Returns the catlevel of this f a q category.
	 *
	 * @return the catlevel of this f a q category
	 */
	public int getCatlevel();

	/**
	 * Sets the catlevel of this f a q category.
	 *
	 * @param catlevel the catlevel of this f a q category
	 */
	public void setCatlevel(int catlevel);

	/**
	 * Returns the image of this f a q category.
	 *
	 * @return the image of this f a q category
	 */
	@AutoEscape
	public String getImage();

	/**
	 * Sets the image of this f a q category.
	 *
	 * @param image the image of this f a q category
	 */
	public void setImage(String image);

	/**
	 * Returns the created by user of this f a q category.
	 *
	 * @return the created by user of this f a q category
	 */
	@AutoEscape
	public String getCreatedByUser();

	/**
	 * Sets the created by user of this f a q category.
	 *
	 * @param createdByUser the created by user of this f a q category
	 */
	public void setCreatedByUser(String createdByUser);

	/**
	 * Returns the created date of this f a q category.
	 *
	 * @return the created date of this f a q category
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this f a q category.
	 *
	 * @param createdDate the created date of this f a q category
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the modified by user of this f a q category.
	 *
	 * @return the modified by user of this f a q category
	 */
	@AutoEscape
	public String getModifiedByUser();

	/**
	 * Sets the modified by user of this f a q category.
	 *
	 * @param modifiedByUser the modified by user of this f a q category
	 */
	public void setModifiedByUser(String modifiedByUser);

	/**
	 * Returns the modified date of this f a q category.
	 *
	 * @return the modified date of this f a q category
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this f a q category.
	 *
	 * @param modifiedDate the modified date of this f a q category
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the group ID of this f a q category.
	 *
	 * @return the group ID of this f a q category
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this f a q category.
	 *
	 * @param groupId the group ID of this f a q category
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this f a q category.
	 *
	 * @return the user ID of this f a q category
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this f a q category.
	 *
	 * @param userId the user ID of this f a q category
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this f a q category.
	 *
	 * @return the user uuid of this f a q category
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this f a q category.
	 *
	 * @param userUuid the user uuid of this f a q category
	 */
	public void setUserUuid(String userUuid);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(vn.gov.hoabinh.model.FAQCategory faqCategory);

	@Override
	public int hashCode();

	@Override
	public CacheModel<vn.gov.hoabinh.model.FAQCategory> toCacheModel();

	@Override
	public vn.gov.hoabinh.model.FAQCategory toEscapedModel();

	@Override
	public vn.gov.hoabinh.model.FAQCategory toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}