/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gov.hoabinh.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the LinkGroup service. Represents a row in the &quot;LinkGroup&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.gov.hoabinh.model.impl.LinkGroupModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.gov.hoabinh.model.impl.LinkGroupImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LinkGroup
 * @see vn.gov.hoabinh.model.impl.LinkGroupImpl
 * @see vn.gov.hoabinh.model.impl.LinkGroupModelImpl
 * @generated
 */
@ProviderType
public interface LinkGroupModel extends BaseModel<LinkGroup>, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a link group model instance should use the {@link LinkGroup} interface instead.
	 */

	/**
	 * Returns the primary key of this link group.
	 *
	 * @return the primary key of this link group
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this link group.
	 *
	 * @param primaryKey the primary key of this link group
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the linkgroup ID of this link group.
	 *
	 * @return the linkgroup ID of this link group
	 */
	public long getLinkgroupId();

	/**
	 * Sets the linkgroup ID of this link group.
	 *
	 * @param linkgroupId the linkgroup ID of this link group
	 */
	public void setLinkgroupId(long linkgroupId);

	/**
	 * Returns the group ID of this link group.
	 *
	 * @return the group ID of this link group
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this link group.
	 *
	 * @param groupId the group ID of this link group
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this link group.
	 *
	 * @return the company ID of this link group
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this link group.
	 *
	 * @param companyId the company ID of this link group
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the created date of this link group.
	 *
	 * @return the created date of this link group
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this link group.
	 *
	 * @param createdDate the created date of this link group
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the modified date of this link group.
	 *
	 * @return the modified date of this link group
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this link group.
	 *
	 * @param modifiedDate the modified date of this link group
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this link group.
	 *
	 * @return the name of this link group
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this link group.
	 *
	 * @param name the name of this link group
	 */
	public void setName(String name);

	/**
	 * Returns the description of this link group.
	 *
	 * @return the description of this link group
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this link group.
	 *
	 * @param description the description of this link group
	 */
	public void setDescription(String description);

	/**
	 * Returns the position of this link group.
	 *
	 * @return the position of this link group
	 */
	public int getPosition();

	/**
	 * Sets the position of this link group.
	 *
	 * @param position the position of this link group
	 */
	public void setPosition(int position);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(vn.gov.hoabinh.model.LinkGroup linkGroup);

	@Override
	public int hashCode();

	@Override
	public CacheModel<vn.gov.hoabinh.model.LinkGroup> toCacheModel();

	@Override
	public vn.gov.hoabinh.model.LinkGroup toEscapedModel();

	@Override
	public vn.gov.hoabinh.model.LinkGroup toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}