/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gov.hoabinh.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VcmsArticleRating service. Represents a row in the &quot;VcmsArticleRating&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.gov.hoabinh.model.impl.VcmsArticleRatingModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.gov.hoabinh.model.impl.VcmsArticleRatingImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see VcmsArticleRating
 * @see vn.gov.hoabinh.model.impl.VcmsArticleRatingImpl
 * @see vn.gov.hoabinh.model.impl.VcmsArticleRatingModelImpl
 * @generated
 */
@ProviderType
public interface VcmsArticleRatingModel extends BaseModel<VcmsArticleRating> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a vcms article rating model instance should use the {@link VcmsArticleRating} interface instead.
	 */

	/**
	 * Returns the primary key of this vcms article rating.
	 *
	 * @return the primary key of this vcms article rating
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this vcms article rating.
	 *
	 * @param primaryKey the primary key of this vcms article rating
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this vcms article rating.
	 *
	 * @return the ID of this vcms article rating
	 */
	public long getId();

	/**
	 * Sets the ID of this vcms article rating.
	 *
	 * @param Id the ID of this vcms article rating
	 */
	public void setId(long Id);

	/**
	 * Returns the created date of this vcms article rating.
	 *
	 * @return the created date of this vcms article rating
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this vcms article rating.
	 *
	 * @param createdDate the created date of this vcms article rating
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the article ID of this vcms article rating.
	 *
	 * @return the article ID of this vcms article rating
	 */
	public long getArticleId();

	/**
	 * Sets the article ID of this vcms article rating.
	 *
	 * @param articleId the article ID of this vcms article rating
	 */
	public void setArticleId(long articleId);

	/**
	 * Returns the rating of this vcms article rating.
	 *
	 * @return the rating of this vcms article rating
	 */
	public int getRating();

	/**
	 * Sets the rating of this vcms article rating.
	 *
	 * @param rating the rating of this vcms article rating
	 */
	public void setRating(int rating);

	/**
	 * Returns the session ID of this vcms article rating.
	 *
	 * @return the session ID of this vcms article rating
	 */
	@AutoEscape
	public String getSessionId();

	/**
	 * Sets the session ID of this vcms article rating.
	 *
	 * @param sessionId the session ID of this vcms article rating
	 */
	public void setSessionId(String sessionId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		vn.gov.hoabinh.model.VcmsArticleRating vcmsArticleRating);

	@Override
	public int hashCode();

	@Override
	public CacheModel<vn.gov.hoabinh.model.VcmsArticleRating> toCacheModel();

	@Override
	public vn.gov.hoabinh.model.VcmsArticleRating toEscapedModel();

	@Override
	public vn.gov.hoabinh.model.VcmsArticleRating toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}