/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gov.hoabinh.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VcmsType service. Represents a row in the &quot;VcmsType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.gov.hoabinh.model.impl.VcmsTypeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.gov.hoabinh.model.impl.VcmsTypeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see VcmsType
 * @see vn.gov.hoabinh.model.impl.VcmsTypeImpl
 * @see vn.gov.hoabinh.model.impl.VcmsTypeModelImpl
 * @generated
 */
@ProviderType
public interface VcmsTypeModel extends BaseModel<VcmsType>, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a vcms type model instance should use the {@link VcmsType} interface instead.
	 */

	/**
	 * Returns the primary key of this vcms type.
	 *
	 * @return the primary key of this vcms type
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this vcms type.
	 *
	 * @param primaryKey the primary key of this vcms type
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the type ID of this vcms type.
	 *
	 * @return the type ID of this vcms type
	 */
	public long getTypeId();

	/**
	 * Sets the type ID of this vcms type.
	 *
	 * @param typeId the type ID of this vcms type
	 */
	public void setTypeId(long typeId);

	/**
	 * Returns the group ID of this vcms type.
	 *
	 * @return the group ID of this vcms type
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this vcms type.
	 *
	 * @param groupId the group ID of this vcms type
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this vcms type.
	 *
	 * @return the company ID of this vcms type
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this vcms type.
	 *
	 * @param companyId the company ID of this vcms type
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the created date of this vcms type.
	 *
	 * @return the created date of this vcms type
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this vcms type.
	 *
	 * @param createdDate the created date of this vcms type
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the created by user of this vcms type.
	 *
	 * @return the created by user of this vcms type
	 */
	@AutoEscape
	public String getCreatedByUser();

	/**
	 * Sets the created by user of this vcms type.
	 *
	 * @param createdByUser the created by user of this vcms type
	 */
	public void setCreatedByUser(String createdByUser);

	/**
	 * Returns the modified date of this vcms type.
	 *
	 * @return the modified date of this vcms type
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this vcms type.
	 *
	 * @param modifiedDate the modified date of this vcms type
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the modified by user of this vcms type.
	 *
	 * @return the modified by user of this vcms type
	 */
	@AutoEscape
	public String getModifiedByUser();

	/**
	 * Sets the modified by user of this vcms type.
	 *
	 * @param modifiedByUser the modified by user of this vcms type
	 */
	public void setModifiedByUser(String modifiedByUser);

	/**
	 * Returns the code of this vcms type.
	 *
	 * @return the code of this vcms type
	 */
	@AutoEscape
	public String getCode();

	/**
	 * Sets the code of this vcms type.
	 *
	 * @param code the code of this vcms type
	 */
	public void setCode(String code);

	/**
	 * Returns the name of this vcms type.
	 *
	 * @return the name of this vcms type
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this vcms type.
	 *
	 * @param name the name of this vcms type
	 */
	public void setName(String name);

	/**
	 * Returns the description of this vcms type.
	 *
	 * @return the description of this vcms type
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this vcms type.
	 *
	 * @param description the description of this vcms type
	 */
	public void setDescription(String description);

	/**
	 * Returns the language of this vcms type.
	 *
	 * @return the language of this vcms type
	 */
	@AutoEscape
	public String getLanguage();

	/**
	 * Sets the language of this vcms type.
	 *
	 * @param language the language of this vcms type
	 */
	public void setLanguage(String language);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(vn.gov.hoabinh.model.VcmsType vcmsType);

	@Override
	public int hashCode();

	@Override
	public CacheModel<vn.gov.hoabinh.model.VcmsType> toCacheModel();

	@Override
	public vn.gov.hoabinh.model.VcmsType toEscapedModel();

	@Override
	public vn.gov.hoabinh.model.VcmsType toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}