/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gov.hoabinh.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VcmsLogger service. Represents a row in the &quot;VcmsLogger&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.gov.hoabinh.model.impl.VcmsLoggerModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.gov.hoabinh.model.impl.VcmsLoggerImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see VcmsLogger
 * @see vn.gov.hoabinh.model.impl.VcmsLoggerImpl
 * @see vn.gov.hoabinh.model.impl.VcmsLoggerModelImpl
 * @generated
 */
@ProviderType
public interface VcmsLoggerModel extends BaseModel<VcmsLogger>, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a vcms logger model instance should use the {@link VcmsLogger} interface instead.
	 */

	/**
	 * Returns the primary key of this vcms logger.
	 *
	 * @return the primary key of this vcms logger
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this vcms logger.
	 *
	 * @param primaryKey the primary key of this vcms logger
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the logger ID of this vcms logger.
	 *
	 * @return the logger ID of this vcms logger
	 */
	@AutoEscape
	public String getLoggerId();

	/**
	 * Sets the logger ID of this vcms logger.
	 *
	 * @param loggerId the logger ID of this vcms logger
	 */
	public void setLoggerId(String loggerId);

	/**
	 * Returns the group ID of this vcms logger.
	 *
	 * @return the group ID of this vcms logger
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this vcms logger.
	 *
	 * @param groupId the group ID of this vcms logger
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this vcms logger.
	 *
	 * @return the company ID of this vcms logger
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this vcms logger.
	 *
	 * @param companyId the company ID of this vcms logger
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the entry ID of this vcms logger.
	 *
	 * @return the entry ID of this vcms logger
	 */
	@AutoEscape
	public String getEntryId();

	/**
	 * Sets the entry ID of this vcms logger.
	 *
	 * @param entryId the entry ID of this vcms logger
	 */
	public void setEntryId(String entryId);

	/**
	 * Returns the created date of this vcms logger.
	 *
	 * @return the created date of this vcms logger
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this vcms logger.
	 *
	 * @param createdDate the created date of this vcms logger
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the created by user of this vcms logger.
	 *
	 * @return the created by user of this vcms logger
	 */
	@AutoEscape
	public String getCreatedByUser();

	/**
	 * Sets the created by user of this vcms logger.
	 *
	 * @param createdByUser the created by user of this vcms logger
	 */
	public void setCreatedByUser(String createdByUser);

	/**
	 * Returns the class entry of this vcms logger.
	 *
	 * @return the class entry of this vcms logger
	 */
	@AutoEscape
	public String getClassEntry();

	/**
	 * Sets the class entry of this vcms logger.
	 *
	 * @param classEntry the class entry of this vcms logger
	 */
	public void setClassEntry(String classEntry);

	/**
	 * Returns the content of this vcms logger.
	 *
	 * @return the content of this vcms logger
	 */
	@AutoEscape
	public String getContent();

	/**
	 * Sets the content of this vcms logger.
	 *
	 * @param content the content of this vcms logger
	 */
	public void setContent(String content);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(vn.gov.hoabinh.model.VcmsLogger vcmsLogger);

	@Override
	public int hashCode();

	@Override
	public CacheModel<vn.gov.hoabinh.model.VcmsLogger> toCacheModel();

	@Override
	public vn.gov.hoabinh.model.VcmsLogger toEscapedModel();

	@Override
	public vn.gov.hoabinh.model.VcmsLogger toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}