/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gov.hoabinh.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import vn.gov.hoabinh.service.persistence.VcmsPARelationPK;

import java.io.Serializable;

/**
 * The base model interface for the VcmsPARelation service. Represents a row in the &quot;VcmsPARelation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.gov.hoabinh.model.impl.VcmsPARelationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.gov.hoabinh.model.impl.VcmsPARelationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see VcmsPARelation
 * @see vn.gov.hoabinh.model.impl.VcmsPARelationImpl
 * @see vn.gov.hoabinh.model.impl.VcmsPARelationModelImpl
 * @generated
 */
@ProviderType
public interface VcmsPARelationModel extends BaseModel<VcmsPARelation> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a vcms p a relation model instance should use the {@link VcmsPARelation} interface instead.
	 */

	/**
	 * Returns the primary key of this vcms p a relation.
	 *
	 * @return the primary key of this vcms p a relation
	 */
	public VcmsPARelationPK getPrimaryKey();

	/**
	 * Sets the primary key of this vcms p a relation.
	 *
	 * @param primaryKey the primary key of this vcms p a relation
	 */
	public void setPrimaryKey(VcmsPARelationPK primaryKey);

	/**
	 * Returns the portion ID of this vcms p a relation.
	 *
	 * @return the portion ID of this vcms p a relation
	 */
	@AutoEscape
	public String getPortionId();

	/**
	 * Sets the portion ID of this vcms p a relation.
	 *
	 * @param portionId the portion ID of this vcms p a relation
	 */
	public void setPortionId(String portionId);

	/**
	 * Returns the article ID of this vcms p a relation.
	 *
	 * @return the article ID of this vcms p a relation
	 */
	@AutoEscape
	public String getArticleId();

	/**
	 * Sets the article ID of this vcms p a relation.
	 *
	 * @param articleId the article ID of this vcms p a relation
	 */
	public void setArticleId(String articleId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(vn.gov.hoabinh.model.VcmsPARelation vcmsPARelation);

	@Override
	public int hashCode();

	@Override
	public CacheModel<vn.gov.hoabinh.model.VcmsPARelation> toCacheModel();

	@Override
	public vn.gov.hoabinh.model.VcmsPARelation toEscapedModel();

	@Override
	public vn.gov.hoabinh.model.VcmsPARelation toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}