/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gov.hoabinh.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import vn.gov.hoabinh.service.persistence.VcmsCURelationPK;

import java.io.Serializable;

/**
 * The base model interface for the VcmsCURelation service. Represents a row in the &quot;VcmsCURelation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.gov.hoabinh.model.impl.VcmsCURelationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.gov.hoabinh.model.impl.VcmsCURelationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see VcmsCURelation
 * @see vn.gov.hoabinh.model.impl.VcmsCURelationImpl
 * @see vn.gov.hoabinh.model.impl.VcmsCURelationModelImpl
 * @generated
 */
@ProviderType
public interface VcmsCURelationModel extends BaseModel<VcmsCURelation> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a vcms c u relation model instance should use the {@link VcmsCURelation} interface instead.
	 */

	/**
	 * Returns the primary key of this vcms c u relation.
	 *
	 * @return the primary key of this vcms c u relation
	 */
	public VcmsCURelationPK getPrimaryKey();

	/**
	 * Sets the primary key of this vcms c u relation.
	 *
	 * @param primaryKey the primary key of this vcms c u relation
	 */
	public void setPrimaryKey(VcmsCURelationPK primaryKey);

	/**
	 * Returns the category ID of this vcms c u relation.
	 *
	 * @return the category ID of this vcms c u relation
	 */
	@AutoEscape
	public String getCategoryId();

	/**
	 * Sets the category ID of this vcms c u relation.
	 *
	 * @param categoryId the category ID of this vcms c u relation
	 */
	public void setCategoryId(String categoryId);

	/**
	 * Returns the user ID of this vcms c u relation.
	 *
	 * @return the user ID of this vcms c u relation
	 */
	@AutoEscape
	public String getUserId();

	/**
	 * Sets the user ID of this vcms c u relation.
	 *
	 * @param userId the user ID of this vcms c u relation
	 */
	public void setUserId(String userId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(vn.gov.hoabinh.model.VcmsCURelation vcmsCURelation);

	@Override
	public int hashCode();

	@Override
	public CacheModel<vn.gov.hoabinh.model.VcmsCURelation> toCacheModel();

	@Override
	public vn.gov.hoabinh.model.VcmsCURelation toEscapedModel();

	@Override
	public vn.gov.hoabinh.model.VcmsCURelation toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}