/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gov.hoabinh.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import vn.gov.hoabinh.service.persistence.VcmsArticleStatusPK;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VcmsArticleStatus service. Represents a row in the &quot;VcmsArticleStatus&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.gov.hoabinh.model.impl.VcmsArticleStatusModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.gov.hoabinh.model.impl.VcmsArticleStatusImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see VcmsArticleStatus
 * @see vn.gov.hoabinh.model.impl.VcmsArticleStatusImpl
 * @see vn.gov.hoabinh.model.impl.VcmsArticleStatusModelImpl
 * @generated
 */
@ProviderType
public interface VcmsArticleStatusModel extends BaseModel<VcmsArticleStatus> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a vcms article status model instance should use the {@link VcmsArticleStatus} interface instead.
	 */

	/**
	 * Returns the primary key of this vcms article status.
	 *
	 * @return the primary key of this vcms article status
	 */
	public VcmsArticleStatusPK getPrimaryKey();

	/**
	 * Sets the primary key of this vcms article status.
	 *
	 * @param primaryKey the primary key of this vcms article status
	 */
	public void setPrimaryKey(VcmsArticleStatusPK primaryKey);

	/**
	 * Returns the status ID of this vcms article status.
	 *
	 * @return the status ID of this vcms article status
	 */
	public long getStatusId();

	/**
	 * Sets the status ID of this vcms article status.
	 *
	 * @param statusId the status ID of this vcms article status
	 */
	public void setStatusId(long statusId);

	/**
	 * Returns the article ID of this vcms article status.
	 *
	 * @return the article ID of this vcms article status
	 */
	@AutoEscape
	public String getArticleId();

	/**
	 * Sets the article ID of this vcms article status.
	 *
	 * @param articleId the article ID of this vcms article status
	 */
	public void setArticleId(String articleId);

	/**
	 * Returns the category ID of this vcms article status.
	 *
	 * @return the category ID of this vcms article status
	 */
	@AutoEscape
	public String getCategoryId();

	/**
	 * Sets the category ID of this vcms article status.
	 *
	 * @param categoryId the category ID of this vcms article status
	 */
	public void setCategoryId(String categoryId);

	/**
	 * Returns the created date of this vcms article status.
	 *
	 * @return the created date of this vcms article status
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this vcms article status.
	 *
	 * @param createdDate the created date of this vcms article status
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the created by user of this vcms article status.
	 *
	 * @return the created by user of this vcms article status
	 */
	@AutoEscape
	public String getCreatedByUser();

	/**
	 * Sets the created by user of this vcms article status.
	 *
	 * @param createdByUser the created by user of this vcms article status
	 */
	public void setCreatedByUser(String createdByUser);

	/**
	 * Returns the active of this vcms article status.
	 *
	 * @return the active of this vcms article status
	 */
	public boolean getActive();

	/**
	 * Returns <code>true</code> if this vcms article status is active.
	 *
	 * @return <code>true</code> if this vcms article status is active; <code>false</code> otherwise
	 */
	public boolean isActive();

	/**
	 * Sets whether this vcms article status is active.
	 *
	 * @param active the active of this vcms article status
	 */
	public void setActive(boolean active);

	/**
	 * Returns the article version ID of this vcms article status.
	 *
	 * @return the article version ID of this vcms article status
	 */
	public long getArticleVersionId();

	/**
	 * Sets the article version ID of this vcms article status.
	 *
	 * @param articleVersionId the article version ID of this vcms article status
	 */
	public void setArticleVersionId(long articleVersionId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		vn.gov.hoabinh.model.VcmsArticleStatus vcmsArticleStatus);

	@Override
	public int hashCode();

	@Override
	public CacheModel<vn.gov.hoabinh.model.VcmsArticleStatus> toCacheModel();

	@Override
	public vn.gov.hoabinh.model.VcmsArticleStatus toEscapedModel();

	@Override
	public vn.gov.hoabinh.model.VcmsArticleStatus toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}