/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gov.hoabinh.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import vn.gov.hoabinh.service.persistence.VcmsCARelationPK;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VcmsCARelation service. Represents a row in the &quot;VcmsCARelation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.gov.hoabinh.model.impl.VcmsCARelationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.gov.hoabinh.model.impl.VcmsCARelationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see VcmsCARelation
 * @see vn.gov.hoabinh.model.impl.VcmsCARelationImpl
 * @see vn.gov.hoabinh.model.impl.VcmsCARelationModelImpl
 * @generated
 */
@ProviderType
public interface VcmsCARelationModel extends BaseModel<VcmsCARelation> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a vcms c a relation model instance should use the {@link VcmsCARelation} interface instead.
	 */

	/**
	 * Returns the primary key of this vcms c a relation.
	 *
	 * @return the primary key of this vcms c a relation
	 */
	public VcmsCARelationPK getPrimaryKey();

	/**
	 * Sets the primary key of this vcms c a relation.
	 *
	 * @param primaryKey the primary key of this vcms c a relation
	 */
	public void setPrimaryKey(VcmsCARelationPK primaryKey);

	/**
	 * Returns the category ID of this vcms c a relation.
	 *
	 * @return the category ID of this vcms c a relation
	 */
	@AutoEscape
	public String getCategoryId();

	/**
	 * Sets the category ID of this vcms c a relation.
	 *
	 * @param categoryId the category ID of this vcms c a relation
	 */
	public void setCategoryId(String categoryId);

	/**
	 * Returns the article ID of this vcms c a relation.
	 *
	 * @return the article ID of this vcms c a relation
	 */
	@AutoEscape
	public String getArticleId();

	/**
	 * Sets the article ID of this vcms c a relation.
	 *
	 * @param articleId the article ID of this vcms c a relation
	 */
	public void setArticleId(String articleId);

	/**
	 * Returns the created date of this vcms c a relation.
	 *
	 * @return the created date of this vcms c a relation
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this vcms c a relation.
	 *
	 * @param createdDate the created date of this vcms c a relation
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the created by user of this vcms c a relation.
	 *
	 * @return the created by user of this vcms c a relation
	 */
	@AutoEscape
	public String getCreatedByUser();

	/**
	 * Sets the created by user of this vcms c a relation.
	 *
	 * @param createdByUser the created by user of this vcms c a relation
	 */
	public void setCreatedByUser(String createdByUser);

	/**
	 * Returns the status of this vcms c a relation.
	 *
	 * @return the status of this vcms c a relation
	 */
	public long getStatus();

	/**
	 * Sets the status of this vcms c a relation.
	 *
	 * @param status the status of this vcms c a relation
	 */
	public void setStatus(long status);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(vn.gov.hoabinh.model.VcmsCARelation vcmsCARelation);

	@Override
	public int hashCode();

	@Override
	public CacheModel<vn.gov.hoabinh.model.VcmsCARelation> toCacheModel();

	@Override
	public vn.gov.hoabinh.model.VcmsCARelation toEscapedModel();

	@Override
	public vn.gov.hoabinh.model.VcmsCARelation toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}