/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gov.hoabinh.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VContact service. Represents a row in the &quot;VContact&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.gov.hoabinh.model.impl.VContactModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.gov.hoabinh.model.impl.VContactImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see VContact
 * @see vn.gov.hoabinh.model.impl.VContactImpl
 * @see vn.gov.hoabinh.model.impl.VContactModelImpl
 * @generated
 */
@ProviderType
public interface VContactModel extends BaseModel<VContact>, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a v contact model instance should use the {@link VContact} interface instead.
	 */

	/**
	 * Returns the primary key of this v contact.
	 *
	 * @return the primary key of this v contact
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this v contact.
	 *
	 * @param primaryKey the primary key of this v contact
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this v contact.
	 *
	 * @return the ID of this v contact
	 */
	public long getId();

	/**
	 * Sets the ID of this v contact.
	 *
	 * @param id the ID of this v contact
	 */
	public void setId(long id);

	/**
	 * Returns the group ID of this v contact.
	 *
	 * @return the group ID of this v contact
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this v contact.
	 *
	 * @param groupId the group ID of this v contact
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this v contact.
	 *
	 * @return the company ID of this v contact
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this v contact.
	 *
	 * @param companyId the company ID of this v contact
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the created date of this v contact.
	 *
	 * @return the created date of this v contact
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this v contact.
	 *
	 * @param createdDate the created date of this v contact
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the modified date of this v contact.
	 *
	 * @return the modified date of this v contact
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this v contact.
	 *
	 * @param modifiedDate the modified date of this v contact
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the guest name of this v contact.
	 *
	 * @return the guest name of this v contact
	 */
	@AutoEscape
	public String getGuestName();

	/**
	 * Sets the guest name of this v contact.
	 *
	 * @param guestName the guest name of this v contact
	 */
	public void setGuestName(String guestName);

	/**
	 * Returns the email of this v contact.
	 *
	 * @return the email of this v contact
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this v contact.
	 *
	 * @param email the email of this v contact
	 */
	public void setEmail(String email);

	/**
	 * Returns the title of this v contact.
	 *
	 * @return the title of this v contact
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this v contact.
	 *
	 * @param title the title of this v contact
	 */
	public void setTitle(String title);

	/**
	 * Returns the address of this v contact.
	 *
	 * @return the address of this v contact
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this v contact.
	 *
	 * @param address the address of this v contact
	 */
	public void setAddress(String address);

	/**
	 * Returns the phone of this v contact.
	 *
	 * @return the phone of this v contact
	 */
	@AutoEscape
	public String getPhone();

	/**
	 * Sets the phone of this v contact.
	 *
	 * @param phone the phone of this v contact
	 */
	public void setPhone(String phone);

	/**
	 * Returns the fax of this v contact.
	 *
	 * @return the fax of this v contact
	 */
	@AutoEscape
	public String getFax();

	/**
	 * Sets the fax of this v contact.
	 *
	 * @param fax the fax of this v contact
	 */
	public void setFax(String fax);

	/**
	 * Returns the content of this v contact.
	 *
	 * @return the content of this v contact
	 */
	@AutoEscape
	public String getContent();

	/**
	 * Sets the content of this v contact.
	 *
	 * @param content the content of this v contact
	 */
	public void setContent(String content);

	/**
	 * Returns the has attach of this v contact.
	 *
	 * @return the has attach of this v contact
	 */
	public boolean getHasAttach();

	/**
	 * Returns <code>true</code> if this v contact is has attach.
	 *
	 * @return <code>true</code> if this v contact is has attach; <code>false</code> otherwise
	 */
	public boolean isHasAttach();

	/**
	 * Sets whether this v contact is has attach.
	 *
	 * @param hasAttach the has attach of this v contact
	 */
	public void setHasAttach(boolean hasAttach);

	/**
	 * Returns the status of this v contact.
	 *
	 * @return the status of this v contact
	 */
	public int getStatus();

	/**
	 * Sets the status of this v contact.
	 *
	 * @param status the status of this v contact
	 */
	public void setStatus(int status);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(vn.gov.hoabinh.model.VContact vContact);

	@Override
	public int hashCode();

	@Override
	public CacheModel<vn.gov.hoabinh.model.VContact> toCacheModel();

	@Override
	public vn.gov.hoabinh.model.VContact toEscapedModel();

	@Override
	public vn.gov.hoabinh.model.VContact toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}