/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gov.hoabinh.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the vdocField service. Represents a row in the &quot;vdocField&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.gov.hoabinh.model.impl.vdocFieldModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.gov.hoabinh.model.impl.vdocFieldImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see vdocField
 * @see vn.gov.hoabinh.model.impl.vdocFieldImpl
 * @see vn.gov.hoabinh.model.impl.vdocFieldModelImpl
 * @generated
 */
@ProviderType
public interface vdocFieldModel extends BaseModel<vdocField>, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a vdoc field model instance should use the {@link vdocField} interface instead.
	 */

	/**
	 * Returns the primary key of this vdoc field.
	 *
	 * @return the primary key of this vdoc field
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this vdoc field.
	 *
	 * @param primaryKey the primary key of this vdoc field
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the field ID of this vdoc field.
	 *
	 * @return the field ID of this vdoc field
	 */
	@AutoEscape
	public String getFieldId();

	/**
	 * Sets the field ID of this vdoc field.
	 *
	 * @param fieldId the field ID of this vdoc field
	 */
	public void setFieldId(String fieldId);

	/**
	 * Returns the group ID of this vdoc field.
	 *
	 * @return the group ID of this vdoc field
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this vdoc field.
	 *
	 * @param groupId the group ID of this vdoc field
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this vdoc field.
	 *
	 * @return the company ID of this vdoc field
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this vdoc field.
	 *
	 * @param companyId the company ID of this vdoc field
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this vdoc field.
	 *
	 * @return the user ID of this vdoc field
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this vdoc field.
	 *
	 * @param userId the user ID of this vdoc field
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this vdoc field.
	 *
	 * @return the user uuid of this vdoc field
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this vdoc field.
	 *
	 * @param userUuid the user uuid of this vdoc field
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the created date of this vdoc field.
	 *
	 * @return the created date of this vdoc field
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this vdoc field.
	 *
	 * @param createdDate the created date of this vdoc field
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the modified date of this vdoc field.
	 *
	 * @return the modified date of this vdoc field
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this vdoc field.
	 *
	 * @param modifiedDate the modified date of this vdoc field
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the created by user of this vdoc field.
	 *
	 * @return the created by user of this vdoc field
	 */
	public long getCreatedByUser();

	/**
	 * Sets the created by user of this vdoc field.
	 *
	 * @param createdByUser the created by user of this vdoc field
	 */
	public void setCreatedByUser(long createdByUser);

	/**
	 * Returns the modified by user of this vdoc field.
	 *
	 * @return the modified by user of this vdoc field
	 */
	public long getModifiedByUser();

	/**
	 * Sets the modified by user of this vdoc field.
	 *
	 * @param modifiedByUser the modified by user of this vdoc field
	 */
	public void setModifiedByUser(long modifiedByUser);

	/**
	 * Returns the parent ID of this vdoc field.
	 *
	 * @return the parent ID of this vdoc field
	 */
	@AutoEscape
	public String getParentId();

	/**
	 * Sets the parent ID of this vdoc field.
	 *
	 * @param parentId the parent ID of this vdoc field
	 */
	public void setParentId(String parentId);

	/**
	 * Returns the name of this vdoc field.
	 *
	 * @return the name of this vdoc field
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this vdoc field.
	 *
	 * @param name the name of this vdoc field
	 */
	public void setName(String name);

	/**
	 * Returns the description of this vdoc field.
	 *
	 * @return the description of this vdoc field
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this vdoc field.
	 *
	 * @param description the description of this vdoc field
	 */
	public void setDescription(String description);

	/**
	 * Returns the language of this vdoc field.
	 *
	 * @return the language of this vdoc field
	 */
	@AutoEscape
	public String getLanguage();

	/**
	 * Sets the language of this vdoc field.
	 *
	 * @param language the language of this vdoc field
	 */
	public void setLanguage(String language);

	/**
	 * Returns the status field of this vdoc field.
	 *
	 * @return the status field of this vdoc field
	 */
	public boolean getStatusField();

	/**
	 * Returns <code>true</code> if this vdoc field is status field.
	 *
	 * @return <code>true</code> if this vdoc field is status field; <code>false</code> otherwise
	 */
	public boolean isStatusField();

	/**
	 * Sets whether this vdoc field is status field.
	 *
	 * @param statusField the status field of this vdoc field
	 */
	public void setStatusField(boolean statusField);

	/**
	 * Returns the position of this vdoc field.
	 *
	 * @return the position of this vdoc field
	 */
	public int getPosition();

	/**
	 * Sets the position of this vdoc field.
	 *
	 * @param position the position of this vdoc field
	 */
	public void setPosition(int position);

	/**
	 * Returns the listparent of this vdoc field.
	 *
	 * @return the listparent of this vdoc field
	 */
	@AutoEscape
	public String getListparent();

	/**
	 * Sets the listparent of this vdoc field.
	 *
	 * @param listparent the listparent of this vdoc field
	 */
	public void setListparent(String listparent);

	/**
	 * Returns the levels of this vdoc field.
	 *
	 * @return the levels of this vdoc field
	 */
	@AutoEscape
	public String getLevels();

	/**
	 * Sets the levels of this vdoc field.
	 *
	 * @param levels the levels of this vdoc field
	 */
	public void setLevels(String levels);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(vn.gov.hoabinh.model.vdocField vdocField);

	@Override
	public int hashCode();

	@Override
	public CacheModel<vn.gov.hoabinh.model.vdocField> toCacheModel();

	@Override
	public vn.gov.hoabinh.model.vdocField toEscapedModel();

	@Override
	public vn.gov.hoabinh.model.vdocField toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}