/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gov.hoabinh.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the vdocLevel service. Represents a row in the &quot;vdocLevel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.gov.hoabinh.model.impl.vdocLevelModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.gov.hoabinh.model.impl.vdocLevelImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see vdocLevel
 * @see vn.gov.hoabinh.model.impl.vdocLevelImpl
 * @see vn.gov.hoabinh.model.impl.vdocLevelModelImpl
 * @generated
 */
@ProviderType
public interface vdocLevelModel extends BaseModel<vdocLevel>, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a vdoc level model instance should use the {@link vdocLevel} interface instead.
	 */

	/**
	 * Returns the primary key of this vdoc level.
	 *
	 * @return the primary key of this vdoc level
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this vdoc level.
	 *
	 * @param primaryKey the primary key of this vdoc level
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the level ID of this vdoc level.
	 *
	 * @return the level ID of this vdoc level
	 */
	@AutoEscape
	public String getLevelId();

	/**
	 * Sets the level ID of this vdoc level.
	 *
	 * @param levelId the level ID of this vdoc level
	 */
	public void setLevelId(String levelId);

	/**
	 * Returns the group ID of this vdoc level.
	 *
	 * @return the group ID of this vdoc level
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this vdoc level.
	 *
	 * @param groupId the group ID of this vdoc level
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this vdoc level.
	 *
	 * @return the company ID of this vdoc level
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this vdoc level.
	 *
	 * @param companyId the company ID of this vdoc level
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this vdoc level.
	 *
	 * @return the user ID of this vdoc level
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this vdoc level.
	 *
	 * @param userId the user ID of this vdoc level
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this vdoc level.
	 *
	 * @return the user uuid of this vdoc level
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this vdoc level.
	 *
	 * @param userUuid the user uuid of this vdoc level
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the created date of this vdoc level.
	 *
	 * @return the created date of this vdoc level
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this vdoc level.
	 *
	 * @param createdDate the created date of this vdoc level
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the modified date of this vdoc level.
	 *
	 * @return the modified date of this vdoc level
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this vdoc level.
	 *
	 * @param modifiedDate the modified date of this vdoc level
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this vdoc level.
	 *
	 * @return the name of this vdoc level
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this vdoc level.
	 *
	 * @param name the name of this vdoc level
	 */
	public void setName(String name);

	/**
	 * Returns the description of this vdoc level.
	 *
	 * @return the description of this vdoc level
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this vdoc level.
	 *
	 * @param description the description of this vdoc level
	 */
	public void setDescription(String description);

	/**
	 * Returns the language of this vdoc level.
	 *
	 * @return the language of this vdoc level
	 */
	@AutoEscape
	public String getLanguage();

	/**
	 * Sets the language of this vdoc level.
	 *
	 * @param language the language of this vdoc level
	 */
	public void setLanguage(String language);

	/**
	 * Returns the position of this vdoc level.
	 *
	 * @return the position of this vdoc level
	 */
	public int getPosition();

	/**
	 * Sets the position of this vdoc level.
	 *
	 * @param position the position of this vdoc level
	 */
	public void setPosition(int position);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(vn.gov.hoabinh.model.vdocLevel vdocLevel);

	@Override
	public int hashCode();

	@Override
	public CacheModel<vn.gov.hoabinh.model.vdocLevel> toCacheModel();

	@Override
	public vn.gov.hoabinh.model.vdocLevel toEscapedModel();

	@Override
	public vn.gov.hoabinh.model.vdocLevel toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}