/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gov.hoabinh.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the vdocDocument service. Represents a row in the &quot;vdocDocument&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.gov.hoabinh.model.impl.vdocDocumentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.gov.hoabinh.model.impl.vdocDocumentImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see vdocDocument
 * @see vn.gov.hoabinh.model.impl.vdocDocumentImpl
 * @see vn.gov.hoabinh.model.impl.vdocDocumentModelImpl
 * @generated
 */
@ProviderType
public interface vdocDocumentModel extends BaseModel<vdocDocument>, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a vdoc document model instance should use the {@link vdocDocument} interface instead.
	 */

	/**
	 * Returns the primary key of this vdoc document.
	 *
	 * @return the primary key of this vdoc document
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this vdoc document.
	 *
	 * @param primaryKey the primary key of this vdoc document
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the doc ID of this vdoc document.
	 *
	 * @return the doc ID of this vdoc document
	 */
	@AutoEscape
	public String getDocId();

	/**
	 * Sets the doc ID of this vdoc document.
	 *
	 * @param docId the doc ID of this vdoc document
	 */
	public void setDocId(String docId);

	/**
	 * Returns the group ID of this vdoc document.
	 *
	 * @return the group ID of this vdoc document
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this vdoc document.
	 *
	 * @param groupId the group ID of this vdoc document
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the language of this vdoc document.
	 *
	 * @return the language of this vdoc document
	 */
	@AutoEscape
	public String getLanguage();

	/**
	 * Sets the language of this vdoc document.
	 *
	 * @param language the language of this vdoc document
	 */
	public void setLanguage(String language);

	/**
	 * Returns the company ID of this vdoc document.
	 *
	 * @return the company ID of this vdoc document
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this vdoc document.
	 *
	 * @param companyId the company ID of this vdoc document
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this vdoc document.
	 *
	 * @return the user ID of this vdoc document
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this vdoc document.
	 *
	 * @param userId the user ID of this vdoc document
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this vdoc document.
	 *
	 * @return the user uuid of this vdoc document
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this vdoc document.
	 *
	 * @param userUuid the user uuid of this vdoc document
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the created by user of this vdoc document.
	 *
	 * @return the created by user of this vdoc document
	 */
	public long getCreatedByUser();

	/**
	 * Sets the created by user of this vdoc document.
	 *
	 * @param createdByUser the created by user of this vdoc document
	 */
	public void setCreatedByUser(long createdByUser);

	/**
	 * Returns the created date of this vdoc document.
	 *
	 * @return the created date of this vdoc document
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this vdoc document.
	 *
	 * @param createdDate the created date of this vdoc document
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the modified by user of this vdoc document.
	 *
	 * @return the modified by user of this vdoc document
	 */
	public long getModifiedByUser();

	/**
	 * Sets the modified by user of this vdoc document.
	 *
	 * @param modifiedByUser the modified by user of this vdoc document
	 */
	public void setModifiedByUser(long modifiedByUser);

	/**
	 * Returns the modified date of this vdoc document.
	 *
	 * @return the modified date of this vdoc document
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this vdoc document.
	 *
	 * @param modifiedDate the modified date of this vdoc document
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the approved by user of this vdoc document.
	 *
	 * @return the approved by user of this vdoc document
	 */
	public long getApprovedByUser();

	/**
	 * Sets the approved by user of this vdoc document.
	 *
	 * @param approvedByUser the approved by user of this vdoc document
	 */
	public void setApprovedByUser(long approvedByUser);

	/**
	 * Returns the approved date of this vdoc document.
	 *
	 * @return the approved date of this vdoc document
	 */
	public Date getApprovedDate();

	/**
	 * Sets the approved date of this vdoc document.
	 *
	 * @param approvedDate the approved date of this vdoc document
	 */
	public void setApprovedDate(Date approvedDate);

	/**
	 * Returns the published by user of this vdoc document.
	 *
	 * @return the published by user of this vdoc document
	 */
	public long getPublishedByUser();

	/**
	 * Sets the published by user of this vdoc document.
	 *
	 * @param publishedByUser the published by user of this vdoc document
	 */
	public void setPublishedByUser(long publishedByUser);

	/**
	 * Returns the published date of this vdoc document.
	 *
	 * @return the published date of this vdoc document
	 */
	public Date getPublishedDate();

	/**
	 * Sets the published date of this vdoc document.
	 *
	 * @param publishedDate the published date of this vdoc document
	 */
	public void setPublishedDate(Date publishedDate);

	/**
	 * Returns the promul date of this vdoc document.
	 *
	 * @return the promul date of this vdoc document
	 */
	public Date getPromulDate();

	/**
	 * Sets the promul date of this vdoc document.
	 *
	 * @param promulDate the promul date of this vdoc document
	 */
	public void setPromulDate(Date promulDate);

	/**
	 * Returns the effectived date of this vdoc document.
	 *
	 * @return the effectived date of this vdoc document
	 */
	public Date getEffectivedDate();

	/**
	 * Sets the effectived date of this vdoc document.
	 *
	 * @param effectivedDate the effectived date of this vdoc document
	 */
	public void setEffectivedDate(Date effectivedDate);

	/**
	 * Returns the expired date of this vdoc document.
	 *
	 * @return the expired date of this vdoc document
	 */
	public Date getExpiredDate();

	/**
	 * Sets the expired date of this vdoc document.
	 *
	 * @param expiredDate the expired date of this vdoc document
	 */
	public void setExpiredDate(Date expiredDate);

	/**
	 * Returns the replace doc of this vdoc document.
	 *
	 * @return the replace doc of this vdoc document
	 */
	@AutoEscape
	public String getReplaceDoc();

	/**
	 * Sets the replace doc of this vdoc document.
	 *
	 * @param replaceDoc the replace doc of this vdoc document
	 */
	public void setReplaceDoc(String replaceDoc);

	/**
	 * Returns the title of this vdoc document.
	 *
	 * @return the title of this vdoc document
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this vdoc document.
	 *
	 * @param title the title of this vdoc document
	 */
	public void setTitle(String title);

	/**
	 * Returns the content of this vdoc document.
	 *
	 * @return the content of this vdoc document
	 */
	@AutoEscape
	public String getContent();

	/**
	 * Sets the content of this vdoc document.
	 *
	 * @param content the content of this vdoc document
	 */
	public void setContent(String content);

	/**
	 * Returns the process of this vdoc document.
	 *
	 * @return the process of this vdoc document
	 */
	@AutoEscape
	public String getProcess();

	/**
	 * Sets the process of this vdoc document.
	 *
	 * @param process the process of this vdoc document
	 */
	public void setProcess(String process);

	/**
	 * Returns the base of this vdoc document.
	 *
	 * @return the base of this vdoc document
	 */
	@AutoEscape
	public String getBase();

	/**
	 * Sets the base of this vdoc document.
	 *
	 * @param base the base of this vdoc document
	 */
	public void setBase(String base);

	/**
	 * Returns the time process of this vdoc document.
	 *
	 * @return the time process of this vdoc document
	 */
	@AutoEscape
	public String getTimeProcess();

	/**
	 * Sets the time process of this vdoc document.
	 *
	 * @param timeProcess the time process of this vdoc document
	 */
	public void setTimeProcess(String timeProcess);

	/**
	 * Returns the cost of this vdoc document.
	 *
	 * @return the cost of this vdoc document
	 */
	@AutoEscape
	public String getCost();

	/**
	 * Sets the cost of this vdoc document.
	 *
	 * @param cost the cost of this vdoc document
	 */
	public void setCost(String cost);

	/**
	 * Returns the require doc of this vdoc document.
	 *
	 * @return the require doc of this vdoc document
	 */
	@AutoEscape
	public String getRequireDoc();

	/**
	 * Sets the require doc of this vdoc document.
	 *
	 * @param requireDoc the require doc of this vdoc document
	 */
	public void setRequireDoc(String requireDoc);

	/**
	 * Returns the result of this vdoc document.
	 *
	 * @return the result of this vdoc document
	 */
	@AutoEscape
	public String getResult();

	/**
	 * Sets the result of this vdoc document.
	 *
	 * @param result the result of this vdoc document
	 */
	public void setResult(String result);

	/**
	 * Returns the objects of this vdoc document.
	 *
	 * @return the objects of this vdoc document
	 */
	@AutoEscape
	public String getObjects();

	/**
	 * Sets the objects of this vdoc document.
	 *
	 * @param objects the objects of this vdoc document
	 */
	public void setObjects(String objects);

	/**
	 * Returns the style of this vdoc document.
	 *
	 * @return the style of this vdoc document
	 */
	@AutoEscape
	public String getStyle();

	/**
	 * Sets the style of this vdoc document.
	 *
	 * @param style the style of this vdoc document
	 */
	public void setStyle(String style);

	/**
	 * Returns the position of this vdoc document.
	 *
	 * @return the position of this vdoc document
	 */
	public int getPosition();

	/**
	 * Sets the position of this vdoc document.
	 *
	 * @param position the position of this vdoc document
	 */
	public void setPosition(int position);

	/**
	 * Returns the note of this vdoc document.
	 *
	 * @return the note of this vdoc document
	 */
	@AutoEscape
	public String getNote();

	/**
	 * Sets the note of this vdoc document.
	 *
	 * @param note the note of this vdoc document
	 */
	public void setNote(String note);

	/**
	 * Returns the execute org of this vdoc document.
	 *
	 * @return the execute org of this vdoc document
	 */
	@AutoEscape
	public String getExecuteOrg();

	/**
	 * Sets the execute org of this vdoc document.
	 *
	 * @param executeOrg the execute org of this vdoc document
	 */
	public void setExecuteOrg(String executeOrg);

	/**
	 * Returns the user hit of this vdoc document.
	 *
	 * @return the user hit of this vdoc document
	 */
	public int getUserHit();

	/**
	 * Sets the user hit of this vdoc document.
	 *
	 * @param userHit the user hit of this vdoc document
	 */
	public void setUserHit(int userHit);

	/**
	 * Returns the status doc of this vdoc document.
	 *
	 * @return the status doc of this vdoc document
	 */
	public int getStatusDoc();

	/**
	 * Sets the status doc of this vdoc document.
	 *
	 * @param statusDoc the status doc of this vdoc document
	 */
	public void setStatusDoc(int statusDoc);

	/**
	 * Returns the type doc of this vdoc document.
	 *
	 * @return the type doc of this vdoc document
	 */
	public int getTypeDoc();

	/**
	 * Sets the type doc of this vdoc document.
	 *
	 * @param typeDoc the type doc of this vdoc document
	 */
	public void setTypeDoc(int typeDoc);

	/**
	 * Returns the has service of this vdoc document.
	 *
	 * @return the has service of this vdoc document
	 */
	public boolean getHasService();

	/**
	 * Returns <code>true</code> if this vdoc document is has service.
	 *
	 * @return <code>true</code> if this vdoc document is has service; <code>false</code> otherwise
	 */
	public boolean isHasService();

	/**
	 * Sets whether this vdoc document is has service.
	 *
	 * @param hasService the has service of this vdoc document
	 */
	public void setHasService(boolean hasService);

	/**
	 * Returns the has attachment of this vdoc document.
	 *
	 * @return the has attachment of this vdoc document
	 */
	public boolean getHasAttachment();

	/**
	 * Returns <code>true</code> if this vdoc document is has attachment.
	 *
	 * @return <code>true</code> if this vdoc document is has attachment; <code>false</code> otherwise
	 */
	public boolean isHasAttachment();

	/**
	 * Sets whether this vdoc document is has attachment.
	 *
	 * @param hasAttachment the has attachment of this vdoc document
	 */
	public void setHasAttachment(boolean hasAttachment);

	/**
	 * Returns the field ID of this vdoc document.
	 *
	 * @return the field ID of this vdoc document
	 */
	@AutoEscape
	public String getFieldId();

	/**
	 * Sets the field ID of this vdoc document.
	 *
	 * @param fieldId the field ID of this vdoc document
	 */
	public void setFieldId(String fieldId);

	/**
	 * Returns the org rels of this vdoc document.
	 *
	 * @return the org rels of this vdoc document
	 */
	@AutoEscape
	public String getOrgRels();

	/**
	 * Sets the org rels of this vdoc document.
	 *
	 * @param orgRels the org rels of this vdoc document
	 */
	public void setOrgRels(String orgRels);

	/**
	 * Returns the field rels of this vdoc document.
	 *
	 * @return the field rels of this vdoc document
	 */
	@AutoEscape
	public String getFieldRels();

	/**
	 * Sets the field rels of this vdoc document.
	 *
	 * @param fieldRels the field rels of this vdoc document
	 */
	public void setFieldRels(String fieldRels);

	/**
	 * Returns the levels of this vdoc document.
	 *
	 * @return the levels of this vdoc document
	 */
	@AutoEscape
	public String getLevels();

	/**
	 * Sets the levels of this vdoc document.
	 *
	 * @param levels the levels of this vdoc document
	 */
	public void setLevels(String levels);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(vn.gov.hoabinh.model.vdocDocument vdocDocument);

	@Override
	public int hashCode();

	@Override
	public CacheModel<vn.gov.hoabinh.model.vdocDocument> toCacheModel();

	@Override
	public vn.gov.hoabinh.model.vdocDocument toEscapedModel();

	@Override
	public vn.gov.hoabinh.model.vdocDocument toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}