/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gov.hoabinh.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import vn.gov.hoabinh.service.persistence.vdocDORelPK;

import java.io.Serializable;

/**
 * The base model interface for the vdocDORel service. Represents a row in the &quot;vdocDORel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.gov.hoabinh.model.impl.vdocDORelModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.gov.hoabinh.model.impl.vdocDORelImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see vdocDORel
 * @see vn.gov.hoabinh.model.impl.vdocDORelImpl
 * @see vn.gov.hoabinh.model.impl.vdocDORelModelImpl
 * @generated
 */
@ProviderType
public interface vdocDORelModel extends BaseModel<vdocDORel> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a vdoc d o rel model instance should use the {@link vdocDORel} interface instead.
	 */

	/**
	 * Returns the primary key of this vdoc d o rel.
	 *
	 * @return the primary key of this vdoc d o rel
	 */
	public vdocDORelPK getPrimaryKey();

	/**
	 * Sets the primary key of this vdoc d o rel.
	 *
	 * @param primaryKey the primary key of this vdoc d o rel
	 */
	public void setPrimaryKey(vdocDORelPK primaryKey);

	/**
	 * Returns the doc ID of this vdoc d o rel.
	 *
	 * @return the doc ID of this vdoc d o rel
	 */
	@AutoEscape
	public String getDocId();

	/**
	 * Sets the doc ID of this vdoc d o rel.
	 *
	 * @param docId the doc ID of this vdoc d o rel
	 */
	public void setDocId(String docId);

	/**
	 * Returns the org ID of this vdoc d o rel.
	 *
	 * @return the org ID of this vdoc d o rel
	 */
	@AutoEscape
	public String getOrgId();

	/**
	 * Sets the org ID of this vdoc d o rel.
	 *
	 * @param orgId the org ID of this vdoc d o rel
	 */
	public void setOrgId(String orgId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(vn.gov.hoabinh.model.vdocDORel vdocDORel);

	@Override
	public int hashCode();

	@Override
	public CacheModel<vn.gov.hoabinh.model.vdocDORel> toCacheModel();

	@Override
	public vn.gov.hoabinh.model.vdocDORel toEscapedModel();

	@Override
	public vn.gov.hoabinh.model.vdocDORel toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}