/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gov.hoabinh.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VLegalDraftDocument service. Represents a row in the &quot;VLegalDraftDocument&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.gov.hoabinh.model.impl.VLegalDraftDocumentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.gov.hoabinh.model.impl.VLegalDraftDocumentImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see VLegalDraftDocument
 * @see vn.gov.hoabinh.model.impl.VLegalDraftDocumentImpl
 * @see vn.gov.hoabinh.model.impl.VLegalDraftDocumentModelImpl
 * @generated
 */
@ProviderType
public interface VLegalDraftDocumentModel extends BaseModel<VLegalDraftDocument>,
	ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a v legal draft document model instance should use the {@link VLegalDraftDocument} interface instead.
	 */

	/**
	 * Returns the primary key of this v legal draft document.
	 *
	 * @return the primary key of this v legal draft document
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this v legal draft document.
	 *
	 * @param primaryKey the primary key of this v legal draft document
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the draft ID of this v legal draft document.
	 *
	 * @return the draft ID of this v legal draft document
	 */
	@AutoEscape
	public String getDraftId();

	/**
	 * Sets the draft ID of this v legal draft document.
	 *
	 * @param draftId the draft ID of this v legal draft document
	 */
	public void setDraftId(String draftId);

	/**
	 * Returns the group ID of this v legal draft document.
	 *
	 * @return the group ID of this v legal draft document
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this v legal draft document.
	 *
	 * @param groupId the group ID of this v legal draft document
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this v legal draft document.
	 *
	 * @return the company ID of this v legal draft document
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this v legal draft document.
	 *
	 * @param companyId the company ID of this v legal draft document
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this v legal draft document.
	 *
	 * @return the user ID of this v legal draft document
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this v legal draft document.
	 *
	 * @param userId the user ID of this v legal draft document
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this v legal draft document.
	 *
	 * @return the user uuid of this v legal draft document
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this v legal draft document.
	 *
	 * @param userUuid the user uuid of this v legal draft document
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the created by user of this v legal draft document.
	 *
	 * @return the created by user of this v legal draft document
	 */
	public long getCreatedByUser();

	/**
	 * Sets the created by user of this v legal draft document.
	 *
	 * @param createdByUser the created by user of this v legal draft document
	 */
	public void setCreatedByUser(long createdByUser);

	/**
	 * Returns the created date of this v legal draft document.
	 *
	 * @return the created date of this v legal draft document
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this v legal draft document.
	 *
	 * @param createdDate the created date of this v legal draft document
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the modified by user of this v legal draft document.
	 *
	 * @return the modified by user of this v legal draft document
	 */
	public long getModifiedByUser();

	/**
	 * Sets the modified by user of this v legal draft document.
	 *
	 * @param modifiedByUser the modified by user of this v legal draft document
	 */
	public void setModifiedByUser(long modifiedByUser);

	/**
	 * Returns the modified date of this v legal draft document.
	 *
	 * @return the modified date of this v legal draft document
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this v legal draft document.
	 *
	 * @param modifiedDate the modified date of this v legal draft document
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the approved by user of this v legal draft document.
	 *
	 * @return the approved by user of this v legal draft document
	 */
	public long getApprovedByUser();

	/**
	 * Sets the approved by user of this v legal draft document.
	 *
	 * @param approvedByUser the approved by user of this v legal draft document
	 */
	public void setApprovedByUser(long approvedByUser);

	/**
	 * Returns the approved date of this v legal draft document.
	 *
	 * @return the approved date of this v legal draft document
	 */
	public Date getApprovedDate();

	/**
	 * Sets the approved date of this v legal draft document.
	 *
	 * @param approvedDate the approved date of this v legal draft document
	 */
	public void setApprovedDate(Date approvedDate);

	/**
	 * Returns the published by user of this v legal draft document.
	 *
	 * @return the published by user of this v legal draft document
	 */
	public long getPublishedByUser();

	/**
	 * Sets the published by user of this v legal draft document.
	 *
	 * @param publishedByUser the published by user of this v legal draft document
	 */
	public void setPublishedByUser(long publishedByUser);

	/**
	 * Returns the published date of this v legal draft document.
	 *
	 * @return the published date of this v legal draft document
	 */
	public Date getPublishedDate();

	/**
	 * Sets the published date of this v legal draft document.
	 *
	 * @param publishedDate the published date of this v legal draft document
	 */
	public void setPublishedDate(Date publishedDate);

	/**
	 * Returns the title of this v legal draft document.
	 *
	 * @return the title of this v legal draft document
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this v legal draft document.
	 *
	 * @param title the title of this v legal draft document
	 */
	public void setTitle(String title);

	/**
	 * Returns the expired date of this v legal draft document.
	 *
	 * @return the expired date of this v legal draft document
	 */
	public Date getExpiredDate();

	/**
	 * Sets the expired date of this v legal draft document.
	 *
	 * @param expiredDate the expired date of this v legal draft document
	 */
	public void setExpiredDate(Date expiredDate);

	/**
	 * Returns the language of this v legal draft document.
	 *
	 * @return the language of this v legal draft document
	 */
	@AutoEscape
	public String getLanguage();

	/**
	 * Sets the language of this v legal draft document.
	 *
	 * @param language the language of this v legal draft document
	 */
	public void setLanguage(String language);

	/**
	 * Returns the content of this v legal draft document.
	 *
	 * @return the content of this v legal draft document
	 */
	@AutoEscape
	public String getContent();

	/**
	 * Sets the content of this v legal draft document.
	 *
	 * @param content the content of this v legal draft document
	 */
	public void setContent(String content);

	/**
	 * Returns the type ID of this v legal draft document.
	 *
	 * @return the type ID of this v legal draft document
	 */
	@AutoEscape
	public String getTypeId();

	/**
	 * Sets the type ID of this v legal draft document.
	 *
	 * @param typeId the type ID of this v legal draft document
	 */
	public void setTypeId(String typeId);

	/**
	 * Returns the field ID of this v legal draft document.
	 *
	 * @return the field ID of this v legal draft document
	 */
	@AutoEscape
	public String getFieldId();

	/**
	 * Sets the field ID of this v legal draft document.
	 *
	 * @param fieldId the field ID of this v legal draft document
	 */
	public void setFieldId(String fieldId);

	/**
	 * Returns the has attachment of this v legal draft document.
	 *
	 * @return the has attachment of this v legal draft document
	 */
	public boolean getHasAttachment();

	/**
	 * Returns <code>true</code> if this v legal draft document is has attachment.
	 *
	 * @return <code>true</code> if this v legal draft document is has attachment; <code>false</code> otherwise
	 */
	public boolean isHasAttachment();

	/**
	 * Sets whether this v legal draft document is has attachment.
	 *
	 * @param hasAttachment the has attachment of this v legal draft document
	 */
	public void setHasAttachment(boolean hasAttachment);

	/**
	 * Returns the draft level of this v legal draft document.
	 *
	 * @return the draft level of this v legal draft document
	 */
	public int getDraftLevel();

	/**
	 * Sets the draft level of this v legal draft document.
	 *
	 * @param draftLevel the draft level of this v legal draft document
	 */
	public void setDraftLevel(int draftLevel);

	/**
	 * Returns the doc code of this v legal draft document.
	 *
	 * @return the doc code of this v legal draft document
	 */
	@AutoEscape
	public String getDocCode();

	/**
	 * Sets the doc code of this v legal draft document.
	 *
	 * @param docCode the doc code of this v legal draft document
	 */
	public void setDocCode(String docCode);

	/**
	 * Returns the status draft of this v legal draft document.
	 *
	 * @return the status draft of this v legal draft document
	 */
	public int getStatusDraft();

	/**
	 * Sets the status draft of this v legal draft document.
	 *
	 * @param statusDraft the status draft of this v legal draft document
	 */
	public void setStatusDraft(int statusDraft);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		vn.gov.hoabinh.model.VLegalDraftDocument vLegalDraftDocument);

	@Override
	public int hashCode();

	@Override
	public CacheModel<vn.gov.hoabinh.model.VLegalDraftDocument> toCacheModel();

	@Override
	public vn.gov.hoabinh.model.VLegalDraftDocument toEscapedModel();

	@Override
	public vn.gov.hoabinh.model.VLegalDraftDocument toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}