/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gov.hoabinh.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VLegalTags service. Represents a row in the &quot;VLegalTags&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.gov.hoabinh.model.impl.VLegalTagsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.gov.hoabinh.model.impl.VLegalTagsImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see VLegalTags
 * @see vn.gov.hoabinh.model.impl.VLegalTagsImpl
 * @see vn.gov.hoabinh.model.impl.VLegalTagsModelImpl
 * @generated
 */
@ProviderType
public interface VLegalTagsModel extends BaseModel<VLegalTags>, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a v legal tags model instance should use the {@link VLegalTags} interface instead.
	 */

	/**
	 * Returns the primary key of this v legal tags.
	 *
	 * @return the primary key of this v legal tags
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this v legal tags.
	 *
	 * @param primaryKey the primary key of this v legal tags
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the tag ID of this v legal tags.
	 *
	 * @return the tag ID of this v legal tags
	 */
	@AutoEscape
	public String getTagId();

	/**
	 * Sets the tag ID of this v legal tags.
	 *
	 * @param tagId the tag ID of this v legal tags
	 */
	public void setTagId(String tagId);

	/**
	 * Returns the group ID of this v legal tags.
	 *
	 * @return the group ID of this v legal tags
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this v legal tags.
	 *
	 * @param groupId the group ID of this v legal tags
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this v legal tags.
	 *
	 * @return the company ID of this v legal tags
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this v legal tags.
	 *
	 * @param companyId the company ID of this v legal tags
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this v legal tags.
	 *
	 * @return the user ID of this v legal tags
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this v legal tags.
	 *
	 * @param userId the user ID of this v legal tags
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this v legal tags.
	 *
	 * @return the user uuid of this v legal tags
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this v legal tags.
	 *
	 * @param userUuid the user uuid of this v legal tags
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the created date of this v legal tags.
	 *
	 * @return the created date of this v legal tags
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this v legal tags.
	 *
	 * @param createdDate the created date of this v legal tags
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the modified date of this v legal tags.
	 *
	 * @return the modified date of this v legal tags
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this v legal tags.
	 *
	 * @param modifiedDate the modified date of this v legal tags
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this v legal tags.
	 *
	 * @return the name of this v legal tags
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this v legal tags.
	 *
	 * @param name the name of this v legal tags
	 */
	public void setName(String name);

	/**
	 * Returns the status tags of this v legal tags.
	 *
	 * @return the status tags of this v legal tags
	 */
	public boolean getStatusTags();

	/**
	 * Returns <code>true</code> if this v legal tags is status tags.
	 *
	 * @return <code>true</code> if this v legal tags is status tags; <code>false</code> otherwise
	 */
	public boolean isStatusTags();

	/**
	 * Sets whether this v legal tags is status tags.
	 *
	 * @param statusTags the status tags of this v legal tags
	 */
	public void setStatusTags(boolean statusTags);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(vn.gov.hoabinh.model.VLegalTags vLegalTags);

	@Override
	public int hashCode();

	@Override
	public CacheModel<vn.gov.hoabinh.model.VLegalTags> toCacheModel();

	@Override
	public vn.gov.hoabinh.model.VLegalTags toEscapedModel();

	@Override
	public vn.gov.hoabinh.model.VLegalTags toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}