/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gov.hoabinh.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VLegalOrg service. Represents a row in the &quot;VLegalOrg&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.gov.hoabinh.model.impl.VLegalOrgModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.gov.hoabinh.model.impl.VLegalOrgImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see VLegalOrg
 * @see vn.gov.hoabinh.model.impl.VLegalOrgImpl
 * @see vn.gov.hoabinh.model.impl.VLegalOrgModelImpl
 * @generated
 */
@ProviderType
public interface VLegalOrgModel extends BaseModel<VLegalOrg>, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a v legal org model instance should use the {@link VLegalOrg} interface instead.
	 */

	/**
	 * Returns the primary key of this v legal org.
	 *
	 * @return the primary key of this v legal org
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this v legal org.
	 *
	 * @param primaryKey the primary key of this v legal org
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the org ID of this v legal org.
	 *
	 * @return the org ID of this v legal org
	 */
	@AutoEscape
	public String getOrgId();

	/**
	 * Sets the org ID of this v legal org.
	 *
	 * @param orgId the org ID of this v legal org
	 */
	public void setOrgId(String orgId);

	/**
	 * Returns the group ID of this v legal org.
	 *
	 * @return the group ID of this v legal org
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this v legal org.
	 *
	 * @param groupId the group ID of this v legal org
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this v legal org.
	 *
	 * @return the company ID of this v legal org
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this v legal org.
	 *
	 * @param companyId the company ID of this v legal org
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this v legal org.
	 *
	 * @return the user ID of this v legal org
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this v legal org.
	 *
	 * @param userId the user ID of this v legal org
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this v legal org.
	 *
	 * @return the user uuid of this v legal org
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this v legal org.
	 *
	 * @param userUuid the user uuid of this v legal org
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the created date of this v legal org.
	 *
	 * @return the created date of this v legal org
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this v legal org.
	 *
	 * @param createdDate the created date of this v legal org
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the modified date of this v legal org.
	 *
	 * @return the modified date of this v legal org
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this v legal org.
	 *
	 * @param modifiedDate the modified date of this v legal org
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the created by user of this v legal org.
	 *
	 * @return the created by user of this v legal org
	 */
	public long getCreatedByUser();

	/**
	 * Sets the created by user of this v legal org.
	 *
	 * @param createdByUser the created by user of this v legal org
	 */
	public void setCreatedByUser(long createdByUser);

	/**
	 * Returns the modified by user of this v legal org.
	 *
	 * @return the modified by user of this v legal org
	 */
	public long getModifiedByUser();

	/**
	 * Sets the modified by user of this v legal org.
	 *
	 * @param modifiedByUser the modified by user of this v legal org
	 */
	public void setModifiedByUser(long modifiedByUser);

	/**
	 * Returns the name of this v legal org.
	 *
	 * @return the name of this v legal org
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this v legal org.
	 *
	 * @param name the name of this v legal org
	 */
	public void setName(String name);

	/**
	 * Returns the description of this v legal org.
	 *
	 * @return the description of this v legal org
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this v legal org.
	 *
	 * @param description the description of this v legal org
	 */
	public void setDescription(String description);

	/**
	 * Returns the parent ID of this v legal org.
	 *
	 * @return the parent ID of this v legal org
	 */
	@AutoEscape
	public String getParentId();

	/**
	 * Sets the parent ID of this v legal org.
	 *
	 * @param parentId the parent ID of this v legal org
	 */
	public void setParentId(String parentId);

	/**
	 * Returns the language of this v legal org.
	 *
	 * @return the language of this v legal org
	 */
	@AutoEscape
	public String getLanguage();

	/**
	 * Sets the language of this v legal org.
	 *
	 * @param language the language of this v legal org
	 */
	public void setLanguage(String language);

	/**
	 * Returns the status org of this v legal org.
	 *
	 * @return the status org of this v legal org
	 */
	public boolean getStatusOrg();

	/**
	 * Returns <code>true</code> if this v legal org is status org.
	 *
	 * @return <code>true</code> if this v legal org is status org; <code>false</code> otherwise
	 */
	public boolean isStatusOrg();

	/**
	 * Sets whether this v legal org is status org.
	 *
	 * @param statusOrg the status org of this v legal org
	 */
	public void setStatusOrg(boolean statusOrg);

	/**
	 * Returns the rssable of this v legal org.
	 *
	 * @return the rssable of this v legal org
	 */
	public boolean getRssable();

	/**
	 * Returns <code>true</code> if this v legal org is rssable.
	 *
	 * @return <code>true</code> if this v legal org is rssable; <code>false</code> otherwise
	 */
	public boolean isRssable();

	/**
	 * Sets whether this v legal org is rssable.
	 *
	 * @param rssable the rssable of this v legal org
	 */
	public void setRssable(boolean rssable);

	/**
	 * Returns the position of this v legal org.
	 *
	 * @return the position of this v legal org
	 */
	public int getPosition();

	/**
	 * Sets the position of this v legal org.
	 *
	 * @param position the position of this v legal org
	 */
	public void setPosition(int position);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(vn.gov.hoabinh.model.VLegalOrg vLegalOrg);

	@Override
	public int hashCode();

	@Override
	public CacheModel<vn.gov.hoabinh.model.VLegalOrg> toCacheModel();

	@Override
	public vn.gov.hoabinh.model.VLegalOrg toEscapedModel();

	@Override
	public vn.gov.hoabinh.model.VLegalOrg toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}