/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gov.hoabinh.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VLegalDocument service. Represents a row in the &quot;VLegalDocument&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.gov.hoabinh.model.impl.VLegalDocumentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.gov.hoabinh.model.impl.VLegalDocumentImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see VLegalDocument
 * @see vn.gov.hoabinh.model.impl.VLegalDocumentImpl
 * @see vn.gov.hoabinh.model.impl.VLegalDocumentModelImpl
 * @generated
 */
@ProviderType
public interface VLegalDocumentModel extends BaseModel<VLegalDocument>,
	ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a v legal document model instance should use the {@link VLegalDocument} interface instead.
	 */

	/**
	 * Returns the primary key of this v legal document.
	 *
	 * @return the primary key of this v legal document
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this v legal document.
	 *
	 * @param primaryKey the primary key of this v legal document
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the doc ID of this v legal document.
	 *
	 * @return the doc ID of this v legal document
	 */
	@AutoEscape
	public String getDocId();

	/**
	 * Sets the doc ID of this v legal document.
	 *
	 * @param docId the doc ID of this v legal document
	 */
	public void setDocId(String docId);

	/**
	 * Returns the group ID of this v legal document.
	 *
	 * @return the group ID of this v legal document
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this v legal document.
	 *
	 * @param groupId the group ID of this v legal document
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this v legal document.
	 *
	 * @return the company ID of this v legal document
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this v legal document.
	 *
	 * @param companyId the company ID of this v legal document
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this v legal document.
	 *
	 * @return the user ID of this v legal document
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this v legal document.
	 *
	 * @param userId the user ID of this v legal document
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this v legal document.
	 *
	 * @return the user uuid of this v legal document
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this v legal document.
	 *
	 * @param userUuid the user uuid of this v legal document
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the created by user of this v legal document.
	 *
	 * @return the created by user of this v legal document
	 */
	public long getCreatedByUser();

	/**
	 * Sets the created by user of this v legal document.
	 *
	 * @param createdByUser the created by user of this v legal document
	 */
	public void setCreatedByUser(long createdByUser);

	/**
	 * Returns the created date of this v legal document.
	 *
	 * @return the created date of this v legal document
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this v legal document.
	 *
	 * @param createdDate the created date of this v legal document
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the modified by user of this v legal document.
	 *
	 * @return the modified by user of this v legal document
	 */
	public long getModifiedByUser();

	/**
	 * Sets the modified by user of this v legal document.
	 *
	 * @param modifiedByUser the modified by user of this v legal document
	 */
	public void setModifiedByUser(long modifiedByUser);

	/**
	 * Returns the modified date of this v legal document.
	 *
	 * @return the modified date of this v legal document
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this v legal document.
	 *
	 * @param modifiedDate the modified date of this v legal document
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the approved by user of this v legal document.
	 *
	 * @return the approved by user of this v legal document
	 */
	public long getApprovedByUser();

	/**
	 * Sets the approved by user of this v legal document.
	 *
	 * @param approvedByUser the approved by user of this v legal document
	 */
	public void setApprovedByUser(long approvedByUser);

	/**
	 * Returns the approved date of this v legal document.
	 *
	 * @return the approved date of this v legal document
	 */
	public Date getApprovedDate();

	/**
	 * Sets the approved date of this v legal document.
	 *
	 * @param approvedDate the approved date of this v legal document
	 */
	public void setApprovedDate(Date approvedDate);

	/**
	 * Returns the forwarded by user of this v legal document.
	 *
	 * @return the forwarded by user of this v legal document
	 */
	public long getForwardedByUser();

	/**
	 * Sets the forwarded by user of this v legal document.
	 *
	 * @param forwardedByUser the forwarded by user of this v legal document
	 */
	public void setForwardedByUser(long forwardedByUser);

	/**
	 * Returns the forwarded date of this v legal document.
	 *
	 * @return the forwarded date of this v legal document
	 */
	public Date getForwardedDate();

	/**
	 * Sets the forwarded date of this v legal document.
	 *
	 * @param forwardedDate the forwarded date of this v legal document
	 */
	public void setForwardedDate(Date forwardedDate);

	/**
	 * Returns the published by user of this v legal document.
	 *
	 * @return the published by user of this v legal document
	 */
	public long getPublishedByUser();

	/**
	 * Sets the published by user of this v legal document.
	 *
	 * @param publishedByUser the published by user of this v legal document
	 */
	public void setPublishedByUser(long publishedByUser);

	/**
	 * Returns the published date of this v legal document.
	 *
	 * @return the published date of this v legal document
	 */
	public Date getPublishedDate();

	/**
	 * Sets the published date of this v legal document.
	 *
	 * @param publishedDate the published date of this v legal document
	 */
	public void setPublishedDate(Date publishedDate);

	/**
	 * Returns the symbol of this v legal document.
	 *
	 * @return the symbol of this v legal document
	 */
	@AutoEscape
	public String getSymbol();

	/**
	 * Sets the symbol of this v legal document.
	 *
	 * @param symbol the symbol of this v legal document
	 */
	public void setSymbol(String symbol);

	/**
	 * Returns the num of this v legal document.
	 *
	 * @return the num of this v legal document
	 */
	@AutoEscape
	public String getNum();

	/**
	 * Sets the num of this v legal document.
	 *
	 * @param num the num of this v legal document
	 */
	public void setNum(String num);

	/**
	 * Returns the promul date of this v legal document.
	 *
	 * @return the promul date of this v legal document
	 */
	public Date getPromulDate();

	/**
	 * Sets the promul date of this v legal document.
	 *
	 * @param promulDate the promul date of this v legal document
	 */
	public void setPromulDate(Date promulDate);

	/**
	 * Returns the effectived date of this v legal document.
	 *
	 * @return the effectived date of this v legal document
	 */
	public Date getEffectivedDate();

	/**
	 * Sets the effectived date of this v legal document.
	 *
	 * @param effectivedDate the effectived date of this v legal document
	 */
	public void setEffectivedDate(Date effectivedDate);

	/**
	 * Returns the expired date of this v legal document.
	 *
	 * @return the expired date of this v legal document
	 */
	public Date getExpiredDate();

	/**
	 * Sets the expired date of this v legal document.
	 *
	 * @param expiredDate the expired date of this v legal document
	 */
	public void setExpiredDate(Date expiredDate);

	/**
	 * Returns the replace doc of this v legal document.
	 *
	 * @return the replace doc of this v legal document
	 */
	@AutoEscape
	public String getReplaceDoc();

	/**
	 * Sets the replace doc of this v legal document.
	 *
	 * @param replaceDoc the replace doc of this v legal document
	 */
	public void setReplaceDoc(String replaceDoc);

	/**
	 * Returns the summary of this v legal document.
	 *
	 * @return the summary of this v legal document
	 */
	@AutoEscape
	public String getSummary();

	/**
	 * Sets the summary of this v legal document.
	 *
	 * @param summary the summary of this v legal document
	 */
	public void setSummary(String summary);

	/**
	 * Returns the content of this v legal document.
	 *
	 * @return the content of this v legal document
	 */
	@AutoEscape
	public String getContent();

	/**
	 * Sets the content of this v legal document.
	 *
	 * @param content the content of this v legal document
	 */
	public void setContent(String content);

	/**
	 * Returns the language of this v legal document.
	 *
	 * @return the language of this v legal document
	 */
	@AutoEscape
	public String getLanguage();

	/**
	 * Sets the language of this v legal document.
	 *
	 * @param language the language of this v legal document
	 */
	public void setLanguage(String language);

	/**
	 * Returns the user hit of this v legal document.
	 *
	 * @return the user hit of this v legal document
	 */
	public int getUserHit();

	/**
	 * Sets the user hit of this v legal document.
	 *
	 * @param userHit the user hit of this v legal document
	 */
	public void setUserHit(int userHit);

	/**
	 * Returns the status doc of this v legal document.
	 *
	 * @return the status doc of this v legal document
	 */
	public int getStatusDoc();

	/**
	 * Sets the status doc of this v legal document.
	 *
	 * @param statusDoc the status doc of this v legal document
	 */
	public void setStatusDoc(int statusDoc);

	/**
	 * Returns the has attachment of this v legal document.
	 *
	 * @return the has attachment of this v legal document
	 */
	public boolean getHasAttachment();

	/**
	 * Returns <code>true</code> if this v legal document is has attachment.
	 *
	 * @return <code>true</code> if this v legal document is has attachment; <code>false</code> otherwise
	 */
	public boolean isHasAttachment();

	/**
	 * Sets whether this v legal document is has attachment.
	 *
	 * @param hasAttachment the has attachment of this v legal document
	 */
	public void setHasAttachment(boolean hasAttachment);

	/**
	 * Returns the type doc ID of this v legal document.
	 *
	 * @return the type doc ID of this v legal document
	 */
	@AutoEscape
	public String getTypeDocId();

	/**
	 * Sets the type doc ID of this v legal document.
	 *
	 * @param typeDocId the type doc ID of this v legal document
	 */
	public void setTypeDocId(String typeDocId);

	/**
	 * Returns the field ID of this v legal document.
	 *
	 * @return the field ID of this v legal document
	 */
	@AutoEscape
	public String getFieldId();

	/**
	 * Sets the field ID of this v legal document.
	 *
	 * @param fieldId the field ID of this v legal document
	 */
	public void setFieldId(String fieldId);

	/**
	 * Returns the org ID of this v legal document.
	 *
	 * @return the org ID of this v legal document
	 */
	@AutoEscape
	public String getOrgId();

	/**
	 * Sets the org ID of this v legal document.
	 *
	 * @param orgId the org ID of this v legal document
	 */
	public void setOrgId(String orgId);

	/**
	 * Returns the org rels of this v legal document.
	 *
	 * @return the org rels of this v legal document
	 */
	@AutoEscape
	public String getOrgRels();

	/**
	 * Sets the org rels of this v legal document.
	 *
	 * @param orgRels the org rels of this v legal document
	 */
	public void setOrgRels(String orgRels);

	/**
	 * Returns the signer rels of this v legal document.
	 *
	 * @return the signer rels of this v legal document
	 */
	@AutoEscape
	public String getSignerRels();

	/**
	 * Sets the signer rels of this v legal document.
	 *
	 * @param signerRels the signer rels of this v legal document
	 */
	public void setSignerRels(String signerRels);

	/**
	 * Returns the field rels of this v legal document.
	 *
	 * @return the field rels of this v legal document
	 */
	@AutoEscape
	public String getFieldRels();

	/**
	 * Sets the field rels of this v legal document.
	 *
	 * @param fieldRels the field rels of this v legal document
	 */
	public void setFieldRels(String fieldRels);

	/**
	 * Returns the num rels of this v legal document.
	 *
	 * @return the num rels of this v legal document
	 */
	@AutoEscape
	public String getNumRels();

	/**
	 * Sets the num rels of this v legal document.
	 *
	 * @param numRels the num rels of this v legal document
	 */
	public void setNumRels(String numRels);

	/**
	 * Returns the doc code of this v legal document.
	 *
	 * @return the doc code of this v legal document
	 */
	@AutoEscape
	public String getDocCode();

	/**
	 * Sets the doc code of this v legal document.
	 *
	 * @param docCode the doc code of this v legal document
	 */
	public void setDocCode(String docCode);

	/**
	 * Returns the department rels of this v legal document.
	 *
	 * @return the department rels of this v legal document
	 */
	@AutoEscape
	public String getDepartmentRels();

	/**
	 * Sets the department rels of this v legal document.
	 *
	 * @param departmentRels the department rels of this v legal document
	 */
	public void setDepartmentRels(String departmentRels);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(vn.gov.hoabinh.model.VLegalDocument vLegalDocument);

	@Override
	public int hashCode();

	@Override
	public CacheModel<vn.gov.hoabinh.model.VLegalDocument> toCacheModel();

	@Override
	public vn.gov.hoabinh.model.VLegalDocument toEscapedModel();

	@Override
	public vn.gov.hoabinh.model.VLegalDocument toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}