/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gov.hoabinh.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VLegalLogger service. Represents a row in the &quot;VLegalLogger&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.gov.hoabinh.model.impl.VLegalLoggerModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.gov.hoabinh.model.impl.VLegalLoggerImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see VLegalLogger
 * @see vn.gov.hoabinh.model.impl.VLegalLoggerImpl
 * @see vn.gov.hoabinh.model.impl.VLegalLoggerModelImpl
 * @generated
 */
@ProviderType
public interface VLegalLoggerModel extends BaseModel<VLegalLogger>, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a v legal logger model instance should use the {@link VLegalLogger} interface instead.
	 */

	/**
	 * Returns the primary key of this v legal logger.
	 *
	 * @return the primary key of this v legal logger
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this v legal logger.
	 *
	 * @param primaryKey the primary key of this v legal logger
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the logger ID of this v legal logger.
	 *
	 * @return the logger ID of this v legal logger
	 */
	@AutoEscape
	public String getLoggerId();

	/**
	 * Sets the logger ID of this v legal logger.
	 *
	 * @param loggerId the logger ID of this v legal logger
	 */
	public void setLoggerId(String loggerId);

	/**
	 * Returns the group ID of this v legal logger.
	 *
	 * @return the group ID of this v legal logger
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this v legal logger.
	 *
	 * @param groupId the group ID of this v legal logger
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this v legal logger.
	 *
	 * @return the company ID of this v legal logger
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this v legal logger.
	 *
	 * @param companyId the company ID of this v legal logger
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this v legal logger.
	 *
	 * @return the user ID of this v legal logger
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this v legal logger.
	 *
	 * @param userId the user ID of this v legal logger
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this v legal logger.
	 *
	 * @return the user uuid of this v legal logger
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this v legal logger.
	 *
	 * @param userUuid the user uuid of this v legal logger
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the created date of this v legal logger.
	 *
	 * @return the created date of this v legal logger
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this v legal logger.
	 *
	 * @param createdDate the created date of this v legal logger
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the created by user of this v legal logger.
	 *
	 * @return the created by user of this v legal logger
	 */
	public long getCreatedByUser();

	/**
	 * Sets the created by user of this v legal logger.
	 *
	 * @param createdByUser the created by user of this v legal logger
	 */
	public void setCreatedByUser(long createdByUser);

	/**
	 * Returns the content of this v legal logger.
	 *
	 * @return the content of this v legal logger
	 */
	@AutoEscape
	public String getContent();

	/**
	 * Sets the content of this v legal logger.
	 *
	 * @param content the content of this v legal logger
	 */
	public void setContent(String content);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(vn.gov.hoabinh.model.VLegalLogger vLegalLogger);

	@Override
	public int hashCode();

	@Override
	public CacheModel<vn.gov.hoabinh.model.VLegalLogger> toCacheModel();

	@Override
	public vn.gov.hoabinh.model.VLegalLogger toEscapedModel();

	@Override
	public vn.gov.hoabinh.model.VLegalLogger toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}