/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gov.hoabinh.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import vn.gov.hoabinh.model.Clip;
import vn.gov.hoabinh.model.ClipModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Clip service. Represents a row in the &quot;Clip&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link ClipModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ClipImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ClipImpl
 * @see Clip
 * @see ClipModel
 * @generated
 */
@ProviderType
public class ClipModelImpl extends BaseModelImpl<Clip> implements ClipModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a clip model instance should use the {@link Clip} interface instead.
	 */
	public static final String TABLE_NAME = "Clip";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id_", Types.VARCHAR },
			{ "clipTypeId", Types.VARCHAR },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "createdDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "url", Types.VARCHAR },
			{ "name", Types.VARCHAR },
			{ "title", Types.VARCHAR },
			{ "image", Types.VARCHAR },
			{ "description", Types.VARCHAR },
			{ "active_", Types.BOOLEAN },
			{ "language", Types.VARCHAR },
			{ "hitcount", Types.INTEGER },
			{ "hitcountview", Types.INTEGER }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("clipTypeId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createdDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("url", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("title", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("image", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("active_", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("language", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("hitcount", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("hitcountview", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE = "create table Clip (id_ VARCHAR(75) not null primary key,clipTypeId VARCHAR(75) null,groupId LONG,companyId LONG,userId LONG,createdDate DATE null,modifiedDate DATE null,url VARCHAR(75) null,name VARCHAR(75) null,title VARCHAR(75) null,image VARCHAR(75) null,description VARCHAR(75) null,active_ BOOLEAN,language VARCHAR(75) null,hitcount INTEGER,hitcountview INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table Clip";
	public static final String ORDER_BY_JPQL = " ORDER BY clip.createdDate DESC";
	public static final String ORDER_BY_SQL = " ORDER BY Clip.createdDate DESC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(vn.gov.hoabinh.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.gov.hoabinh.model.Clip"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(vn.gov.hoabinh.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.gov.hoabinh.model.Clip"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(vn.gov.hoabinh.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.vn.gov.hoabinh.model.Clip"),
			true);
	public static final long ACTIVE_COLUMN_BITMASK = 1L;
	public static final long CLIPTYPEID_COLUMN_BITMASK = 2L;
	public static final long GROUPID_COLUMN_BITMASK = 4L;
	public static final long LANGUAGE_COLUMN_BITMASK = 8L;
	public static final long CREATEDDATE_COLUMN_BITMASK = 16L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(vn.gov.hoabinh.service.util.ServiceProps.get(
				"lock.expiration.time.vn.gov.hoabinh.model.Clip"));

	public ClipModelImpl() {
	}

	@Override
	public String getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(String primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((String)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return Clip.class;
	}

	@Override
	public String getModelClassName() {
		return Clip.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("clipTypeId", getClipTypeId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("createdDate", getCreatedDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("url", getUrl());
		attributes.put("name", getName());
		attributes.put("title", getTitle());
		attributes.put("image", getImage());
		attributes.put("description", getDescription());
		attributes.put("active", getActive());
		attributes.put("language", getLanguage());
		attributes.put("hitcount", getHitcount());
		attributes.put("hitcountview", getHitcountview());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String id = (String)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		String clipTypeId = (String)attributes.get("clipTypeId");

		if (clipTypeId != null) {
			setClipTypeId(clipTypeId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Date createdDate = (Date)attributes.get("createdDate");

		if (createdDate != null) {
			setCreatedDate(createdDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String url = (String)attributes.get("url");

		if (url != null) {
			setUrl(url);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}

		String title = (String)attributes.get("title");

		if (title != null) {
			setTitle(title);
		}

		String image = (String)attributes.get("image");

		if (image != null) {
			setImage(image);
		}

		String description = (String)attributes.get("description");

		if (description != null) {
			setDescription(description);
		}

		Boolean active = (Boolean)attributes.get("active");

		if (active != null) {
			setActive(active);
		}

		String language = (String)attributes.get("language");

		if (language != null) {
			setLanguage(language);
		}

		Integer hitcount = (Integer)attributes.get("hitcount");

		if (hitcount != null) {
			setHitcount(hitcount);
		}

		Integer hitcountview = (Integer)attributes.get("hitcountview");

		if (hitcountview != null) {
			setHitcountview(hitcountview);
		}
	}

	@Override
	public String getId() {
		if (_id == null) {
			return StringPool.BLANK;
		}
		else {
			return _id;
		}
	}

	@Override
	public void setId(String id) {
		_id = id;
	}

	@Override
	public String getClipTypeId() {
		if (_clipTypeId == null) {
			return StringPool.BLANK;
		}
		else {
			return _clipTypeId;
		}
	}

	@Override
	public void setClipTypeId(String clipTypeId) {
		_columnBitmask |= CLIPTYPEID_COLUMN_BITMASK;

		if (_originalClipTypeId == null) {
			_originalClipTypeId = _clipTypeId;
		}

		_clipTypeId = clipTypeId;
	}

	public String getOriginalClipTypeId() {
		return GetterUtil.getString(_originalClipTypeId);
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public Date getCreatedDate() {
		return _createdDate;
	}

	@Override
	public void setCreatedDate(Date createdDate) {
		_columnBitmask = -1L;

		_createdDate = createdDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@Override
	public String getUrl() {
		if (_url == null) {
			return StringPool.BLANK;
		}
		else {
			return _url;
		}
	}

	@Override
	public void setUrl(String url) {
		_url = url;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@Override
	public String getTitle() {
		if (_title == null) {
			return StringPool.BLANK;
		}
		else {
			return _title;
		}
	}

	@Override
	public void setTitle(String title) {
		_title = title;
	}

	@Override
	public String getImage() {
		if (_image == null) {
			return StringPool.BLANK;
		}
		else {
			return _image;
		}
	}

	@Override
	public void setImage(String image) {
		_image = image;
	}

	@Override
	public String getDescription() {
		if (_description == null) {
			return StringPool.BLANK;
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	@Override
	public boolean getActive() {
		return _active;
	}

	@Override
	public boolean isActive() {
		return _active;
	}

	@Override
	public void setActive(boolean active) {
		_columnBitmask |= ACTIVE_COLUMN_BITMASK;

		if (!_setOriginalActive) {
			_setOriginalActive = true;

			_originalActive = _active;
		}

		_active = active;
	}

	public boolean getOriginalActive() {
		return _originalActive;
	}

	@Override
	public String getLanguage() {
		if (_language == null) {
			return StringPool.BLANK;
		}
		else {
			return _language;
		}
	}

	@Override
	public void setLanguage(String language) {
		_columnBitmask |= LANGUAGE_COLUMN_BITMASK;

		if (_originalLanguage == null) {
			_originalLanguage = _language;
		}

		_language = language;
	}

	public String getOriginalLanguage() {
		return GetterUtil.getString(_originalLanguage);
	}

	@Override
	public int getHitcount() {
		return _hitcount;
	}

	@Override
	public void setHitcount(int hitcount) {
		_hitcount = hitcount;
	}

	@Override
	public int getHitcountview() {
		return _hitcountview;
	}

	@Override
	public void setHitcountview(int hitcountview) {
		_hitcountview = hitcountview;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public Clip toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Clip)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ClipImpl clipImpl = new ClipImpl();

		clipImpl.setId(getId());
		clipImpl.setClipTypeId(getClipTypeId());
		clipImpl.setGroupId(getGroupId());
		clipImpl.setCompanyId(getCompanyId());
		clipImpl.setUserId(getUserId());
		clipImpl.setCreatedDate(getCreatedDate());
		clipImpl.setModifiedDate(getModifiedDate());
		clipImpl.setUrl(getUrl());
		clipImpl.setName(getName());
		clipImpl.setTitle(getTitle());
		clipImpl.setImage(getImage());
		clipImpl.setDescription(getDescription());
		clipImpl.setActive(getActive());
		clipImpl.setLanguage(getLanguage());
		clipImpl.setHitcount(getHitcount());
		clipImpl.setHitcountview(getHitcountview());

		clipImpl.resetOriginalValues();

		return clipImpl;
	}

	@Override
	public int compareTo(Clip clip) {
		int value = 0;

		value = DateUtil.compareTo(getCreatedDate(), clip.getCreatedDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Clip)) {
			return false;
		}

		Clip clip = (Clip)obj;

		String primaryKey = clip.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		ClipModelImpl clipModelImpl = this;

		clipModelImpl._originalClipTypeId = clipModelImpl._clipTypeId;

		clipModelImpl._originalGroupId = clipModelImpl._groupId;

		clipModelImpl._setOriginalGroupId = false;

		clipModelImpl._originalActive = clipModelImpl._active;

		clipModelImpl._setOriginalActive = false;

		clipModelImpl._originalLanguage = clipModelImpl._language;

		clipModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Clip> toCacheModel() {
		ClipCacheModel clipCacheModel = new ClipCacheModel();

		clipCacheModel.id = getId();

		String id = clipCacheModel.id;

		if ((id != null) && (id.length() == 0)) {
			clipCacheModel.id = null;
		}

		clipCacheModel.clipTypeId = getClipTypeId();

		String clipTypeId = clipCacheModel.clipTypeId;

		if ((clipTypeId != null) && (clipTypeId.length() == 0)) {
			clipCacheModel.clipTypeId = null;
		}

		clipCacheModel.groupId = getGroupId();

		clipCacheModel.companyId = getCompanyId();

		clipCacheModel.userId = getUserId();

		Date createdDate = getCreatedDate();

		if (createdDate != null) {
			clipCacheModel.createdDate = createdDate.getTime();
		}
		else {
			clipCacheModel.createdDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			clipCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			clipCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		clipCacheModel.url = getUrl();

		String url = clipCacheModel.url;

		if ((url != null) && (url.length() == 0)) {
			clipCacheModel.url = null;
		}

		clipCacheModel.name = getName();

		String name = clipCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			clipCacheModel.name = null;
		}

		clipCacheModel.title = getTitle();

		String title = clipCacheModel.title;

		if ((title != null) && (title.length() == 0)) {
			clipCacheModel.title = null;
		}

		clipCacheModel.image = getImage();

		String image = clipCacheModel.image;

		if ((image != null) && (image.length() == 0)) {
			clipCacheModel.image = null;
		}

		clipCacheModel.description = getDescription();

		String description = clipCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			clipCacheModel.description = null;
		}

		clipCacheModel.active = getActive();

		clipCacheModel.language = getLanguage();

		String language = clipCacheModel.language;

		if ((language != null) && (language.length() == 0)) {
			clipCacheModel.language = null;
		}

		clipCacheModel.hitcount = getHitcount();

		clipCacheModel.hitcountview = getHitcountview();

		return clipCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(33);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", clipTypeId=");
		sb.append(getClipTypeId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", createdDate=");
		sb.append(getCreatedDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", url=");
		sb.append(getUrl());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", title=");
		sb.append(getTitle());
		sb.append(", image=");
		sb.append(getImage());
		sb.append(", description=");
		sb.append(getDescription());
		sb.append(", active=");
		sb.append(getActive());
		sb.append(", language=");
		sb.append(getLanguage());
		sb.append(", hitcount=");
		sb.append(getHitcount());
		sb.append(", hitcountview=");
		sb.append(getHitcountview());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(52);

		sb.append("<model><model-name>");
		sb.append("vn.gov.hoabinh.model.Clip");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>clipTypeId</column-name><column-value><![CDATA[");
		sb.append(getClipTypeId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdDate</column-name><column-value><![CDATA[");
		sb.append(getCreatedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>url</column-name><column-value><![CDATA[");
		sb.append(getUrl());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>title</column-name><column-value><![CDATA[");
		sb.append(getTitle());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>image</column-name><column-value><![CDATA[");
		sb.append(getImage());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>description</column-name><column-value><![CDATA[");
		sb.append(getDescription());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>active</column-name><column-value><![CDATA[");
		sb.append(getActive());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>language</column-name><column-value><![CDATA[");
		sb.append(getLanguage());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>hitcount</column-name><column-value><![CDATA[");
		sb.append(getHitcount());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>hitcountview</column-name><column-value><![CDATA[");
		sb.append(getHitcountview());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = Clip.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			Clip.class
		};
	private String _id;
	private String _clipTypeId;
	private String _originalClipTypeId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _userId;
	private Date _createdDate;
	private Date _modifiedDate;
	private String _url;
	private String _name;
	private String _title;
	private String _image;
	private String _description;
	private boolean _active;
	private boolean _originalActive;
	private boolean _setOriginalActive;
	private String _language;
	private String _originalLanguage;
	private int _hitcount;
	private int _hitcountview;
	private long _columnBitmask;
	private Clip _escapedModel;
}