/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gov.hoabinh.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import vn.gov.hoabinh.model.FAQQuestion;
import vn.gov.hoabinh.model.FAQQuestionModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the FAQQuestion service. Represents a row in the &quot;FAQQuestion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link FAQQuestionModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FAQQuestionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FAQQuestionImpl
 * @see FAQQuestion
 * @see FAQQuestionModel
 * @generated
 */
@ProviderType
public class FAQQuestionModelImpl extends BaseModelImpl<FAQQuestion>
	implements FAQQuestionModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a f a q question model instance should use the {@link FAQQuestion} interface instead.
	 */
	public static final String TABLE_NAME = "FAQQuestion";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id_", Types.BIGINT },
			{ "title", Types.VARCHAR },
			{ "content", Types.VARCHAR },
			{ "language", Types.VARCHAR },
			{ "questionOrder", Types.INTEGER },
			{ "sentDate", Types.TIMESTAMP },
			{ "sentByUser", Types.VARCHAR },
			{ "senderEmail", Types.VARCHAR },
			{ "questionType", Types.VARCHAR },
			{ "modifiedByUser", Types.VARCHAR },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "hitCount", Types.INTEGER },
			{ "approved", Types.BOOLEAN },
			{ "groupId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "categoryId", Types.BIGINT }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id_", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("title", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("content", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("language", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("questionOrder", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("sentDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("sentByUser", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("senderEmail", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("questionType", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("modifiedByUser", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("hitCount", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("approved", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("categoryId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE = "create table FAQQuestion (id_ LONG not null primary key,title VARCHAR(75) null,content VARCHAR(75) null,language VARCHAR(75) null,questionOrder INTEGER,sentDate DATE null,sentByUser VARCHAR(75) null,senderEmail VARCHAR(75) null,questionType VARCHAR(75) null,modifiedByUser VARCHAR(75) null,modifiedDate DATE null,hitCount INTEGER,approved BOOLEAN,groupId LONG,userId LONG,categoryId LONG)";
	public static final String TABLE_SQL_DROP = "drop table FAQQuestion";
	public static final String ORDER_BY_JPQL = " ORDER BY faqQuestion.sentDate DESC";
	public static final String ORDER_BY_SQL = " ORDER BY FAQQuestion.sentDate DESC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(vn.gov.hoabinh.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.gov.hoabinh.model.FAQQuestion"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(vn.gov.hoabinh.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.gov.hoabinh.model.FAQQuestion"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(vn.gov.hoabinh.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.vn.gov.hoabinh.model.FAQQuestion"),
			true);
	public static final long APPROVED_COLUMN_BITMASK = 1L;
	public static final long CATEGORYID_COLUMN_BITMASK = 2L;
	public static final long GROUPID_COLUMN_BITMASK = 4L;
	public static final long ID_COLUMN_BITMASK = 8L;
	public static final long LANGUAGE_COLUMN_BITMASK = 16L;
	public static final long QUESTIONTYPE_COLUMN_BITMASK = 32L;
	public static final long SENTDATE_COLUMN_BITMASK = 64L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(vn.gov.hoabinh.service.util.ServiceProps.get(
				"lock.expiration.time.vn.gov.hoabinh.model.FAQQuestion"));

	public FAQQuestionModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return FAQQuestion.class;
	}

	@Override
	public String getModelClassName() {
		return FAQQuestion.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("title", getTitle());
		attributes.put("content", getContent());
		attributes.put("language", getLanguage());
		attributes.put("questionOrder", getQuestionOrder());
		attributes.put("sentDate", getSentDate());
		attributes.put("sentByUser", getSentByUser());
		attributes.put("senderEmail", getSenderEmail());
		attributes.put("questionType", getQuestionType());
		attributes.put("modifiedByUser", getModifiedByUser());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("hitCount", getHitCount());
		attributes.put("approved", getApproved());
		attributes.put("groupId", getGroupId());
		attributes.put("userId", getUserId());
		attributes.put("categoryId", getCategoryId());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		String title = (String)attributes.get("title");

		if (title != null) {
			setTitle(title);
		}

		String content = (String)attributes.get("content");

		if (content != null) {
			setContent(content);
		}

		String language = (String)attributes.get("language");

		if (language != null) {
			setLanguage(language);
		}

		Integer questionOrder = (Integer)attributes.get("questionOrder");

		if (questionOrder != null) {
			setQuestionOrder(questionOrder);
		}

		Date sentDate = (Date)attributes.get("sentDate");

		if (sentDate != null) {
			setSentDate(sentDate);
		}

		String sentByUser = (String)attributes.get("sentByUser");

		if (sentByUser != null) {
			setSentByUser(sentByUser);
		}

		String senderEmail = (String)attributes.get("senderEmail");

		if (senderEmail != null) {
			setSenderEmail(senderEmail);
		}

		String questionType = (String)attributes.get("questionType");

		if (questionType != null) {
			setQuestionType(questionType);
		}

		String modifiedByUser = (String)attributes.get("modifiedByUser");

		if (modifiedByUser != null) {
			setModifiedByUser(modifiedByUser);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Integer hitCount = (Integer)attributes.get("hitCount");

		if (hitCount != null) {
			setHitCount(hitCount);
		}

		Boolean approved = (Boolean)attributes.get("approved");

		if (approved != null) {
			setApproved(approved);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Long categoryId = (Long)attributes.get("categoryId");

		if (categoryId != null) {
			setCategoryId(categoryId);
		}
	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_columnBitmask |= ID_COLUMN_BITMASK;

		if (!_setOriginalId) {
			_setOriginalId = true;

			_originalId = _id;
		}

		_id = id;
	}

	public long getOriginalId() {
		return _originalId;
	}

	@Override
	public String getTitle() {
		if (_title == null) {
			return StringPool.BLANK;
		}
		else {
			return _title;
		}
	}

	@Override
	public void setTitle(String title) {
		_title = title;
	}

	@Override
	public String getContent() {
		if (_content == null) {
			return StringPool.BLANK;
		}
		else {
			return _content;
		}
	}

	@Override
	public void setContent(String content) {
		_content = content;
	}

	@Override
	public String getLanguage() {
		if (_language == null) {
			return StringPool.BLANK;
		}
		else {
			return _language;
		}
	}

	@Override
	public void setLanguage(String language) {
		_columnBitmask |= LANGUAGE_COLUMN_BITMASK;

		if (_originalLanguage == null) {
			_originalLanguage = _language;
		}

		_language = language;
	}

	public String getOriginalLanguage() {
		return GetterUtil.getString(_originalLanguage);
	}

	@Override
	public int getQuestionOrder() {
		return _questionOrder;
	}

	@Override
	public void setQuestionOrder(int questionOrder) {
		_questionOrder = questionOrder;
	}

	@Override
	public Date getSentDate() {
		return _sentDate;
	}

	@Override
	public void setSentDate(Date sentDate) {
		_columnBitmask = -1L;

		_sentDate = sentDate;
	}

	@Override
	public String getSentByUser() {
		if (_sentByUser == null) {
			return StringPool.BLANK;
		}
		else {
			return _sentByUser;
		}
	}

	@Override
	public void setSentByUser(String sentByUser) {
		_sentByUser = sentByUser;
	}

	@Override
	public String getSenderEmail() {
		if (_senderEmail == null) {
			return StringPool.BLANK;
		}
		else {
			return _senderEmail;
		}
	}

	@Override
	public void setSenderEmail(String senderEmail) {
		_senderEmail = senderEmail;
	}

	@Override
	public String getQuestionType() {
		if (_questionType == null) {
			return StringPool.BLANK;
		}
		else {
			return _questionType;
		}
	}

	@Override
	public void setQuestionType(String questionType) {
		_columnBitmask |= QUESTIONTYPE_COLUMN_BITMASK;

		if (_originalQuestionType == null) {
			_originalQuestionType = _questionType;
		}

		_questionType = questionType;
	}

	public String getOriginalQuestionType() {
		return GetterUtil.getString(_originalQuestionType);
	}

	@Override
	public String getModifiedByUser() {
		if (_modifiedByUser == null) {
			return StringPool.BLANK;
		}
		else {
			return _modifiedByUser;
		}
	}

	@Override
	public void setModifiedByUser(String modifiedByUser) {
		_modifiedByUser = modifiedByUser;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@Override
	public int getHitCount() {
		return _hitCount;
	}

	@Override
	public void setHitCount(int hitCount) {
		_hitCount = hitCount;
	}

	@Override
	public boolean getApproved() {
		return _approved;
	}

	@Override
	public boolean isApproved() {
		return _approved;
	}

	@Override
	public void setApproved(boolean approved) {
		_columnBitmask |= APPROVED_COLUMN_BITMASK;

		if (!_setOriginalApproved) {
			_setOriginalApproved = true;

			_originalApproved = _approved;
		}

		_approved = approved;
	}

	public boolean getOriginalApproved() {
		return _originalApproved;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public long getCategoryId() {
		return _categoryId;
	}

	@Override
	public void setCategoryId(long categoryId) {
		_columnBitmask |= CATEGORYID_COLUMN_BITMASK;

		if (!_setOriginalCategoryId) {
			_setOriginalCategoryId = true;

			_originalCategoryId = _categoryId;
		}

		_categoryId = categoryId;
	}

	public long getOriginalCategoryId() {
		return _originalCategoryId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			FAQQuestion.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public FAQQuestion toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (FAQQuestion)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		FAQQuestionImpl faqQuestionImpl = new FAQQuestionImpl();

		faqQuestionImpl.setId(getId());
		faqQuestionImpl.setTitle(getTitle());
		faqQuestionImpl.setContent(getContent());
		faqQuestionImpl.setLanguage(getLanguage());
		faqQuestionImpl.setQuestionOrder(getQuestionOrder());
		faqQuestionImpl.setSentDate(getSentDate());
		faqQuestionImpl.setSentByUser(getSentByUser());
		faqQuestionImpl.setSenderEmail(getSenderEmail());
		faqQuestionImpl.setQuestionType(getQuestionType());
		faqQuestionImpl.setModifiedByUser(getModifiedByUser());
		faqQuestionImpl.setModifiedDate(getModifiedDate());
		faqQuestionImpl.setHitCount(getHitCount());
		faqQuestionImpl.setApproved(getApproved());
		faqQuestionImpl.setGroupId(getGroupId());
		faqQuestionImpl.setUserId(getUserId());
		faqQuestionImpl.setCategoryId(getCategoryId());

		faqQuestionImpl.resetOriginalValues();

		return faqQuestionImpl;
	}

	@Override
	public int compareTo(FAQQuestion faqQuestion) {
		int value = 0;

		value = DateUtil.compareTo(getSentDate(), faqQuestion.getSentDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof FAQQuestion)) {
			return false;
		}

		FAQQuestion faqQuestion = (FAQQuestion)obj;

		long primaryKey = faqQuestion.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		FAQQuestionModelImpl faqQuestionModelImpl = this;

		faqQuestionModelImpl._originalId = faqQuestionModelImpl._id;

		faqQuestionModelImpl._setOriginalId = false;

		faqQuestionModelImpl._originalLanguage = faqQuestionModelImpl._language;

		faqQuestionModelImpl._originalQuestionType = faqQuestionModelImpl._questionType;

		faqQuestionModelImpl._originalApproved = faqQuestionModelImpl._approved;

		faqQuestionModelImpl._setOriginalApproved = false;

		faqQuestionModelImpl._originalGroupId = faqQuestionModelImpl._groupId;

		faqQuestionModelImpl._setOriginalGroupId = false;

		faqQuestionModelImpl._originalCategoryId = faqQuestionModelImpl._categoryId;

		faqQuestionModelImpl._setOriginalCategoryId = false;

		faqQuestionModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<FAQQuestion> toCacheModel() {
		FAQQuestionCacheModel faqQuestionCacheModel = new FAQQuestionCacheModel();

		faqQuestionCacheModel.id = getId();

		faqQuestionCacheModel.title = getTitle();

		String title = faqQuestionCacheModel.title;

		if ((title != null) && (title.length() == 0)) {
			faqQuestionCacheModel.title = null;
		}

		faqQuestionCacheModel.content = getContent();

		String content = faqQuestionCacheModel.content;

		if ((content != null) && (content.length() == 0)) {
			faqQuestionCacheModel.content = null;
		}

		faqQuestionCacheModel.language = getLanguage();

		String language = faqQuestionCacheModel.language;

		if ((language != null) && (language.length() == 0)) {
			faqQuestionCacheModel.language = null;
		}

		faqQuestionCacheModel.questionOrder = getQuestionOrder();

		Date sentDate = getSentDate();

		if (sentDate != null) {
			faqQuestionCacheModel.sentDate = sentDate.getTime();
		}
		else {
			faqQuestionCacheModel.sentDate = Long.MIN_VALUE;
		}

		faqQuestionCacheModel.sentByUser = getSentByUser();

		String sentByUser = faqQuestionCacheModel.sentByUser;

		if ((sentByUser != null) && (sentByUser.length() == 0)) {
			faqQuestionCacheModel.sentByUser = null;
		}

		faqQuestionCacheModel.senderEmail = getSenderEmail();

		String senderEmail = faqQuestionCacheModel.senderEmail;

		if ((senderEmail != null) && (senderEmail.length() == 0)) {
			faqQuestionCacheModel.senderEmail = null;
		}

		faqQuestionCacheModel.questionType = getQuestionType();

		String questionType = faqQuestionCacheModel.questionType;

		if ((questionType != null) && (questionType.length() == 0)) {
			faqQuestionCacheModel.questionType = null;
		}

		faqQuestionCacheModel.modifiedByUser = getModifiedByUser();

		String modifiedByUser = faqQuestionCacheModel.modifiedByUser;

		if ((modifiedByUser != null) && (modifiedByUser.length() == 0)) {
			faqQuestionCacheModel.modifiedByUser = null;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			faqQuestionCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			faqQuestionCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		faqQuestionCacheModel.hitCount = getHitCount();

		faqQuestionCacheModel.approved = getApproved();

		faqQuestionCacheModel.groupId = getGroupId();

		faqQuestionCacheModel.userId = getUserId();

		faqQuestionCacheModel.categoryId = getCategoryId();

		return faqQuestionCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(33);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", title=");
		sb.append(getTitle());
		sb.append(", content=");
		sb.append(getContent());
		sb.append(", language=");
		sb.append(getLanguage());
		sb.append(", questionOrder=");
		sb.append(getQuestionOrder());
		sb.append(", sentDate=");
		sb.append(getSentDate());
		sb.append(", sentByUser=");
		sb.append(getSentByUser());
		sb.append(", senderEmail=");
		sb.append(getSenderEmail());
		sb.append(", questionType=");
		sb.append(getQuestionType());
		sb.append(", modifiedByUser=");
		sb.append(getModifiedByUser());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", hitCount=");
		sb.append(getHitCount());
		sb.append(", approved=");
		sb.append(getApproved());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", categoryId=");
		sb.append(getCategoryId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(52);

		sb.append("<model><model-name>");
		sb.append("vn.gov.hoabinh.model.FAQQuestion");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>title</column-name><column-value><![CDATA[");
		sb.append(getTitle());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>content</column-name><column-value><![CDATA[");
		sb.append(getContent());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>language</column-name><column-value><![CDATA[");
		sb.append(getLanguage());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>questionOrder</column-name><column-value><![CDATA[");
		sb.append(getQuestionOrder());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sentDate</column-name><column-value><![CDATA[");
		sb.append(getSentDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sentByUser</column-name><column-value><![CDATA[");
		sb.append(getSentByUser());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>senderEmail</column-name><column-value><![CDATA[");
		sb.append(getSenderEmail());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>questionType</column-name><column-value><![CDATA[");
		sb.append(getQuestionType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedByUser</column-name><column-value><![CDATA[");
		sb.append(getModifiedByUser());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>hitCount</column-name><column-value><![CDATA[");
		sb.append(getHitCount());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>approved</column-name><column-value><![CDATA[");
		sb.append(getApproved());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>categoryId</column-name><column-value><![CDATA[");
		sb.append(getCategoryId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = FAQQuestion.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			FAQQuestion.class
		};
	private long _id;
	private long _originalId;
	private boolean _setOriginalId;
	private String _title;
	private String _content;
	private String _language;
	private String _originalLanguage;
	private int _questionOrder;
	private Date _sentDate;
	private String _sentByUser;
	private String _senderEmail;
	private String _questionType;
	private String _originalQuestionType;
	private String _modifiedByUser;
	private Date _modifiedDate;
	private int _hitCount;
	private boolean _approved;
	private boolean _originalApproved;
	private boolean _setOriginalApproved;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _userId;
	private long _categoryId;
	private long _originalCategoryId;
	private boolean _setOriginalCategoryId;
	private long _columnBitmask;
	private FAQQuestion _escapedModel;
}