/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gov.hoabinh.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import vn.gov.hoabinh.model.VcmsTARelation;
import vn.gov.hoabinh.model.VcmsTARelationModel;
import vn.gov.hoabinh.service.persistence.VcmsTARelationPK;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the VcmsTARelation service. Represents a row in the &quot;VcmsTARelation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link VcmsTARelationModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VcmsTARelationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see VcmsTARelationImpl
 * @see VcmsTARelation
 * @see VcmsTARelationModel
 * @generated
 */
@ProviderType
public class VcmsTARelationModelImpl extends BaseModelImpl<VcmsTARelation>
	implements VcmsTARelationModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a vcms t a relation model instance should use the {@link VcmsTARelation} interface instead.
	 */
	public static final String TABLE_NAME = "VcmsTARelation";
	public static final Object[][] TABLE_COLUMNS = {
			{ "threadId", Types.VARCHAR },
			{ "articleId", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("threadId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("articleId", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table VcmsTARelation (threadId VARCHAR(75) not null,articleId VARCHAR(75) not null,primary key (threadId, articleId))";
	public static final String TABLE_SQL_DROP = "drop table VcmsTARelation";
	public static final String ORDER_BY_JPQL = " ORDER BY vcmsTARelation.id.articleId DESC, vcmsTARelation.id.threadId DESC";
	public static final String ORDER_BY_SQL = " ORDER BY VcmsTARelation.articleId DESC, VcmsTARelation.threadId DESC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(vn.gov.hoabinh.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.gov.hoabinh.model.VcmsTARelation"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(vn.gov.hoabinh.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.gov.hoabinh.model.VcmsTARelation"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(vn.gov.hoabinh.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.vn.gov.hoabinh.model.VcmsTARelation"),
			true);
	public static final long ARTICLEID_COLUMN_BITMASK = 1L;
	public static final long THREADID_COLUMN_BITMASK = 2L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(vn.gov.hoabinh.service.util.ServiceProps.get(
				"lock.expiration.time.vn.gov.hoabinh.model.VcmsTARelation"));

	public VcmsTARelationModelImpl() {
	}

	@Override
	public VcmsTARelationPK getPrimaryKey() {
		return new VcmsTARelationPK(_threadId, _articleId);
	}

	@Override
	public void setPrimaryKey(VcmsTARelationPK primaryKey) {
		setThreadId(primaryKey.threadId);
		setArticleId(primaryKey.articleId);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return new VcmsTARelationPK(_threadId, _articleId);
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((VcmsTARelationPK)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return VcmsTARelation.class;
	}

	@Override
	public String getModelClassName() {
		return VcmsTARelation.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("threadId", getThreadId());
		attributes.put("articleId", getArticleId());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String threadId = (String)attributes.get("threadId");

		if (threadId != null) {
			setThreadId(threadId);
		}

		String articleId = (String)attributes.get("articleId");

		if (articleId != null) {
			setArticleId(articleId);
		}
	}

	@Override
	public String getThreadId() {
		if (_threadId == null) {
			return StringPool.BLANK;
		}
		else {
			return _threadId;
		}
	}

	@Override
	public void setThreadId(String threadId) {
		_columnBitmask = -1L;

		if (_originalThreadId == null) {
			_originalThreadId = _threadId;
		}

		_threadId = threadId;
	}

	public String getOriginalThreadId() {
		return GetterUtil.getString(_originalThreadId);
	}

	@Override
	public String getArticleId() {
		if (_articleId == null) {
			return StringPool.BLANK;
		}
		else {
			return _articleId;
		}
	}

	@Override
	public void setArticleId(String articleId) {
		_columnBitmask = -1L;

		if (_originalArticleId == null) {
			_originalArticleId = _articleId;
		}

		_articleId = articleId;
	}

	public String getOriginalArticleId() {
		return GetterUtil.getString(_originalArticleId);
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public VcmsTARelation toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (VcmsTARelation)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		VcmsTARelationImpl vcmsTARelationImpl = new VcmsTARelationImpl();

		vcmsTARelationImpl.setThreadId(getThreadId());
		vcmsTARelationImpl.setArticleId(getArticleId());

		vcmsTARelationImpl.resetOriginalValues();

		return vcmsTARelationImpl;
	}

	@Override
	public int compareTo(VcmsTARelation vcmsTARelation) {
		int value = 0;

		value = getArticleId().compareTo(vcmsTARelation.getArticleId());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		value = getThreadId().compareTo(vcmsTARelation.getThreadId());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof VcmsTARelation)) {
			return false;
		}

		VcmsTARelation vcmsTARelation = (VcmsTARelation)obj;

		VcmsTARelationPK primaryKey = vcmsTARelation.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		VcmsTARelationModelImpl vcmsTARelationModelImpl = this;

		vcmsTARelationModelImpl._originalThreadId = vcmsTARelationModelImpl._threadId;

		vcmsTARelationModelImpl._originalArticleId = vcmsTARelationModelImpl._articleId;

		vcmsTARelationModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<VcmsTARelation> toCacheModel() {
		VcmsTARelationCacheModel vcmsTARelationCacheModel = new VcmsTARelationCacheModel();

		vcmsTARelationCacheModel.vcmsTARelationPK = getPrimaryKey();

		vcmsTARelationCacheModel.threadId = getThreadId();

		String threadId = vcmsTARelationCacheModel.threadId;

		if ((threadId != null) && (threadId.length() == 0)) {
			vcmsTARelationCacheModel.threadId = null;
		}

		vcmsTARelationCacheModel.articleId = getArticleId();

		String articleId = vcmsTARelationCacheModel.articleId;

		if ((articleId != null) && (articleId.length() == 0)) {
			vcmsTARelationCacheModel.articleId = null;
		}

		return vcmsTARelationCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{threadId=");
		sb.append(getThreadId());
		sb.append(", articleId=");
		sb.append(getArticleId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append("vn.gov.hoabinh.model.VcmsTARelation");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>threadId</column-name><column-value><![CDATA[");
		sb.append(getThreadId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>articleId</column-name><column-value><![CDATA[");
		sb.append(getArticleId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = VcmsTARelation.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			VcmsTARelation.class
		};
	private String _threadId;
	private String _originalThreadId;
	private String _articleId;
	private String _originalArticleId;
	private long _columnBitmask;
	private VcmsTARelation _escapedModel;
}