/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gov.hoabinh.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import vn.gov.hoabinh.model.VcmsCARelation;
import vn.gov.hoabinh.model.VcmsCARelationModel;
import vn.gov.hoabinh.service.persistence.VcmsCARelationPK;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the VcmsCARelation service. Represents a row in the &quot;VcmsCARelation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link VcmsCARelationModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VcmsCARelationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see VcmsCARelationImpl
 * @see VcmsCARelation
 * @see VcmsCARelationModel
 * @generated
 */
@ProviderType
public class VcmsCARelationModelImpl extends BaseModelImpl<VcmsCARelation>
	implements VcmsCARelationModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a vcms c a relation model instance should use the {@link VcmsCARelation} interface instead.
	 */
	public static final String TABLE_NAME = "VcmsCARelation";
	public static final Object[][] TABLE_COLUMNS = {
			{ "categoryId", Types.VARCHAR },
			{ "articleId", Types.VARCHAR },
			{ "createdDate", Types.TIMESTAMP },
			{ "createdByUser", Types.VARCHAR },
			{ "status", Types.BIGINT }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("categoryId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("articleId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createdDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("createdByUser", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("status", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE = "create table VcmsCARelation (categoryId VARCHAR(75) not null,articleId VARCHAR(75) not null,createdDate DATE null,createdByUser VARCHAR(75) null,status LONG,primary key (categoryId, articleId))";
	public static final String TABLE_SQL_DROP = "drop table VcmsCARelation";
	public static final String ORDER_BY_JPQL = " ORDER BY vcmsCARelation.id.articleId DESC, vcmsCARelation.id.categoryId DESC";
	public static final String ORDER_BY_SQL = " ORDER BY VcmsCARelation.articleId DESC, VcmsCARelation.categoryId DESC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(vn.gov.hoabinh.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.gov.hoabinh.model.VcmsCARelation"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(vn.gov.hoabinh.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.gov.hoabinh.model.VcmsCARelation"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(vn.gov.hoabinh.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.vn.gov.hoabinh.model.VcmsCARelation"),
			true);
	public static final long ARTICLEID_COLUMN_BITMASK = 1L;
	public static final long CATEGORYID_COLUMN_BITMASK = 2L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(vn.gov.hoabinh.service.util.ServiceProps.get(
				"lock.expiration.time.vn.gov.hoabinh.model.VcmsCARelation"));

	public VcmsCARelationModelImpl() {
	}

	@Override
	public VcmsCARelationPK getPrimaryKey() {
		return new VcmsCARelationPK(_categoryId, _articleId);
	}

	@Override
	public void setPrimaryKey(VcmsCARelationPK primaryKey) {
		setCategoryId(primaryKey.categoryId);
		setArticleId(primaryKey.articleId);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return new VcmsCARelationPK(_categoryId, _articleId);
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((VcmsCARelationPK)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return VcmsCARelation.class;
	}

	@Override
	public String getModelClassName() {
		return VcmsCARelation.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("categoryId", getCategoryId());
		attributes.put("articleId", getArticleId());
		attributes.put("createdDate", getCreatedDate());
		attributes.put("createdByUser", getCreatedByUser());
		attributes.put("status", getStatus());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String categoryId = (String)attributes.get("categoryId");

		if (categoryId != null) {
			setCategoryId(categoryId);
		}

		String articleId = (String)attributes.get("articleId");

		if (articleId != null) {
			setArticleId(articleId);
		}

		Date createdDate = (Date)attributes.get("createdDate");

		if (createdDate != null) {
			setCreatedDate(createdDate);
		}

		String createdByUser = (String)attributes.get("createdByUser");

		if (createdByUser != null) {
			setCreatedByUser(createdByUser);
		}

		Long status = (Long)attributes.get("status");

		if (status != null) {
			setStatus(status);
		}
	}

	@Override
	public String getCategoryId() {
		if (_categoryId == null) {
			return StringPool.BLANK;
		}
		else {
			return _categoryId;
		}
	}

	@Override
	public void setCategoryId(String categoryId) {
		_columnBitmask = -1L;

		if (_originalCategoryId == null) {
			_originalCategoryId = _categoryId;
		}

		_categoryId = categoryId;
	}

	public String getOriginalCategoryId() {
		return GetterUtil.getString(_originalCategoryId);
	}

	@Override
	public String getArticleId() {
		if (_articleId == null) {
			return StringPool.BLANK;
		}
		else {
			return _articleId;
		}
	}

	@Override
	public void setArticleId(String articleId) {
		_columnBitmask = -1L;

		if (_originalArticleId == null) {
			_originalArticleId = _articleId;
		}

		_articleId = articleId;
	}

	public String getOriginalArticleId() {
		return GetterUtil.getString(_originalArticleId);
	}

	@Override
	public Date getCreatedDate() {
		return _createdDate;
	}

	@Override
	public void setCreatedDate(Date createdDate) {
		_createdDate = createdDate;
	}

	@Override
	public String getCreatedByUser() {
		if (_createdByUser == null) {
			return StringPool.BLANK;
		}
		else {
			return _createdByUser;
		}
	}

	@Override
	public void setCreatedByUser(String createdByUser) {
		_createdByUser = createdByUser;
	}

	@Override
	public long getStatus() {
		return _status;
	}

	@Override
	public void setStatus(long status) {
		_status = status;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public VcmsCARelation toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (VcmsCARelation)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		VcmsCARelationImpl vcmsCARelationImpl = new VcmsCARelationImpl();

		vcmsCARelationImpl.setCategoryId(getCategoryId());
		vcmsCARelationImpl.setArticleId(getArticleId());
		vcmsCARelationImpl.setCreatedDate(getCreatedDate());
		vcmsCARelationImpl.setCreatedByUser(getCreatedByUser());
		vcmsCARelationImpl.setStatus(getStatus());

		vcmsCARelationImpl.resetOriginalValues();

		return vcmsCARelationImpl;
	}

	@Override
	public int compareTo(VcmsCARelation vcmsCARelation) {
		int value = 0;

		value = getArticleId().compareTo(vcmsCARelation.getArticleId());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		value = getCategoryId().compareTo(vcmsCARelation.getCategoryId());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof VcmsCARelation)) {
			return false;
		}

		VcmsCARelation vcmsCARelation = (VcmsCARelation)obj;

		VcmsCARelationPK primaryKey = vcmsCARelation.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		VcmsCARelationModelImpl vcmsCARelationModelImpl = this;

		vcmsCARelationModelImpl._originalCategoryId = vcmsCARelationModelImpl._categoryId;

		vcmsCARelationModelImpl._originalArticleId = vcmsCARelationModelImpl._articleId;

		vcmsCARelationModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<VcmsCARelation> toCacheModel() {
		VcmsCARelationCacheModel vcmsCARelationCacheModel = new VcmsCARelationCacheModel();

		vcmsCARelationCacheModel.vcmsCARelationPK = getPrimaryKey();

		vcmsCARelationCacheModel.categoryId = getCategoryId();

		String categoryId = vcmsCARelationCacheModel.categoryId;

		if ((categoryId != null) && (categoryId.length() == 0)) {
			vcmsCARelationCacheModel.categoryId = null;
		}

		vcmsCARelationCacheModel.articleId = getArticleId();

		String articleId = vcmsCARelationCacheModel.articleId;

		if ((articleId != null) && (articleId.length() == 0)) {
			vcmsCARelationCacheModel.articleId = null;
		}

		Date createdDate = getCreatedDate();

		if (createdDate != null) {
			vcmsCARelationCacheModel.createdDate = createdDate.getTime();
		}
		else {
			vcmsCARelationCacheModel.createdDate = Long.MIN_VALUE;
		}

		vcmsCARelationCacheModel.createdByUser = getCreatedByUser();

		String createdByUser = vcmsCARelationCacheModel.createdByUser;

		if ((createdByUser != null) && (createdByUser.length() == 0)) {
			vcmsCARelationCacheModel.createdByUser = null;
		}

		vcmsCARelationCacheModel.status = getStatus();

		return vcmsCARelationCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(11);

		sb.append("{categoryId=");
		sb.append(getCategoryId());
		sb.append(", articleId=");
		sb.append(getArticleId());
		sb.append(", createdDate=");
		sb.append(getCreatedDate());
		sb.append(", createdByUser=");
		sb.append(getCreatedByUser());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(19);

		sb.append("<model><model-name>");
		sb.append("vn.gov.hoabinh.model.VcmsCARelation");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>categoryId</column-name><column-value><![CDATA[");
		sb.append(getCategoryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>articleId</column-name><column-value><![CDATA[");
		sb.append(getArticleId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdDate</column-name><column-value><![CDATA[");
		sb.append(getCreatedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdByUser</column-name><column-value><![CDATA[");
		sb.append(getCreatedByUser());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = VcmsCARelation.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			VcmsCARelation.class
		};
	private String _categoryId;
	private String _originalCategoryId;
	private String _articleId;
	private String _originalArticleId;
	private Date _createdDate;
	private String _createdByUser;
	private long _status;
	private long _columnBitmask;
	private VcmsCARelation _escapedModel;
}