/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gov.hoabinh.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import vn.gov.hoabinh.model.VcmsArticleRating;
import vn.gov.hoabinh.model.VcmsArticleRatingModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the VcmsArticleRating service. Represents a row in the &quot;VcmsArticleRating&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link VcmsArticleRatingModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VcmsArticleRatingImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see VcmsArticleRatingImpl
 * @see VcmsArticleRating
 * @see VcmsArticleRatingModel
 * @generated
 */
@ProviderType
public class VcmsArticleRatingModelImpl extends BaseModelImpl<VcmsArticleRating>
	implements VcmsArticleRatingModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a vcms article rating model instance should use the {@link VcmsArticleRating} interface instead.
	 */
	public static final String TABLE_NAME = "VcmsArticleRating";
	public static final Object[][] TABLE_COLUMNS = {
			{ "Id", Types.BIGINT },
			{ "createdDate", Types.TIMESTAMP },
			{ "articleId", Types.BIGINT },
			{ "rating", Types.INTEGER },
			{ "sessionId", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("Id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createdDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("articleId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("rating", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("sessionId", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table VcmsArticleRating (Id LONG not null primary key,createdDate DATE null,articleId LONG,rating INTEGER,sessionId VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table VcmsArticleRating";
	public static final String ORDER_BY_JPQL = " ORDER BY vcmsArticleRating.createdDate DESC";
	public static final String ORDER_BY_SQL = " ORDER BY VcmsArticleRating.createdDate DESC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(vn.gov.hoabinh.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.gov.hoabinh.model.VcmsArticleRating"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(vn.gov.hoabinh.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.gov.hoabinh.model.VcmsArticleRating"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(vn.gov.hoabinh.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.vn.gov.hoabinh.model.VcmsArticleRating"),
			true);
	public static final long ARTICLEID_COLUMN_BITMASK = 1L;
	public static final long SESSIONID_COLUMN_BITMASK = 2L;
	public static final long CREATEDDATE_COLUMN_BITMASK = 4L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(vn.gov.hoabinh.service.util.ServiceProps.get(
				"lock.expiration.time.vn.gov.hoabinh.model.VcmsArticleRating"));

	public VcmsArticleRatingModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _Id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _Id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return VcmsArticleRating.class;
	}

	@Override
	public String getModelClassName() {
		return VcmsArticleRating.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("Id", getId());
		attributes.put("createdDate", getCreatedDate());
		attributes.put("articleId", getArticleId());
		attributes.put("rating", getRating());
		attributes.put("sessionId", getSessionId());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long Id = (Long)attributes.get("Id");

		if (Id != null) {
			setId(Id);
		}

		Date createdDate = (Date)attributes.get("createdDate");

		if (createdDate != null) {
			setCreatedDate(createdDate);
		}

		Long articleId = (Long)attributes.get("articleId");

		if (articleId != null) {
			setArticleId(articleId);
		}

		Integer rating = (Integer)attributes.get("rating");

		if (rating != null) {
			setRating(rating);
		}

		String sessionId = (String)attributes.get("sessionId");

		if (sessionId != null) {
			setSessionId(sessionId);
		}
	}

	@Override
	public long getId() {
		return _Id;
	}

	@Override
	public void setId(long Id) {
		_Id = Id;
	}

	@Override
	public Date getCreatedDate() {
		return _createdDate;
	}

	@Override
	public void setCreatedDate(Date createdDate) {
		_columnBitmask = -1L;

		_createdDate = createdDate;
	}

	@Override
	public long getArticleId() {
		return _articleId;
	}

	@Override
	public void setArticleId(long articleId) {
		_columnBitmask |= ARTICLEID_COLUMN_BITMASK;

		if (!_setOriginalArticleId) {
			_setOriginalArticleId = true;

			_originalArticleId = _articleId;
		}

		_articleId = articleId;
	}

	public long getOriginalArticleId() {
		return _originalArticleId;
	}

	@Override
	public int getRating() {
		return _rating;
	}

	@Override
	public void setRating(int rating) {
		_rating = rating;
	}

	@Override
	public String getSessionId() {
		if (_sessionId == null) {
			return StringPool.BLANK;
		}
		else {
			return _sessionId;
		}
	}

	@Override
	public void setSessionId(String sessionId) {
		_columnBitmask |= SESSIONID_COLUMN_BITMASK;

		if (_originalSessionId == null) {
			_originalSessionId = _sessionId;
		}

		_sessionId = sessionId;
	}

	public String getOriginalSessionId() {
		return GetterUtil.getString(_originalSessionId);
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			VcmsArticleRating.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public VcmsArticleRating toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (VcmsArticleRating)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		VcmsArticleRatingImpl vcmsArticleRatingImpl = new VcmsArticleRatingImpl();

		vcmsArticleRatingImpl.setId(getId());
		vcmsArticleRatingImpl.setCreatedDate(getCreatedDate());
		vcmsArticleRatingImpl.setArticleId(getArticleId());
		vcmsArticleRatingImpl.setRating(getRating());
		vcmsArticleRatingImpl.setSessionId(getSessionId());

		vcmsArticleRatingImpl.resetOriginalValues();

		return vcmsArticleRatingImpl;
	}

	@Override
	public int compareTo(VcmsArticleRating vcmsArticleRating) {
		int value = 0;

		value = DateUtil.compareTo(getCreatedDate(),
				vcmsArticleRating.getCreatedDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof VcmsArticleRating)) {
			return false;
		}

		VcmsArticleRating vcmsArticleRating = (VcmsArticleRating)obj;

		long primaryKey = vcmsArticleRating.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		VcmsArticleRatingModelImpl vcmsArticleRatingModelImpl = this;

		vcmsArticleRatingModelImpl._originalArticleId = vcmsArticleRatingModelImpl._articleId;

		vcmsArticleRatingModelImpl._setOriginalArticleId = false;

		vcmsArticleRatingModelImpl._originalSessionId = vcmsArticleRatingModelImpl._sessionId;

		vcmsArticleRatingModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<VcmsArticleRating> toCacheModel() {
		VcmsArticleRatingCacheModel vcmsArticleRatingCacheModel = new VcmsArticleRatingCacheModel();

		vcmsArticleRatingCacheModel.Id = getId();

		Date createdDate = getCreatedDate();

		if (createdDate != null) {
			vcmsArticleRatingCacheModel.createdDate = createdDate.getTime();
		}
		else {
			vcmsArticleRatingCacheModel.createdDate = Long.MIN_VALUE;
		}

		vcmsArticleRatingCacheModel.articleId = getArticleId();

		vcmsArticleRatingCacheModel.rating = getRating();

		vcmsArticleRatingCacheModel.sessionId = getSessionId();

		String sessionId = vcmsArticleRatingCacheModel.sessionId;

		if ((sessionId != null) && (sessionId.length() == 0)) {
			vcmsArticleRatingCacheModel.sessionId = null;
		}

		return vcmsArticleRatingCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(11);

		sb.append("{Id=");
		sb.append(getId());
		sb.append(", createdDate=");
		sb.append(getCreatedDate());
		sb.append(", articleId=");
		sb.append(getArticleId());
		sb.append(", rating=");
		sb.append(getRating());
		sb.append(", sessionId=");
		sb.append(getSessionId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(19);

		sb.append("<model><model-name>");
		sb.append("vn.gov.hoabinh.model.VcmsArticleRating");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>Id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdDate</column-name><column-value><![CDATA[");
		sb.append(getCreatedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>articleId</column-name><column-value><![CDATA[");
		sb.append(getArticleId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>rating</column-name><column-value><![CDATA[");
		sb.append(getRating());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sessionId</column-name><column-value><![CDATA[");
		sb.append(getSessionId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = VcmsArticleRating.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			VcmsArticleRating.class
		};
	private long _Id;
	private Date _createdDate;
	private long _articleId;
	private long _originalArticleId;
	private boolean _setOriginalArticleId;
	private int _rating;
	private String _sessionId;
	private String _originalSessionId;
	private long _columnBitmask;
	private VcmsArticleRating _escapedModel;
}