/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gov.hoabinh.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import vn.gov.hoabinh.model.VcmsStatus;
import vn.gov.hoabinh.model.VcmsStatusModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the VcmsStatus service. Represents a row in the &quot;VcmsStatus&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link VcmsStatusModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VcmsStatusImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see VcmsStatusImpl
 * @see VcmsStatus
 * @see VcmsStatusModel
 * @generated
 */
@ProviderType
public class VcmsStatusModelImpl extends BaseModelImpl<VcmsStatus>
	implements VcmsStatusModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a vcms status model instance should use the {@link VcmsStatus} interface instead.
	 */
	public static final String TABLE_NAME = "VcmsStatus";
	public static final Object[][] TABLE_COLUMNS = {
			{ "statusId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "createdDate", Types.TIMESTAMP },
			{ "createdByUser", Types.VARCHAR },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "modifiedByUser", Types.VARCHAR },
			{ "name", Types.VARCHAR },
			{ "description", Types.VARCHAR },
			{ "cssClass", Types.VARCHAR },
			{ "textColor", Types.VARCHAR },
			{ "position", Types.INTEGER },
			{ "isPrimary", Types.BOOLEAN },
			{ "active_", Types.BOOLEAN }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("statusId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createdDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("createdByUser", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedByUser", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("cssClass", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("textColor", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("position", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("isPrimary", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("active_", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE = "create table VcmsStatus (statusId LONG not null primary key,companyId LONG,groupId LONG,createdDate DATE null,createdByUser VARCHAR(75) null,modifiedDate DATE null,modifiedByUser VARCHAR(75) null,name VARCHAR(75) null,description VARCHAR(75) null,cssClass VARCHAR(75) null,textColor VARCHAR(75) null,position INTEGER,isPrimary BOOLEAN,active_ BOOLEAN)";
	public static final String TABLE_SQL_DROP = "drop table VcmsStatus";
	public static final String ORDER_BY_JPQL = " ORDER BY vcmsStatus.position ASC, vcmsStatus.createdDate DESC";
	public static final String ORDER_BY_SQL = " ORDER BY VcmsStatus.position ASC, VcmsStatus.createdDate DESC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(vn.gov.hoabinh.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.gov.hoabinh.model.VcmsStatus"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(vn.gov.hoabinh.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.gov.hoabinh.model.VcmsStatus"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(vn.gov.hoabinh.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.vn.gov.hoabinh.model.VcmsStatus"),
			true);
	public static final long ACTIVE_COLUMN_BITMASK = 1L;
	public static final long COMPANYID_COLUMN_BITMASK = 2L;
	public static final long GROUPID_COLUMN_BITMASK = 4L;
	public static final long ISPRIMARY_COLUMN_BITMASK = 8L;
	public static final long POSITION_COLUMN_BITMASK = 16L;
	public static final long CREATEDDATE_COLUMN_BITMASK = 32L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(vn.gov.hoabinh.service.util.ServiceProps.get(
				"lock.expiration.time.vn.gov.hoabinh.model.VcmsStatus"));

	public VcmsStatusModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _statusId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setStatusId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _statusId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return VcmsStatus.class;
	}

	@Override
	public String getModelClassName() {
		return VcmsStatus.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("statusId", getStatusId());
		attributes.put("companyId", getCompanyId());
		attributes.put("groupId", getGroupId());
		attributes.put("createdDate", getCreatedDate());
		attributes.put("createdByUser", getCreatedByUser());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("modifiedByUser", getModifiedByUser());
		attributes.put("name", getName());
		attributes.put("description", getDescription());
		attributes.put("cssClass", getCssClass());
		attributes.put("textColor", getTextColor());
		attributes.put("position", getPosition());
		attributes.put("isPrimary", getIsPrimary());
		attributes.put("active", getActive());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long statusId = (Long)attributes.get("statusId");

		if (statusId != null) {
			setStatusId(statusId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Date createdDate = (Date)attributes.get("createdDate");

		if (createdDate != null) {
			setCreatedDate(createdDate);
		}

		String createdByUser = (String)attributes.get("createdByUser");

		if (createdByUser != null) {
			setCreatedByUser(createdByUser);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String modifiedByUser = (String)attributes.get("modifiedByUser");

		if (modifiedByUser != null) {
			setModifiedByUser(modifiedByUser);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}

		String description = (String)attributes.get("description");

		if (description != null) {
			setDescription(description);
		}

		String cssClass = (String)attributes.get("cssClass");

		if (cssClass != null) {
			setCssClass(cssClass);
		}

		String textColor = (String)attributes.get("textColor");

		if (textColor != null) {
			setTextColor(textColor);
		}

		Integer position = (Integer)attributes.get("position");

		if (position != null) {
			setPosition(position);
		}

		Boolean isPrimary = (Boolean)attributes.get("isPrimary");

		if (isPrimary != null) {
			setIsPrimary(isPrimary);
		}

		Boolean active = (Boolean)attributes.get("active");

		if (active != null) {
			setActive(active);
		}
	}

	@Override
	public long getStatusId() {
		return _statusId;
	}

	@Override
	public void setStatusId(long statusId) {
		_statusId = statusId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public Date getCreatedDate() {
		return _createdDate;
	}

	@Override
	public void setCreatedDate(Date createdDate) {
		_columnBitmask = -1L;

		_createdDate = createdDate;
	}

	@Override
	public String getCreatedByUser() {
		if (_createdByUser == null) {
			return StringPool.BLANK;
		}
		else {
			return _createdByUser;
		}
	}

	@Override
	public void setCreatedByUser(String createdByUser) {
		_createdByUser = createdByUser;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@Override
	public String getModifiedByUser() {
		if (_modifiedByUser == null) {
			return StringPool.BLANK;
		}
		else {
			return _modifiedByUser;
		}
	}

	@Override
	public void setModifiedByUser(String modifiedByUser) {
		_modifiedByUser = modifiedByUser;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@Override
	public String getDescription() {
		if (_description == null) {
			return StringPool.BLANK;
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	@Override
	public String getCssClass() {
		if (_cssClass == null) {
			return StringPool.BLANK;
		}
		else {
			return _cssClass;
		}
	}

	@Override
	public void setCssClass(String cssClass) {
		_cssClass = cssClass;
	}

	@Override
	public String getTextColor() {
		if (_textColor == null) {
			return StringPool.BLANK;
		}
		else {
			return _textColor;
		}
	}

	@Override
	public void setTextColor(String textColor) {
		_textColor = textColor;
	}

	@Override
	public int getPosition() {
		return _position;
	}

	@Override
	public void setPosition(int position) {
		_columnBitmask = -1L;

		if (!_setOriginalPosition) {
			_setOriginalPosition = true;

			_originalPosition = _position;
		}

		_position = position;
	}

	public int getOriginalPosition() {
		return _originalPosition;
	}

	@Override
	public boolean getIsPrimary() {
		return _isPrimary;
	}

	@Override
	public boolean isIsPrimary() {
		return _isPrimary;
	}

	@Override
	public void setIsPrimary(boolean isPrimary) {
		_columnBitmask |= ISPRIMARY_COLUMN_BITMASK;

		if (!_setOriginalIsPrimary) {
			_setOriginalIsPrimary = true;

			_originalIsPrimary = _isPrimary;
		}

		_isPrimary = isPrimary;
	}

	public boolean getOriginalIsPrimary() {
		return _originalIsPrimary;
	}

	@Override
	public boolean getActive() {
		return _active;
	}

	@Override
	public boolean isActive() {
		return _active;
	}

	@Override
	public void setActive(boolean active) {
		_columnBitmask |= ACTIVE_COLUMN_BITMASK;

		if (!_setOriginalActive) {
			_setOriginalActive = true;

			_originalActive = _active;
		}

		_active = active;
	}

	public boolean getOriginalActive() {
		return _originalActive;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			VcmsStatus.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public VcmsStatus toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (VcmsStatus)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		VcmsStatusImpl vcmsStatusImpl = new VcmsStatusImpl();

		vcmsStatusImpl.setStatusId(getStatusId());
		vcmsStatusImpl.setCompanyId(getCompanyId());
		vcmsStatusImpl.setGroupId(getGroupId());
		vcmsStatusImpl.setCreatedDate(getCreatedDate());
		vcmsStatusImpl.setCreatedByUser(getCreatedByUser());
		vcmsStatusImpl.setModifiedDate(getModifiedDate());
		vcmsStatusImpl.setModifiedByUser(getModifiedByUser());
		vcmsStatusImpl.setName(getName());
		vcmsStatusImpl.setDescription(getDescription());
		vcmsStatusImpl.setCssClass(getCssClass());
		vcmsStatusImpl.setTextColor(getTextColor());
		vcmsStatusImpl.setPosition(getPosition());
		vcmsStatusImpl.setIsPrimary(getIsPrimary());
		vcmsStatusImpl.setActive(getActive());

		vcmsStatusImpl.resetOriginalValues();

		return vcmsStatusImpl;
	}

	@Override
	public int compareTo(VcmsStatus vcmsStatus) {
		int value = 0;

		if (getPosition() < vcmsStatus.getPosition()) {
			value = -1;
		}
		else if (getPosition() > vcmsStatus.getPosition()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		value = DateUtil.compareTo(getCreatedDate(), vcmsStatus.getCreatedDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof VcmsStatus)) {
			return false;
		}

		VcmsStatus vcmsStatus = (VcmsStatus)obj;

		long primaryKey = vcmsStatus.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		VcmsStatusModelImpl vcmsStatusModelImpl = this;

		vcmsStatusModelImpl._originalCompanyId = vcmsStatusModelImpl._companyId;

		vcmsStatusModelImpl._setOriginalCompanyId = false;

		vcmsStatusModelImpl._originalGroupId = vcmsStatusModelImpl._groupId;

		vcmsStatusModelImpl._setOriginalGroupId = false;

		vcmsStatusModelImpl._originalPosition = vcmsStatusModelImpl._position;

		vcmsStatusModelImpl._setOriginalPosition = false;

		vcmsStatusModelImpl._originalIsPrimary = vcmsStatusModelImpl._isPrimary;

		vcmsStatusModelImpl._setOriginalIsPrimary = false;

		vcmsStatusModelImpl._originalActive = vcmsStatusModelImpl._active;

		vcmsStatusModelImpl._setOriginalActive = false;

		vcmsStatusModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<VcmsStatus> toCacheModel() {
		VcmsStatusCacheModel vcmsStatusCacheModel = new VcmsStatusCacheModel();

		vcmsStatusCacheModel.statusId = getStatusId();

		vcmsStatusCacheModel.companyId = getCompanyId();

		vcmsStatusCacheModel.groupId = getGroupId();

		Date createdDate = getCreatedDate();

		if (createdDate != null) {
			vcmsStatusCacheModel.createdDate = createdDate.getTime();
		}
		else {
			vcmsStatusCacheModel.createdDate = Long.MIN_VALUE;
		}

		vcmsStatusCacheModel.createdByUser = getCreatedByUser();

		String createdByUser = vcmsStatusCacheModel.createdByUser;

		if ((createdByUser != null) && (createdByUser.length() == 0)) {
			vcmsStatusCacheModel.createdByUser = null;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			vcmsStatusCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			vcmsStatusCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		vcmsStatusCacheModel.modifiedByUser = getModifiedByUser();

		String modifiedByUser = vcmsStatusCacheModel.modifiedByUser;

		if ((modifiedByUser != null) && (modifiedByUser.length() == 0)) {
			vcmsStatusCacheModel.modifiedByUser = null;
		}

		vcmsStatusCacheModel.name = getName();

		String name = vcmsStatusCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			vcmsStatusCacheModel.name = null;
		}

		vcmsStatusCacheModel.description = getDescription();

		String description = vcmsStatusCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			vcmsStatusCacheModel.description = null;
		}

		vcmsStatusCacheModel.cssClass = getCssClass();

		String cssClass = vcmsStatusCacheModel.cssClass;

		if ((cssClass != null) && (cssClass.length() == 0)) {
			vcmsStatusCacheModel.cssClass = null;
		}

		vcmsStatusCacheModel.textColor = getTextColor();

		String textColor = vcmsStatusCacheModel.textColor;

		if ((textColor != null) && (textColor.length() == 0)) {
			vcmsStatusCacheModel.textColor = null;
		}

		vcmsStatusCacheModel.position = getPosition();

		vcmsStatusCacheModel.isPrimary = getIsPrimary();

		vcmsStatusCacheModel.active = getActive();

		return vcmsStatusCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(29);

		sb.append("{statusId=");
		sb.append(getStatusId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", createdDate=");
		sb.append(getCreatedDate());
		sb.append(", createdByUser=");
		sb.append(getCreatedByUser());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", modifiedByUser=");
		sb.append(getModifiedByUser());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", description=");
		sb.append(getDescription());
		sb.append(", cssClass=");
		sb.append(getCssClass());
		sb.append(", textColor=");
		sb.append(getTextColor());
		sb.append(", position=");
		sb.append(getPosition());
		sb.append(", isPrimary=");
		sb.append(getIsPrimary());
		sb.append(", active=");
		sb.append(getActive());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(46);

		sb.append("<model><model-name>");
		sb.append("vn.gov.hoabinh.model.VcmsStatus");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>statusId</column-name><column-value><![CDATA[");
		sb.append(getStatusId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdDate</column-name><column-value><![CDATA[");
		sb.append(getCreatedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdByUser</column-name><column-value><![CDATA[");
		sb.append(getCreatedByUser());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedByUser</column-name><column-value><![CDATA[");
		sb.append(getModifiedByUser());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>description</column-name><column-value><![CDATA[");
		sb.append(getDescription());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>cssClass</column-name><column-value><![CDATA[");
		sb.append(getCssClass());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>textColor</column-name><column-value><![CDATA[");
		sb.append(getTextColor());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>position</column-name><column-value><![CDATA[");
		sb.append(getPosition());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>isPrimary</column-name><column-value><![CDATA[");
		sb.append(getIsPrimary());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>active</column-name><column-value><![CDATA[");
		sb.append(getActive());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = VcmsStatus.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			VcmsStatus.class
		};
	private long _statusId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private Date _createdDate;
	private String _createdByUser;
	private Date _modifiedDate;
	private String _modifiedByUser;
	private String _name;
	private String _description;
	private String _cssClass;
	private String _textColor;
	private int _position;
	private int _originalPosition;
	private boolean _setOriginalPosition;
	private boolean _isPrimary;
	private boolean _originalIsPrimary;
	private boolean _setOriginalIsPrimary;
	private boolean _active;
	private boolean _originalActive;
	private boolean _setOriginalActive;
	private long _columnBitmask;
	private VcmsStatus _escapedModel;
}