/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gov.hoabinh.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import vn.gov.hoabinh.model.VLegalOrg;
import vn.gov.hoabinh.model.VLegalOrgModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the VLegalOrg service. Represents a row in the &quot;VLegalOrg&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link VLegalOrgModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VLegalOrgImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see VLegalOrgImpl
 * @see VLegalOrg
 * @see VLegalOrgModel
 * @generated
 */
@ProviderType
public class VLegalOrgModelImpl extends BaseModelImpl<VLegalOrg>
	implements VLegalOrgModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a v legal org model instance should use the {@link VLegalOrg} interface instead.
	 */
	public static final String TABLE_NAME = "VLegalOrg";
	public static final Object[][] TABLE_COLUMNS = {
			{ "orgId", Types.VARCHAR },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "createdDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "createdByUser", Types.BIGINT },
			{ "modifiedByUser", Types.BIGINT },
			{ "name", Types.VARCHAR },
			{ "description", Types.VARCHAR },
			{ "parentId", Types.VARCHAR },
			{ "language", Types.VARCHAR },
			{ "statusOrg", Types.BOOLEAN },
			{ "rssable", Types.BOOLEAN },
			{ "position", Types.INTEGER }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("orgId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createdDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("createdByUser", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedByUser", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("parentId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("language", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusOrg", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("rssable", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("position", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE = "create table VLegalOrg (orgId VARCHAR(75) not null primary key,groupId LONG,companyId LONG,userId LONG,createdDate DATE null,modifiedDate DATE null,createdByUser LONG,modifiedByUser LONG,name VARCHAR(75) null,description VARCHAR(75) null,parentId VARCHAR(75) null,language VARCHAR(75) null,statusOrg BOOLEAN,rssable BOOLEAN,position INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table VLegalOrg";
	public static final String ORDER_BY_JPQL = " ORDER BY vLegalOrg.position ASC";
	public static final String ORDER_BY_SQL = " ORDER BY VLegalOrg.position ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(vn.gov.hoabinh.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.gov.hoabinh.model.VLegalOrg"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(vn.gov.hoabinh.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.gov.hoabinh.model.VLegalOrg"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(vn.gov.hoabinh.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.vn.gov.hoabinh.model.VLegalOrg"),
			true);
	public static final long GROUPID_COLUMN_BITMASK = 1L;
	public static final long LANGUAGE_COLUMN_BITMASK = 2L;
	public static final long ORGID_COLUMN_BITMASK = 4L;
	public static final long PARENTID_COLUMN_BITMASK = 8L;
	public static final long RSSABLE_COLUMN_BITMASK = 16L;
	public static final long STATUSORG_COLUMN_BITMASK = 32L;
	public static final long POSITION_COLUMN_BITMASK = 64L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(vn.gov.hoabinh.service.util.ServiceProps.get(
				"lock.expiration.time.vn.gov.hoabinh.model.VLegalOrg"));

	public VLegalOrgModelImpl() {
	}

	@Override
	public String getPrimaryKey() {
		return _orgId;
	}

	@Override
	public void setPrimaryKey(String primaryKey) {
		setOrgId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _orgId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((String)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return VLegalOrg.class;
	}

	@Override
	public String getModelClassName() {
		return VLegalOrg.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("orgId", getOrgId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("createdDate", getCreatedDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("createdByUser", getCreatedByUser());
		attributes.put("modifiedByUser", getModifiedByUser());
		attributes.put("name", getName());
		attributes.put("description", getDescription());
		attributes.put("parentId", getParentId());
		attributes.put("language", getLanguage());
		attributes.put("statusOrg", getStatusOrg());
		attributes.put("rssable", getRssable());
		attributes.put("position", getPosition());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String orgId = (String)attributes.get("orgId");

		if (orgId != null) {
			setOrgId(orgId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Date createdDate = (Date)attributes.get("createdDate");

		if (createdDate != null) {
			setCreatedDate(createdDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long createdByUser = (Long)attributes.get("createdByUser");

		if (createdByUser != null) {
			setCreatedByUser(createdByUser);
		}

		Long modifiedByUser = (Long)attributes.get("modifiedByUser");

		if (modifiedByUser != null) {
			setModifiedByUser(modifiedByUser);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}

		String description = (String)attributes.get("description");

		if (description != null) {
			setDescription(description);
		}

		String parentId = (String)attributes.get("parentId");

		if (parentId != null) {
			setParentId(parentId);
		}

		String language = (String)attributes.get("language");

		if (language != null) {
			setLanguage(language);
		}

		Boolean statusOrg = (Boolean)attributes.get("statusOrg");

		if (statusOrg != null) {
			setStatusOrg(statusOrg);
		}

		Boolean rssable = (Boolean)attributes.get("rssable");

		if (rssable != null) {
			setRssable(rssable);
		}

		Integer position = (Integer)attributes.get("position");

		if (position != null) {
			setPosition(position);
		}
	}

	@Override
	public String getOrgId() {
		if (_orgId == null) {
			return StringPool.BLANK;
		}
		else {
			return _orgId;
		}
	}

	@Override
	public void setOrgId(String orgId) {
		_columnBitmask |= ORGID_COLUMN_BITMASK;

		if (_originalOrgId == null) {
			_originalOrgId = _orgId;
		}

		_orgId = orgId;
	}

	public String getOriginalOrgId() {
		return GetterUtil.getString(_originalOrgId);
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public Date getCreatedDate() {
		return _createdDate;
	}

	@Override
	public void setCreatedDate(Date createdDate) {
		_createdDate = createdDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@Override
	public long getCreatedByUser() {
		return _createdByUser;
	}

	@Override
	public void setCreatedByUser(long createdByUser) {
		_createdByUser = createdByUser;
	}

	@Override
	public long getModifiedByUser() {
		return _modifiedByUser;
	}

	@Override
	public void setModifiedByUser(long modifiedByUser) {
		_modifiedByUser = modifiedByUser;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@Override
	public String getDescription() {
		if (_description == null) {
			return StringPool.BLANK;
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	@Override
	public String getParentId() {
		if (_parentId == null) {
			return StringPool.BLANK;
		}
		else {
			return _parentId;
		}
	}

	@Override
	public void setParentId(String parentId) {
		_columnBitmask |= PARENTID_COLUMN_BITMASK;

		if (_originalParentId == null) {
			_originalParentId = _parentId;
		}

		_parentId = parentId;
	}

	public String getOriginalParentId() {
		return GetterUtil.getString(_originalParentId);
	}

	@Override
	public String getLanguage() {
		if (_language == null) {
			return StringPool.BLANK;
		}
		else {
			return _language;
		}
	}

	@Override
	public void setLanguage(String language) {
		_columnBitmask |= LANGUAGE_COLUMN_BITMASK;

		if (_originalLanguage == null) {
			_originalLanguage = _language;
		}

		_language = language;
	}

	public String getOriginalLanguage() {
		return GetterUtil.getString(_originalLanguage);
	}

	@Override
	public boolean getStatusOrg() {
		return _statusOrg;
	}

	@Override
	public boolean isStatusOrg() {
		return _statusOrg;
	}

	@Override
	public void setStatusOrg(boolean statusOrg) {
		_columnBitmask |= STATUSORG_COLUMN_BITMASK;

		if (!_setOriginalStatusOrg) {
			_setOriginalStatusOrg = true;

			_originalStatusOrg = _statusOrg;
		}

		_statusOrg = statusOrg;
	}

	public boolean getOriginalStatusOrg() {
		return _originalStatusOrg;
	}

	@Override
	public boolean getRssable() {
		return _rssable;
	}

	@Override
	public boolean isRssable() {
		return _rssable;
	}

	@Override
	public void setRssable(boolean rssable) {
		_columnBitmask |= RSSABLE_COLUMN_BITMASK;

		if (!_setOriginalRssable) {
			_setOriginalRssable = true;

			_originalRssable = _rssable;
		}

		_rssable = rssable;
	}

	public boolean getOriginalRssable() {
		return _originalRssable;
	}

	@Override
	public int getPosition() {
		return _position;
	}

	@Override
	public void setPosition(int position) {
		_columnBitmask = -1L;

		_position = position;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public VLegalOrg toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (VLegalOrg)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		VLegalOrgImpl vLegalOrgImpl = new VLegalOrgImpl();

		vLegalOrgImpl.setOrgId(getOrgId());
		vLegalOrgImpl.setGroupId(getGroupId());
		vLegalOrgImpl.setCompanyId(getCompanyId());
		vLegalOrgImpl.setUserId(getUserId());
		vLegalOrgImpl.setCreatedDate(getCreatedDate());
		vLegalOrgImpl.setModifiedDate(getModifiedDate());
		vLegalOrgImpl.setCreatedByUser(getCreatedByUser());
		vLegalOrgImpl.setModifiedByUser(getModifiedByUser());
		vLegalOrgImpl.setName(getName());
		vLegalOrgImpl.setDescription(getDescription());
		vLegalOrgImpl.setParentId(getParentId());
		vLegalOrgImpl.setLanguage(getLanguage());
		vLegalOrgImpl.setStatusOrg(getStatusOrg());
		vLegalOrgImpl.setRssable(getRssable());
		vLegalOrgImpl.setPosition(getPosition());

		vLegalOrgImpl.resetOriginalValues();

		return vLegalOrgImpl;
	}

	@Override
	public int compareTo(VLegalOrg vLegalOrg) {
		int value = 0;

		if (getPosition() < vLegalOrg.getPosition()) {
			value = -1;
		}
		else if (getPosition() > vLegalOrg.getPosition()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof VLegalOrg)) {
			return false;
		}

		VLegalOrg vLegalOrg = (VLegalOrg)obj;

		String primaryKey = vLegalOrg.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		VLegalOrgModelImpl vLegalOrgModelImpl = this;

		vLegalOrgModelImpl._originalOrgId = vLegalOrgModelImpl._orgId;

		vLegalOrgModelImpl._originalGroupId = vLegalOrgModelImpl._groupId;

		vLegalOrgModelImpl._setOriginalGroupId = false;

		vLegalOrgModelImpl._originalParentId = vLegalOrgModelImpl._parentId;

		vLegalOrgModelImpl._originalLanguage = vLegalOrgModelImpl._language;

		vLegalOrgModelImpl._originalStatusOrg = vLegalOrgModelImpl._statusOrg;

		vLegalOrgModelImpl._setOriginalStatusOrg = false;

		vLegalOrgModelImpl._originalRssable = vLegalOrgModelImpl._rssable;

		vLegalOrgModelImpl._setOriginalRssable = false;

		vLegalOrgModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<VLegalOrg> toCacheModel() {
		VLegalOrgCacheModel vLegalOrgCacheModel = new VLegalOrgCacheModel();

		vLegalOrgCacheModel.orgId = getOrgId();

		String orgId = vLegalOrgCacheModel.orgId;

		if ((orgId != null) && (orgId.length() == 0)) {
			vLegalOrgCacheModel.orgId = null;
		}

		vLegalOrgCacheModel.groupId = getGroupId();

		vLegalOrgCacheModel.companyId = getCompanyId();

		vLegalOrgCacheModel.userId = getUserId();

		Date createdDate = getCreatedDate();

		if (createdDate != null) {
			vLegalOrgCacheModel.createdDate = createdDate.getTime();
		}
		else {
			vLegalOrgCacheModel.createdDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			vLegalOrgCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			vLegalOrgCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		vLegalOrgCacheModel.createdByUser = getCreatedByUser();

		vLegalOrgCacheModel.modifiedByUser = getModifiedByUser();

		vLegalOrgCacheModel.name = getName();

		String name = vLegalOrgCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			vLegalOrgCacheModel.name = null;
		}

		vLegalOrgCacheModel.description = getDescription();

		String description = vLegalOrgCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			vLegalOrgCacheModel.description = null;
		}

		vLegalOrgCacheModel.parentId = getParentId();

		String parentId = vLegalOrgCacheModel.parentId;

		if ((parentId != null) && (parentId.length() == 0)) {
			vLegalOrgCacheModel.parentId = null;
		}

		vLegalOrgCacheModel.language = getLanguage();

		String language = vLegalOrgCacheModel.language;

		if ((language != null) && (language.length() == 0)) {
			vLegalOrgCacheModel.language = null;
		}

		vLegalOrgCacheModel.statusOrg = getStatusOrg();

		vLegalOrgCacheModel.rssable = getRssable();

		vLegalOrgCacheModel.position = getPosition();

		return vLegalOrgCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(31);

		sb.append("{orgId=");
		sb.append(getOrgId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", createdDate=");
		sb.append(getCreatedDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", createdByUser=");
		sb.append(getCreatedByUser());
		sb.append(", modifiedByUser=");
		sb.append(getModifiedByUser());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", description=");
		sb.append(getDescription());
		sb.append(", parentId=");
		sb.append(getParentId());
		sb.append(", language=");
		sb.append(getLanguage());
		sb.append(", statusOrg=");
		sb.append(getStatusOrg());
		sb.append(", rssable=");
		sb.append(getRssable());
		sb.append(", position=");
		sb.append(getPosition());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(49);

		sb.append("<model><model-name>");
		sb.append("vn.gov.hoabinh.model.VLegalOrg");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>orgId</column-name><column-value><![CDATA[");
		sb.append(getOrgId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdDate</column-name><column-value><![CDATA[");
		sb.append(getCreatedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdByUser</column-name><column-value><![CDATA[");
		sb.append(getCreatedByUser());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedByUser</column-name><column-value><![CDATA[");
		sb.append(getModifiedByUser());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>description</column-name><column-value><![CDATA[");
		sb.append(getDescription());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>parentId</column-name><column-value><![CDATA[");
		sb.append(getParentId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>language</column-name><column-value><![CDATA[");
		sb.append(getLanguage());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>statusOrg</column-name><column-value><![CDATA[");
		sb.append(getStatusOrg());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>rssable</column-name><column-value><![CDATA[");
		sb.append(getRssable());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>position</column-name><column-value><![CDATA[");
		sb.append(getPosition());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = VLegalOrg.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			VLegalOrg.class
		};
	private String _orgId;
	private String _originalOrgId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _userId;
	private Date _createdDate;
	private Date _modifiedDate;
	private long _createdByUser;
	private long _modifiedByUser;
	private String _name;
	private String _description;
	private String _parentId;
	private String _originalParentId;
	private String _language;
	private String _originalLanguage;
	private boolean _statusOrg;
	private boolean _originalStatusOrg;
	private boolean _setOriginalStatusOrg;
	private boolean _rssable;
	private boolean _originalRssable;
	private boolean _setOriginalRssable;
	private int _position;
	private long _columnBitmask;
	private VLegalOrg _escapedModel;
}