/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gov.hoabinh.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import vn.gov.hoabinh.model.VLegalDFRel;
import vn.gov.hoabinh.model.VLegalDFRelModel;
import vn.gov.hoabinh.service.persistence.VLegalDFRelPK;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the VLegalDFRel service. Represents a row in the &quot;VLegalDFRel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link VLegalDFRelModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VLegalDFRelImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see VLegalDFRelImpl
 * @see VLegalDFRel
 * @see VLegalDFRelModel
 * @generated
 */
@ProviderType
public class VLegalDFRelModelImpl extends BaseModelImpl<VLegalDFRel>
	implements VLegalDFRelModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a v legal d f rel model instance should use the {@link VLegalDFRel} interface instead.
	 */
	public static final String TABLE_NAME = "VLegalDFRel";
	public static final Object[][] TABLE_COLUMNS = {
			{ "fieldId", Types.VARCHAR },
			{ "docId", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("fieldId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("docId", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table VLegalDFRel (fieldId VARCHAR(75) not null,docId VARCHAR(75) not null,primary key (fieldId, docId))";
	public static final String TABLE_SQL_DROP = "drop table VLegalDFRel";
	public static final String ORDER_BY_JPQL = " ORDER BY vLegalDFRel.id.fieldId DESC, vLegalDFRel.id.docId DESC";
	public static final String ORDER_BY_SQL = " ORDER BY VLegalDFRel.fieldId DESC, VLegalDFRel.docId DESC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(vn.gov.hoabinh.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.gov.hoabinh.model.VLegalDFRel"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(vn.gov.hoabinh.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.gov.hoabinh.model.VLegalDFRel"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(vn.gov.hoabinh.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.vn.gov.hoabinh.model.VLegalDFRel"),
			true);
	public static final long DOCID_COLUMN_BITMASK = 1L;
	public static final long FIELDID_COLUMN_BITMASK = 2L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(vn.gov.hoabinh.service.util.ServiceProps.get(
				"lock.expiration.time.vn.gov.hoabinh.model.VLegalDFRel"));

	public VLegalDFRelModelImpl() {
	}

	@Override
	public VLegalDFRelPK getPrimaryKey() {
		return new VLegalDFRelPK(_fieldId, _docId);
	}

	@Override
	public void setPrimaryKey(VLegalDFRelPK primaryKey) {
		setFieldId(primaryKey.fieldId);
		setDocId(primaryKey.docId);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return new VLegalDFRelPK(_fieldId, _docId);
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((VLegalDFRelPK)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return VLegalDFRel.class;
	}

	@Override
	public String getModelClassName() {
		return VLegalDFRel.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("fieldId", getFieldId());
		attributes.put("docId", getDocId());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String fieldId = (String)attributes.get("fieldId");

		if (fieldId != null) {
			setFieldId(fieldId);
		}

		String docId = (String)attributes.get("docId");

		if (docId != null) {
			setDocId(docId);
		}
	}

	@Override
	public String getFieldId() {
		if (_fieldId == null) {
			return StringPool.BLANK;
		}
		else {
			return _fieldId;
		}
	}

	@Override
	public void setFieldId(String fieldId) {
		_columnBitmask = -1L;

		if (_originalFieldId == null) {
			_originalFieldId = _fieldId;
		}

		_fieldId = fieldId;
	}

	public String getOriginalFieldId() {
		return GetterUtil.getString(_originalFieldId);
	}

	@Override
	public String getDocId() {
		if (_docId == null) {
			return StringPool.BLANK;
		}
		else {
			return _docId;
		}
	}

	@Override
	public void setDocId(String docId) {
		_columnBitmask = -1L;

		if (_originalDocId == null) {
			_originalDocId = _docId;
		}

		_docId = docId;
	}

	public String getOriginalDocId() {
		return GetterUtil.getString(_originalDocId);
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public VLegalDFRel toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (VLegalDFRel)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		VLegalDFRelImpl vLegalDFRelImpl = new VLegalDFRelImpl();

		vLegalDFRelImpl.setFieldId(getFieldId());
		vLegalDFRelImpl.setDocId(getDocId());

		vLegalDFRelImpl.resetOriginalValues();

		return vLegalDFRelImpl;
	}

	@Override
	public int compareTo(VLegalDFRel vLegalDFRel) {
		int value = 0;

		value = getFieldId().compareTo(vLegalDFRel.getFieldId());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		value = getDocId().compareTo(vLegalDFRel.getDocId());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof VLegalDFRel)) {
			return false;
		}

		VLegalDFRel vLegalDFRel = (VLegalDFRel)obj;

		VLegalDFRelPK primaryKey = vLegalDFRel.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		VLegalDFRelModelImpl vLegalDFRelModelImpl = this;

		vLegalDFRelModelImpl._originalFieldId = vLegalDFRelModelImpl._fieldId;

		vLegalDFRelModelImpl._originalDocId = vLegalDFRelModelImpl._docId;

		vLegalDFRelModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<VLegalDFRel> toCacheModel() {
		VLegalDFRelCacheModel vLegalDFRelCacheModel = new VLegalDFRelCacheModel();

		vLegalDFRelCacheModel.vLegalDFRelPK = getPrimaryKey();

		vLegalDFRelCacheModel.fieldId = getFieldId();

		String fieldId = vLegalDFRelCacheModel.fieldId;

		if ((fieldId != null) && (fieldId.length() == 0)) {
			vLegalDFRelCacheModel.fieldId = null;
		}

		vLegalDFRelCacheModel.docId = getDocId();

		String docId = vLegalDFRelCacheModel.docId;

		if ((docId != null) && (docId.length() == 0)) {
			vLegalDFRelCacheModel.docId = null;
		}

		return vLegalDFRelCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{fieldId=");
		sb.append(getFieldId());
		sb.append(", docId=");
		sb.append(getDocId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append("vn.gov.hoabinh.model.VLegalDFRel");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>fieldId</column-name><column-value><![CDATA[");
		sb.append(getFieldId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>docId</column-name><column-value><![CDATA[");
		sb.append(getDocId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = VLegalDFRel.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			VLegalDFRel.class
		};
	private String _fieldId;
	private String _originalFieldId;
	private String _docId;
	private String _originalDocId;
	private long _columnBitmask;
	private VLegalDFRel _escapedModel;
}