/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gov.hoabinh.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import vn.gov.hoabinh.model.VLegalAttachedMessage;
import vn.gov.hoabinh.model.VLegalAttachedMessageModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the VLegalAttachedMessage service. Represents a row in the &quot;VLegalAttachedMessage&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link VLegalAttachedMessageModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VLegalAttachedMessageImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see VLegalAttachedMessageImpl
 * @see VLegalAttachedMessage
 * @see VLegalAttachedMessageModel
 * @generated
 */
@ProviderType
public class VLegalAttachedMessageModelImpl extends BaseModelImpl<VLegalAttachedMessage>
	implements VLegalAttachedMessageModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a v legal attached message model instance should use the {@link VLegalAttachedMessage} interface instead.
	 */
	public static final String TABLE_NAME = "VLegalAttachedMessage";
	public static final Object[][] TABLE_COLUMNS = {
			{ "messageId", Types.VARCHAR },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "createdDate", Types.TIMESTAMP },
			{ "createdByUser", Types.BIGINT },
			{ "articleId", Types.VARCHAR },
			{ "content", Types.VARCHAR },
			{ "readMessage", Types.BOOLEAN }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("messageId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createdDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("createdByUser", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("articleId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("content", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("readMessage", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE = "create table VLegalAttachedMessage (messageId VARCHAR(75) not null primary key,groupId LONG,companyId LONG,userId LONG,createdDate DATE null,createdByUser LONG,articleId VARCHAR(75) null,content VARCHAR(75) null,readMessage BOOLEAN)";
	public static final String TABLE_SQL_DROP = "drop table VLegalAttachedMessage";
	public static final String ORDER_BY_JPQL = " ORDER BY vLegalAttachedMessage.createdDate DESC";
	public static final String ORDER_BY_SQL = " ORDER BY VLegalAttachedMessage.createdDate DESC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(vn.gov.hoabinh.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.gov.hoabinh.model.VLegalAttachedMessage"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(vn.gov.hoabinh.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.gov.hoabinh.model.VLegalAttachedMessage"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(vn.gov.hoabinh.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.vn.gov.hoabinh.model.VLegalAttachedMessage"),
			true);
	public static final long ARTICLEID_COLUMN_BITMASK = 1L;
	public static final long GROUPID_COLUMN_BITMASK = 2L;
	public static final long READMESSAGE_COLUMN_BITMASK = 4L;
	public static final long CREATEDDATE_COLUMN_BITMASK = 8L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(vn.gov.hoabinh.service.util.ServiceProps.get(
				"lock.expiration.time.vn.gov.hoabinh.model.VLegalAttachedMessage"));

	public VLegalAttachedMessageModelImpl() {
	}

	@Override
	public String getPrimaryKey() {
		return _messageId;
	}

	@Override
	public void setPrimaryKey(String primaryKey) {
		setMessageId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _messageId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((String)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return VLegalAttachedMessage.class;
	}

	@Override
	public String getModelClassName() {
		return VLegalAttachedMessage.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("messageId", getMessageId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("createdDate", getCreatedDate());
		attributes.put("createdByUser", getCreatedByUser());
		attributes.put("articleId", getArticleId());
		attributes.put("content", getContent());
		attributes.put("readMessage", getReadMessage());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String messageId = (String)attributes.get("messageId");

		if (messageId != null) {
			setMessageId(messageId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Date createdDate = (Date)attributes.get("createdDate");

		if (createdDate != null) {
			setCreatedDate(createdDate);
		}

		Long createdByUser = (Long)attributes.get("createdByUser");

		if (createdByUser != null) {
			setCreatedByUser(createdByUser);
		}

		String articleId = (String)attributes.get("articleId");

		if (articleId != null) {
			setArticleId(articleId);
		}

		String content = (String)attributes.get("content");

		if (content != null) {
			setContent(content);
		}

		Boolean readMessage = (Boolean)attributes.get("readMessage");

		if (readMessage != null) {
			setReadMessage(readMessage);
		}
	}

	@Override
	public String getMessageId() {
		if (_messageId == null) {
			return StringPool.BLANK;
		}
		else {
			return _messageId;
		}
	}

	@Override
	public void setMessageId(String messageId) {
		_messageId = messageId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public Date getCreatedDate() {
		return _createdDate;
	}

	@Override
	public void setCreatedDate(Date createdDate) {
		_columnBitmask = -1L;

		_createdDate = createdDate;
	}

	@Override
	public long getCreatedByUser() {
		return _createdByUser;
	}

	@Override
	public void setCreatedByUser(long createdByUser) {
		_createdByUser = createdByUser;
	}

	@Override
	public String getArticleId() {
		if (_articleId == null) {
			return StringPool.BLANK;
		}
		else {
			return _articleId;
		}
	}

	@Override
	public void setArticleId(String articleId) {
		_columnBitmask |= ARTICLEID_COLUMN_BITMASK;

		if (_originalArticleId == null) {
			_originalArticleId = _articleId;
		}

		_articleId = articleId;
	}

	public String getOriginalArticleId() {
		return GetterUtil.getString(_originalArticleId);
	}

	@Override
	public String getContent() {
		if (_content == null) {
			return StringPool.BLANK;
		}
		else {
			return _content;
		}
	}

	@Override
	public void setContent(String content) {
		_content = content;
	}

	@Override
	public boolean getReadMessage() {
		return _readMessage;
	}

	@Override
	public boolean isReadMessage() {
		return _readMessage;
	}

	@Override
	public void setReadMessage(boolean readMessage) {
		_columnBitmask |= READMESSAGE_COLUMN_BITMASK;

		if (!_setOriginalReadMessage) {
			_setOriginalReadMessage = true;

			_originalReadMessage = _readMessage;
		}

		_readMessage = readMessage;
	}

	public boolean getOriginalReadMessage() {
		return _originalReadMessage;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public VLegalAttachedMessage toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (VLegalAttachedMessage)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		VLegalAttachedMessageImpl vLegalAttachedMessageImpl = new VLegalAttachedMessageImpl();

		vLegalAttachedMessageImpl.setMessageId(getMessageId());
		vLegalAttachedMessageImpl.setGroupId(getGroupId());
		vLegalAttachedMessageImpl.setCompanyId(getCompanyId());
		vLegalAttachedMessageImpl.setUserId(getUserId());
		vLegalAttachedMessageImpl.setCreatedDate(getCreatedDate());
		vLegalAttachedMessageImpl.setCreatedByUser(getCreatedByUser());
		vLegalAttachedMessageImpl.setArticleId(getArticleId());
		vLegalAttachedMessageImpl.setContent(getContent());
		vLegalAttachedMessageImpl.setReadMessage(getReadMessage());

		vLegalAttachedMessageImpl.resetOriginalValues();

		return vLegalAttachedMessageImpl;
	}

	@Override
	public int compareTo(VLegalAttachedMessage vLegalAttachedMessage) {
		int value = 0;

		value = DateUtil.compareTo(getCreatedDate(),
				vLegalAttachedMessage.getCreatedDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof VLegalAttachedMessage)) {
			return false;
		}

		VLegalAttachedMessage vLegalAttachedMessage = (VLegalAttachedMessage)obj;

		String primaryKey = vLegalAttachedMessage.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		VLegalAttachedMessageModelImpl vLegalAttachedMessageModelImpl = this;

		vLegalAttachedMessageModelImpl._originalGroupId = vLegalAttachedMessageModelImpl._groupId;

		vLegalAttachedMessageModelImpl._setOriginalGroupId = false;

		vLegalAttachedMessageModelImpl._originalArticleId = vLegalAttachedMessageModelImpl._articleId;

		vLegalAttachedMessageModelImpl._originalReadMessage = vLegalAttachedMessageModelImpl._readMessage;

		vLegalAttachedMessageModelImpl._setOriginalReadMessage = false;

		vLegalAttachedMessageModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<VLegalAttachedMessage> toCacheModel() {
		VLegalAttachedMessageCacheModel vLegalAttachedMessageCacheModel = new VLegalAttachedMessageCacheModel();

		vLegalAttachedMessageCacheModel.messageId = getMessageId();

		String messageId = vLegalAttachedMessageCacheModel.messageId;

		if ((messageId != null) && (messageId.length() == 0)) {
			vLegalAttachedMessageCacheModel.messageId = null;
		}

		vLegalAttachedMessageCacheModel.groupId = getGroupId();

		vLegalAttachedMessageCacheModel.companyId = getCompanyId();

		vLegalAttachedMessageCacheModel.userId = getUserId();

		Date createdDate = getCreatedDate();

		if (createdDate != null) {
			vLegalAttachedMessageCacheModel.createdDate = createdDate.getTime();
		}
		else {
			vLegalAttachedMessageCacheModel.createdDate = Long.MIN_VALUE;
		}

		vLegalAttachedMessageCacheModel.createdByUser = getCreatedByUser();

		vLegalAttachedMessageCacheModel.articleId = getArticleId();

		String articleId = vLegalAttachedMessageCacheModel.articleId;

		if ((articleId != null) && (articleId.length() == 0)) {
			vLegalAttachedMessageCacheModel.articleId = null;
		}

		vLegalAttachedMessageCacheModel.content = getContent();

		String content = vLegalAttachedMessageCacheModel.content;

		if ((content != null) && (content.length() == 0)) {
			vLegalAttachedMessageCacheModel.content = null;
		}

		vLegalAttachedMessageCacheModel.readMessage = getReadMessage();

		return vLegalAttachedMessageCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(19);

		sb.append("{messageId=");
		sb.append(getMessageId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", createdDate=");
		sb.append(getCreatedDate());
		sb.append(", createdByUser=");
		sb.append(getCreatedByUser());
		sb.append(", articleId=");
		sb.append(getArticleId());
		sb.append(", content=");
		sb.append(getContent());
		sb.append(", readMessage=");
		sb.append(getReadMessage());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(31);

		sb.append("<model><model-name>");
		sb.append("vn.gov.hoabinh.model.VLegalAttachedMessage");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>messageId</column-name><column-value><![CDATA[");
		sb.append(getMessageId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdDate</column-name><column-value><![CDATA[");
		sb.append(getCreatedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdByUser</column-name><column-value><![CDATA[");
		sb.append(getCreatedByUser());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>articleId</column-name><column-value><![CDATA[");
		sb.append(getArticleId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>content</column-name><column-value><![CDATA[");
		sb.append(getContent());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>readMessage</column-name><column-value><![CDATA[");
		sb.append(getReadMessage());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = VLegalAttachedMessage.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			VLegalAttachedMessage.class
		};
	private String _messageId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _userId;
	private Date _createdDate;
	private long _createdByUser;
	private String _articleId;
	private String _originalArticleId;
	private String _content;
	private boolean _readMessage;
	private boolean _originalReadMessage;
	private boolean _setOriginalReadMessage;
	private long _columnBitmask;
	private VLegalAttachedMessage _escapedModel;
}