/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gov.hoabinh.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import vn.gov.hoabinh.model.VLegalField;
import vn.gov.hoabinh.model.VLegalFieldModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the VLegalField service. Represents a row in the &quot;VLegalField&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link VLegalFieldModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VLegalFieldImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see VLegalFieldImpl
 * @see VLegalField
 * @see VLegalFieldModel
 * @generated
 */
@ProviderType
public class VLegalFieldModelImpl extends BaseModelImpl<VLegalField>
	implements VLegalFieldModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a v legal field model instance should use the {@link VLegalField} interface instead.
	 */
	public static final String TABLE_NAME = "VLegalField";
	public static final Object[][] TABLE_COLUMNS = {
			{ "fieldId", Types.VARCHAR },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "createdDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "createdByUser", Types.BIGINT },
			{ "modifiedByUser", Types.BIGINT },
			{ "name", Types.VARCHAR },
			{ "description", Types.VARCHAR },
			{ "language", Types.VARCHAR },
			{ "statusField", Types.BOOLEAN },
			{ "rssable", Types.BOOLEAN }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("fieldId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createdDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("createdByUser", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedByUser", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("language", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusField", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("rssable", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE = "create table VLegalField (fieldId VARCHAR(75) not null primary key,groupId LONG,companyId LONG,userId LONG,createdDate DATE null,modifiedDate DATE null,createdByUser LONG,modifiedByUser LONG,name VARCHAR(75) null,description VARCHAR(75) null,language VARCHAR(75) null,statusField BOOLEAN,rssable BOOLEAN)";
	public static final String TABLE_SQL_DROP = "drop table VLegalField";
	public static final String ORDER_BY_JPQL = " ORDER BY vLegalField.name ASC";
	public static final String ORDER_BY_SQL = " ORDER BY VLegalField.name ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(vn.gov.hoabinh.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.gov.hoabinh.model.VLegalField"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(vn.gov.hoabinh.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.gov.hoabinh.model.VLegalField"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(vn.gov.hoabinh.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.vn.gov.hoabinh.model.VLegalField"),
			true);
	public static final long FIELDID_COLUMN_BITMASK = 1L;
	public static final long GROUPID_COLUMN_BITMASK = 2L;
	public static final long LANGUAGE_COLUMN_BITMASK = 4L;
	public static final long RSSABLE_COLUMN_BITMASK = 8L;
	public static final long STATUSFIELD_COLUMN_BITMASK = 16L;
	public static final long NAME_COLUMN_BITMASK = 32L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(vn.gov.hoabinh.service.util.ServiceProps.get(
				"lock.expiration.time.vn.gov.hoabinh.model.VLegalField"));

	public VLegalFieldModelImpl() {
	}

	@Override
	public String getPrimaryKey() {
		return _fieldId;
	}

	@Override
	public void setPrimaryKey(String primaryKey) {
		setFieldId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _fieldId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((String)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return VLegalField.class;
	}

	@Override
	public String getModelClassName() {
		return VLegalField.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("fieldId", getFieldId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("createdDate", getCreatedDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("createdByUser", getCreatedByUser());
		attributes.put("modifiedByUser", getModifiedByUser());
		attributes.put("name", getName());
		attributes.put("description", getDescription());
		attributes.put("language", getLanguage());
		attributes.put("statusField", getStatusField());
		attributes.put("rssable", getRssable());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String fieldId = (String)attributes.get("fieldId");

		if (fieldId != null) {
			setFieldId(fieldId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Date createdDate = (Date)attributes.get("createdDate");

		if (createdDate != null) {
			setCreatedDate(createdDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long createdByUser = (Long)attributes.get("createdByUser");

		if (createdByUser != null) {
			setCreatedByUser(createdByUser);
		}

		Long modifiedByUser = (Long)attributes.get("modifiedByUser");

		if (modifiedByUser != null) {
			setModifiedByUser(modifiedByUser);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}

		String description = (String)attributes.get("description");

		if (description != null) {
			setDescription(description);
		}

		String language = (String)attributes.get("language");

		if (language != null) {
			setLanguage(language);
		}

		Boolean statusField = (Boolean)attributes.get("statusField");

		if (statusField != null) {
			setStatusField(statusField);
		}

		Boolean rssable = (Boolean)attributes.get("rssable");

		if (rssable != null) {
			setRssable(rssable);
		}
	}

	@Override
	public String getFieldId() {
		if (_fieldId == null) {
			return StringPool.BLANK;
		}
		else {
			return _fieldId;
		}
	}

	@Override
	public void setFieldId(String fieldId) {
		_columnBitmask |= FIELDID_COLUMN_BITMASK;

		if (_originalFieldId == null) {
			_originalFieldId = _fieldId;
		}

		_fieldId = fieldId;
	}

	public String getOriginalFieldId() {
		return GetterUtil.getString(_originalFieldId);
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public Date getCreatedDate() {
		return _createdDate;
	}

	@Override
	public void setCreatedDate(Date createdDate) {
		_createdDate = createdDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@Override
	public long getCreatedByUser() {
		return _createdByUser;
	}

	@Override
	public void setCreatedByUser(long createdByUser) {
		_createdByUser = createdByUser;
	}

	@Override
	public long getModifiedByUser() {
		return _modifiedByUser;
	}

	@Override
	public void setModifiedByUser(long modifiedByUser) {
		_modifiedByUser = modifiedByUser;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_columnBitmask = -1L;

		_name = name;
	}

	@Override
	public String getDescription() {
		if (_description == null) {
			return StringPool.BLANK;
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	@Override
	public String getLanguage() {
		if (_language == null) {
			return StringPool.BLANK;
		}
		else {
			return _language;
		}
	}

	@Override
	public void setLanguage(String language) {
		_columnBitmask |= LANGUAGE_COLUMN_BITMASK;

		if (_originalLanguage == null) {
			_originalLanguage = _language;
		}

		_language = language;
	}

	public String getOriginalLanguage() {
		return GetterUtil.getString(_originalLanguage);
	}

	@Override
	public boolean getStatusField() {
		return _statusField;
	}

	@Override
	public boolean isStatusField() {
		return _statusField;
	}

	@Override
	public void setStatusField(boolean statusField) {
		_columnBitmask |= STATUSFIELD_COLUMN_BITMASK;

		if (!_setOriginalStatusField) {
			_setOriginalStatusField = true;

			_originalStatusField = _statusField;
		}

		_statusField = statusField;
	}

	public boolean getOriginalStatusField() {
		return _originalStatusField;
	}

	@Override
	public boolean getRssable() {
		return _rssable;
	}

	@Override
	public boolean isRssable() {
		return _rssable;
	}

	@Override
	public void setRssable(boolean rssable) {
		_columnBitmask |= RSSABLE_COLUMN_BITMASK;

		if (!_setOriginalRssable) {
			_setOriginalRssable = true;

			_originalRssable = _rssable;
		}

		_rssable = rssable;
	}

	public boolean getOriginalRssable() {
		return _originalRssable;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public VLegalField toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (VLegalField)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		VLegalFieldImpl vLegalFieldImpl = new VLegalFieldImpl();

		vLegalFieldImpl.setFieldId(getFieldId());
		vLegalFieldImpl.setGroupId(getGroupId());
		vLegalFieldImpl.setCompanyId(getCompanyId());
		vLegalFieldImpl.setUserId(getUserId());
		vLegalFieldImpl.setCreatedDate(getCreatedDate());
		vLegalFieldImpl.setModifiedDate(getModifiedDate());
		vLegalFieldImpl.setCreatedByUser(getCreatedByUser());
		vLegalFieldImpl.setModifiedByUser(getModifiedByUser());
		vLegalFieldImpl.setName(getName());
		vLegalFieldImpl.setDescription(getDescription());
		vLegalFieldImpl.setLanguage(getLanguage());
		vLegalFieldImpl.setStatusField(getStatusField());
		vLegalFieldImpl.setRssable(getRssable());

		vLegalFieldImpl.resetOriginalValues();

		return vLegalFieldImpl;
	}

	@Override
	public int compareTo(VLegalField vLegalField) {
		int value = 0;

		value = getName().compareTo(vLegalField.getName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof VLegalField)) {
			return false;
		}

		VLegalField vLegalField = (VLegalField)obj;

		String primaryKey = vLegalField.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		VLegalFieldModelImpl vLegalFieldModelImpl = this;

		vLegalFieldModelImpl._originalFieldId = vLegalFieldModelImpl._fieldId;

		vLegalFieldModelImpl._originalGroupId = vLegalFieldModelImpl._groupId;

		vLegalFieldModelImpl._setOriginalGroupId = false;

		vLegalFieldModelImpl._originalLanguage = vLegalFieldModelImpl._language;

		vLegalFieldModelImpl._originalStatusField = vLegalFieldModelImpl._statusField;

		vLegalFieldModelImpl._setOriginalStatusField = false;

		vLegalFieldModelImpl._originalRssable = vLegalFieldModelImpl._rssable;

		vLegalFieldModelImpl._setOriginalRssable = false;

		vLegalFieldModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<VLegalField> toCacheModel() {
		VLegalFieldCacheModel vLegalFieldCacheModel = new VLegalFieldCacheModel();

		vLegalFieldCacheModel.fieldId = getFieldId();

		String fieldId = vLegalFieldCacheModel.fieldId;

		if ((fieldId != null) && (fieldId.length() == 0)) {
			vLegalFieldCacheModel.fieldId = null;
		}

		vLegalFieldCacheModel.groupId = getGroupId();

		vLegalFieldCacheModel.companyId = getCompanyId();

		vLegalFieldCacheModel.userId = getUserId();

		Date createdDate = getCreatedDate();

		if (createdDate != null) {
			vLegalFieldCacheModel.createdDate = createdDate.getTime();
		}
		else {
			vLegalFieldCacheModel.createdDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			vLegalFieldCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			vLegalFieldCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		vLegalFieldCacheModel.createdByUser = getCreatedByUser();

		vLegalFieldCacheModel.modifiedByUser = getModifiedByUser();

		vLegalFieldCacheModel.name = getName();

		String name = vLegalFieldCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			vLegalFieldCacheModel.name = null;
		}

		vLegalFieldCacheModel.description = getDescription();

		String description = vLegalFieldCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			vLegalFieldCacheModel.description = null;
		}

		vLegalFieldCacheModel.language = getLanguage();

		String language = vLegalFieldCacheModel.language;

		if ((language != null) && (language.length() == 0)) {
			vLegalFieldCacheModel.language = null;
		}

		vLegalFieldCacheModel.statusField = getStatusField();

		vLegalFieldCacheModel.rssable = getRssable();

		return vLegalFieldCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(27);

		sb.append("{fieldId=");
		sb.append(getFieldId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", createdDate=");
		sb.append(getCreatedDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", createdByUser=");
		sb.append(getCreatedByUser());
		sb.append(", modifiedByUser=");
		sb.append(getModifiedByUser());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", description=");
		sb.append(getDescription());
		sb.append(", language=");
		sb.append(getLanguage());
		sb.append(", statusField=");
		sb.append(getStatusField());
		sb.append(", rssable=");
		sb.append(getRssable());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(43);

		sb.append("<model><model-name>");
		sb.append("vn.gov.hoabinh.model.VLegalField");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>fieldId</column-name><column-value><![CDATA[");
		sb.append(getFieldId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdDate</column-name><column-value><![CDATA[");
		sb.append(getCreatedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdByUser</column-name><column-value><![CDATA[");
		sb.append(getCreatedByUser());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedByUser</column-name><column-value><![CDATA[");
		sb.append(getModifiedByUser());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>description</column-name><column-value><![CDATA[");
		sb.append(getDescription());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>language</column-name><column-value><![CDATA[");
		sb.append(getLanguage());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>statusField</column-name><column-value><![CDATA[");
		sb.append(getStatusField());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>rssable</column-name><column-value><![CDATA[");
		sb.append(getRssable());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = VLegalField.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			VLegalField.class
		};
	private String _fieldId;
	private String _originalFieldId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _userId;
	private Date _createdDate;
	private Date _modifiedDate;
	private long _createdByUser;
	private long _modifiedByUser;
	private String _name;
	private String _description;
	private String _language;
	private String _originalLanguage;
	private boolean _statusField;
	private boolean _originalStatusField;
	private boolean _setOriginalStatusField;
	private boolean _rssable;
	private boolean _originalRssable;
	private boolean _setOriginalRssable;
	private long _columnBitmask;
	private VLegalField _escapedModel;
}